"""Domain 2 practice bank: Implement generative AI and agentic solutions (30-35%)."""
from d12 import QUESTIONS as OLD
from bank_d1 import T
L = "https://learn.microsoft.com/en-us/azure/foundry/"
SK = {"q9": "Build agents", "q10": "Build agents", "q11": "Build agents", "q12": "Optimise and operationalise", "q13": "Build generative apps",
      "q14": "Build agents", "q15": "Optimise and operationalise", "q16": "Build agents", "q17": "Optimise and operationalise", "q18": "Build generative apps"}
LEARN = {"q9": L+"agents/overview", "q10": L+"agents/how-to/tools/agent-to-agent", "q11": L+"agents/how-to/tools/model-context-protocol",
         "q12": L+"openai/how-to/reasoning", "q13": "https://learn.microsoft.com/en-us/agent-framework/overview/", "q14": L+"agents/how-to/tools/bing-tools",
         "q15": L+"observability/how-to/trace-agent-setup", "q16": L+"agents/concepts/toolbox-overview", "q17": L+"concepts/built-in-evaluators",
         "q18": L+"openai/api-version-lifecycle"}
ITEMS = []
for q in OLD:
    if q["d"] != 2: continue
    ITEMS.append(dict(id="d2-" + q["id"], type="single", skill=SK[q["id"]], stem=q["stem"], options=q["options"], answer=q["answer"],
                      runner=q["runner"], runnerWhy=q["runnerWhy"], think=q["think"], eli5=q["eli5"], learn=LEARN[q["id"]]))
ITEMS += [
dict(id="d2-n1", type="single", skill="Build generative apps",
 stem="An agent answers policy questions through the Azure AI Search tool with query_type set to vector. Answers often miss clauses asked for by number, such as 4.2.1. What do you change?",
 options=["Set query_type to vector_semantic_hybrid","Raise top_k from 5 to 50 results","Replace the Search tool with file search","Store each clause in agent memory instead"],
 answer=0, runner=1, runnerWhy="it helps when the right passage ranks just below the cut-off, not when vector search can't match an exact number.",
 think=T("That retrieving more results fixes a matching problem. Vector search matches meaning; exact codes need keyword matching too.",
  [["Exact codes and IDs missed","Pure vector search","Hybrid (keyword + vector)"],["Right passage ranks 6th or lower","Cut-off too tight","Raise top_k"],["Shared company content","Knowledge source","Search or Foundry IQ, not file search"]],
  [["\"query_type set to vector\"","No keyword matching at all."],["\"clauses asked for by number\"","Exact strings: keyword matching is what's missing."]],
  "Exact identifiers need keyword matching: hybrid. The Search tool's default is vector_semantic_hybrid.",
  "Implement retrieval-augmented generation (RAG) in an application."),
 eli5="Searching by meaning won't find 'shelf 4.2.1'; you need the label too.", learn=L+"agents/how-to/tools/ai-search"),
dict(id="d2-n2", type="single", skill="Build generative apps",
 stem="Before release, you want to score each RAG answer from 1 to 5 for whether its claims are supported by the retrieved passages. A judge model is deployed. Which evaluator do you use?",
 options=["Groundedness evaluator","Groundedness Pro evaluator","Relevance evaluator","Coherence evaluator"],
 answer=0, runner=1, runnerWhy="it wins when you want pass/fail without deploying a judge model.",
 think=T("That fabrication shows up as low relevance or coherence. An answer can be relevant and fluent and still invent facts: that's groundedness.",
  [["Claims not in the sources","Fabrication","Groundedness (1–5)"],["Pass/fail, no judge","Same question, different output","Groundedness Pro"],["Answer off the question","Relevance","Relevance evaluator"]],
  [["\"score each ... from 1 to 5\"","A scale, not pass/fail."],["\"A judge model is deployed\"","So the judge-based evaluator is available."]],
  "Supported by sources = groundedness. 1–5 with a judge = Groundedness; pass/fail without one = Groundedness Pro.",
  "Evaluate models and apps, including detecting fabrications, relevance, quality, and safety."),
 eli5="A confident essay with made-up quotes is well written, but not grounded.", learn=L+"concepts/built-in-evaluators"),
dict(id="d2-m1", type="multi", pick=2, skill="Build agents",
 stem="An agent must call an internal claims REST API that publishes an OpenAPI spec, and run Python to build a settlement table from the results. Which two tools do you add?",
 options=["OpenAPI tool for the claims API","Code interpreter for the Python step","Azure Functions tool for the claims API","Grounding with Bing Search for data","File search over the claims API spec"],
 answer=[0, 1], runner=2, runnerWhy="it fits when your own code must run in Azure Functions, and it needs the Standard setup; with an OpenAPI spec, the OpenAPI tool is direct.",
 think=T("That every API call needs custom code. An API with an OpenAPI spec plugs in directly as a tool.",
  [["REST API with a spec","Direct integration","OpenAPI tool"],["Run Python, make files or tables","Sandboxed execution","Code interpreter"],["Your own logic in Azure","Queue-based function","Azure Functions tool (Standard setup)"]],
  [["\"publishes an OpenAPI spec\"","OpenAPI tool."],["\"run Python to build a settlement table\"","Code interpreter."]],
  "API with a spec → OpenAPI tool. Run code → code interpreter. Your own Azure logic → Functions tool.",
  "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions."),
 eli5="Use the phone to call the office, and the calculator to do the sums.", learn=L+"agents/overview"),
dict(id="d2-m2", type="multi", pick=2, skill="Build agents",
 stem="Which two pairings of need and knowledge option are correct for a Foundry agent?",
 options=["File search for documents a user uploads in the chat","Foundry IQ for curated company content across sources","Memory for policy wordings shared by every customer","Foundry IQ for files a user uploads mid-conversation","File search for what the agent learns about a user"],
 answer=[0, 1], runner=2, runnerWhy="memory is real, but it's for what the agent learns about a user, not shared company content.",
 think=T("That the three options are interchangeable stores. Each matches one source of knowledge.",
  [["User uploads a file now","Conversation-scoped","File search"],["Shared, curated company content","Organisational knowledge","Foundry IQ"],["Learned about a user over time","Personal, persistent","Memory (preview)"]],
  [["\"documents a user uploads\"","File search."],["\"curated company content across sources\"","Foundry IQ."]],
  "Memory = about the user; Foundry IQ = curated organisational content; file search = files the user provides.",
  "Choose appropriate memory, tool, and knowledge integration services for agent solutions."),
 eli5="A diary about you, the company library, and the papers you just handed over.", learn=L+"agents/concepts/what-is-foundry-iq"),
dict(id="d2-y1", type="yesno", skill="Build agents",
 stem="For each statement about evaluating agents in Foundry, select Yes if it's true.",
 statements=[dict(text="Task adherence measures whether the agent follows its instructions.", answer=True, why="That's exactly what it scores."),
  dict(text="Tool call accuracy checks whether the right tool was called with the right arguments.", answer=True, why="It evaluates the tool calls themselves."),
  dict(text="A high coherence score shows the agent used its tools correctly.", answer=False, why="Coherence is about readable language, not tool use."),
  dict(text="An evaluation can run at the turn level or the conversation level.", answer=True, why="Turn is the default; all evaluators in one run must support the chosen level.")],
 think=T("That any quality score covers agent behaviour. Agent behaviour has its own evaluators.",
  [["Ignored instructions","Behaviour","Task adherence"],["Wrong tool or arguments","Trajectory","Tool call accuracy"],["Misread the request","Understanding","Intent resolution"]],
  None, "Language quality ≠ agent behaviour. Use task adherence, intent resolution and tool call accuracy for agents.",
  "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis."),
 eli5="A polite waiter who brings the wrong dish still got the order wrong.", learn=L+"concepts/built-in-evaluators"),
dict(id="d2-y2", type="yesno", skill="Build agents",
 stem="For each statement about MCP tools in Foundry Agent Service, select Yes if it's true.",
 statements=[dict(text="If you don't set require_approval, every MCP tool call needs approval.", answer=True, why="The default is always."),
  dict(text="A non-streaming MCP tool call can run for up to ten minutes.", answer=False, why="It times out at 100 seconds; use background mode for longer work."),
  dict(text="A private MCP server reachable only inside your network needs the Standard setup with your own VNet.", answer=True, why="Outbound private reach needs Standard + VNet."),
  dict(text="A toolbox lets many agents use the same curated tools through one MCP endpoint.", answer=True, why="That's what a toolbox is for.")],
 think=T("That MCP in Foundry behaves like a local MCP server with no limits. Foundry adds approval defaults, timeouts and network rules.",
  [["Writes need a person","Approval","require_approval (default always)"],["Long-running tool","Timeout","Background mode"],["Server on private network","Outbound reach","Standard + VNet"]],
  None, "MCP in Foundry: approval defaults to always; 100-second limit without streaming; private servers need Standard + VNet.",
  "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions."),
 eli5="The phone line has a supervisor listening in by default, and calls drop after 100 seconds.", learn=L+"agents/how-to/tools/model-context-protocol"),
dict(id="d2-o1", type="order", skill="Build agents",
 stem="You create a prompt agent in code and then chat with it. Put the five steps in order.",
 pool=["Create AIProjectClient with DefaultAzureCredential","Call agents.create_version with a PromptAgentDefinition","Get an OpenAI client bound to the agent's name","Create a conversation","Call responses.create with the conversation ID","Create a thread for the chat","Create a run on the thread"],
 answer=[0, 1, 2, 3, 4],
 think=T("That agents v2 still use threads and runs. They use conversations and responses.",
  [["Need a client","Connection","AIProjectClient"],["Need an agent","Definition","create_version"],["Need history","State","conversations.create, then responses.create"]],
  [["\"prompt agent in code\"","The v2 API: no threads, no runs."]],
  "Client → agent version → agent-bound client → conversation → response.",
  "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 eli5="Open the office, hire the clerk, call the clerk, open a case file, then ask your question."),
dict(id="d2-c1", type="code", skill="Build agents",
 stem="Complete the code to create a prompt agent and send one message in a new conversation.",
 code='agent = project.agents.[[0]](\n    agent_name="fnol-intake",\n    definition=PromptAgentDefinition(model="gpt-5-mini", instructions=rules))\noa = project.get_openai_client(agent_name="fnol-intake")\nconv = oa.[[1]].create()\nr = oa.responses.create([[2]]=conv.id, input="I had an accident today")',
 blanks=[dict(options=["create_version","create_agent","create_assistant"], answer=0, why="v2 creates agent versions."),
         dict(options=["conversations","threads","sessions"], answer=0, why="v2 keeps history in conversations."),
         dict(options=["conversation","thread_id","previous_response_id"], answer=0, why="responses.create takes the conversation ID to continue it.")],
 think=T("That the classic Assistants vocabulary still applies. Agents v2 renamed the objects.",
  [["Define the agent","Agent versions","create_version"],["Keep history","Conversations","conversations.create"],["Continue the chat","Conversation ID","conversation="]],
  None, "Agents v2: create_version, conversations, responses.",
  "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 eli5="Same shop, new signs on every door.", learn=L+"agents/overview"),
dict(id="d2-c2", type="code", skill="Build agents",
 stem="Complete the code so an MCP tool asks for approval on every call, and your app approves one request.",
 code='tool = MCPTool(server_label="claims", server_url=url, require_approval="[[0]]")\nr = oa.responses.create(model=m, input=q, tools=[tool])\nreq = next(i for i in r.output if i.type == "mcp_approval_request")\nr2 = oa.responses.create(model=m, tools=[tool], [[1]]=r.id,\n    input=[{"type": "[[2]]", "approve": True, "approval_request_id": req.id}])',
 blanks=[dict(options=["always","never","auto"], answer=0, why="every call needs approval (also the default)."),
         dict(options=["previous_response_id","conversation","thread_id"], answer=0, why="the approval continues the response that asked for it."),
         dict(options=["mcp_approval_response","function_call_output","tool_result"], answer=0, why="the item type that answers an mcp_approval_request; tool_result is the Claude API's name for a tool's output, not this.")],
 think=T("That an approval is answered like a tool result. It's its own item type, sent against the response that asked.",
  [["Model asks to call an MCP tool","Approval request","mcp_approval_response"],["Your function ran","Function output","function_call_output"],["Claude API tool output","Different API","tool_result"]],
  None, "MCP approval: require_approval → mcp_approval_request → mcp_approval_response with previous_response_id.",
  "Build autonomous or semiautonomous workflows with safeguards and approval flow controls."),
 eli5="When the assistant asks 'may I?', you answer the question, not hand over a finished report.", learn=L+"agents/how-to/tools/model-context-protocol"),
]
GOAL = ("An FNOL agent reads and updates claim records through one MCP server. **Goal:** every update must be confirmed by a claims handler "
        "before it runs, and read-only questions must be answered without waiting for anyone.")
def S(i, sol, ans, prem, apply, rule):
    return dict(id="d2-s" + str(i), type="solution", skill="Build agents", scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?",
                answer=ans, think=T(prem, [["Writes need a person","Per-tool approval","{\"always\": [update tools]}"],["Reads must not wait","Approval scope","Don't require approval on reads"],["Detect risky behaviour","Guardrail","Detection, not approval"]],
                apply, rule, "Build autonomous or semiautonomous workflows with safeguards and approval flow controls."),
                eli5="The manager signs the changes, not every question someone asks at the counter.", learn=L+"agents/how-to/tools/model-context-protocol")
ITEMS += [
 S(1, "Set require_approval to {\"always\": [\"update_claim\"]} on the MCP tool.", True, "That approval is all or nothing. It can be set per tool.",
   [["\"every update must be confirmed\"","update_claim always asks: met."],["\"read-only questions ... without waiting\"","Other tools don't ask: met."]], "Per-tool approval lists let reads flow and writes wait."),
 S(2, "Set require_approval to \"always\" on the MCP tool.", False, "That stricter is always safer. Here it breaks the second half of the goal.",
   [["\"every update must be confirmed\"","Met."],["\"read-only questions ... without waiting\"","Reads also wait for approval: not met."]], "Blanket approval blocks reads too."),
 S(3, "Set require_approval to \"never\" and add a Task Adherence guardrail at the tool call point.", False, "That a guardrail can stand in for a person. It detects risk; it doesn't ask a handler.",
   [["\"confirmed by a claims handler\"","No human confirms: not met."],["\"Task Adherence guardrail\"","Detection, not approval."]], "Human confirmation needs an approval flow, not a detector."),
]
BANK = dict(id="d2", title="Domain 2 · Implement generative AI and agentic solutions", minutes=44, items=ITEMS)
