"""D1 practice items: Foundry roles and access. All original; checked against Microsoft Learn RBAC for Foundry (22 Sep 2026)."""
from bank_d1 import T
L = "https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry"
SK = "Manage, monitor, secure"
NOTE = " NOTE: Each correct selection is worth one point."
def single(id, stem, options, runner, runnerWhy, think, eli5):
    return dict(id=id, type="single", skill=SK, stem=stem, options=options, answer=0, runner=runner, runnerWhy=runnerWhy, think=think, eli5=eli5, learn=L)

ROLE_MAP = [["Call agents only","Endpoint access","Foundry Agent Consumer"],["Build and evaluate","Data actions","Foundry User"],["Build + publish + add developers","Team lead","Foundry Project Manager"],["Set up resources, no building","Control plane","Foundry Account Owner"]]
ITEMS = [
single("d1-r1", "A developer has the Contributor role on the resource group that contains your Foundry resource. She can deploy models, but creating an agent in the project fails with a 403 error. You need to let her build and evaluate agents in that project, following least privilege. What should you assign?",
 ["Foundry User on the project","Foundry Owner on the Foundry resource","Owner on the resource group","Cognitive Services Contributor on the resource"], 1,
 "it works, because it includes data actions, but it also lets her create resources and assign roles, which she doesn't need.",
 T("That Contributor can do everything in a resource it manages. Contributor has no data actions, so it can deploy models but can't build agents.",
   ROLE_MAP, [["\"Contributor ... can deploy models\"","Control plane works."],["\"creating an agent ... fails with a 403\"","Data actions are missing."],["\"least privilege\"","Rules out Foundry Owner and Owner."]],
   "Owner and Contributor manage Foundry but can't build in it. Building needs Foundry User.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "Owning the building doesn't give you a desk in the office."),
single("d1-r2", "A platform team manages your company's Foundry resources. They must create Foundry resources and projects, deploy models and create shared connections, and let developers in, but company policy says they must not build or run agents themselves. Which role should you assign them on the Foundry resource?",
 ["Foundry Account Owner","Foundry Owner","Foundry Project Manager","Contributor"], 1,
 "it covers every set-up task, but it also lets them build and run agents, which policy forbids.",
 T("That the most complete role is the safe choice. Foundry Account Owner manages everything but has no data actions.",
   ROLE_MAP, [["\"create Foundry resources and projects, deploy models\"","Control plane."],["\"let developers in\"","Needs role assignment."],["\"must not build or run agents\"","Rules out Foundry Owner and Project Manager."]],
   "Set up without building → Foundry Account Owner. It can assign Foundry User to others.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "The landlord gets every key except the one to the workshop."),
single("d1-r3", "A team lead must create projects for her team, build and test agents in them, publish finished agents to Microsoft Teams, and give developers access to her projects. She must not create Foundry resources or manage model deployments. Which role should you assign, following least privilege?",
 ["Foundry Project Manager","Foundry Owner","Foundry User","Foundry Account Owner"], 1,
 "it does all of this, but it also creates resources and manages models, which she must not do.",
 T("That publishing agents comes with Foundry User. Publishing needs Foundry Project Manager at minimum.",
   ROLE_MAP, [["\"publish finished agents\"","Rules out Foundry User."],["\"give developers access\"","Project Manager can assign Foundry User."],["\"must not create Foundry resources or manage model deployments\"","Rules out Foundry Owner and Account Owner."]],
   "Build + publish + add Foundry Users → Foundry Project Manager.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "A team captain: picks the team and plays, but doesn't own the stadium."),
dict(id="d1-r4", type="yesno", skill=SK, stem="You are reviewing access for a Foundry resource used by several teams. For each of the following statements, select Yes if the statement is true. Otherwise, select No." + NOTE,
 statements=[dict(text="Foundry User on the Foundry resource lets a user see available quota when deploying a model.", answer=False, why="Quota needs Cognitive Services Usages Reader at subscription scope."),
  dict(text="You can use the Azure CLI to assign Foundry Agent Consumer at the scope of a single agent.", answer=True, why="The portal only offers account scope; the CLI can target project or agent scope."),
  dict(text="Requests authenticated with an API key are limited by the caller's Foundry role assignments.", answer=False, why="A key grants full access with no role checks."),
  dict(text="Creating a project in the Foundry portal can automatically assign Foundry User to the project's managed identity.", answer=True, why="If the creator can assign roles; SDK and CLI deployments don't do this.")],
 think=T("That RBAC covers every way in. Keys bypass it, and quota lives at subscription scope.", None, None,
   "Quota → Usages Reader at subscription. Agent scope → CLI. Keys → no RBAC. Portal → auto-assigns Foundry User.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="A master key opens every door, whatever the guest list says.", learn=L),
dict(id="d1-r5", type="multi", pick=2, skill=SK,
 stem="A prompt agent uses the Azure AI Search tool on an existing index. Developers have Foundry User on the project, but every search call made by the agent fails with an authorization error. Key-based access to the search service is disabled. Which two role assignments should you add? Each correct answer presents part of the solution.",
 options=["Search Index Data Contributor for the project's managed identity on the search service","Search Service Contributor for the project's managed identity on the search service","Search Index Data Reader for every developer who builds the agent, on the search service","Foundry User for the search service's system-assigned managed identity on the claims project","Owner for the project's managed identity on the resource group"],
 answer=[0, 1], runner=2, runnerWhy="it lets developers query the index themselves, but the agent's tool calls Search with the project's identity, not theirs.",
 think=T("That the developer's identity makes the tool's calls. The project's managed identity is the second hop.",
   [["Caller → Foundry","Hop 1","Foundry roles"],["Project → Search, Storage","Hop 2","Project managed identity + data roles"],["Wide fix","Over-privileged","Owner: never the least-privilege answer"]],
   [["\"every search call made by the agent fails\"","Hop 2 is missing."],["\"Key-based access ... is disabled\"","Needs Entra roles."]],
   "The Search tool needs Search Index Data Contributor and Search Service Contributor for the project's managed identity.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="The courier needs their own pass to the warehouse; your pass doesn't travel with them.", learn="https://learn.microsoft.com/en-us/azure/foundry/agents/how-to/tools/ai-search"),
dict(id="d1-r6", type="code", skill=SK, stem="A partner's application runs with a managed identity. It must call only the claims-triage agent in the claims project, and no other agent. You need to complete the command, following least privilege. How should you complete the command?",
 code='az role assignment create \\\n  --assignee-object-id $PARTNER_MI --assignee-principal-type ServicePrincipal \\\n  --role "[[0]]" \\\n  --scope "/subscriptions/$SUB/resourceGroups/rg/providers/Microsoft.CognitiveServices/accounts/contoso/projects/claims/[[1]]"',
 blanks=[dict(options=["Foundry Agent Consumer","Foundry User","Cognitive Services User"], answer=0, why="calls agent endpoints only; Foundry User can also build."),
         dict(options=["agents/claims-triage","deployments/gpt-5-mini","connections/claims-mcp"], answer=0, why="agent scope limits the assignment to one agent's endpoint.")],
 think=T("That project scope is the narrowest. Agents are a scope of their own, assignable with the CLI.", None, None,
   "One agent only → Foundry Agent Consumer at .../projects/<project>/agents/<agent>.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="A key cut for one room, not the whole floor.", learn=L),
single("d1-r7", "A data scientist must fine-tune a model in a Foundry project and then deploy the fine-tuned model for testing. You want to assign a single built-in role on the Foundry resource. Which role should you assign?",
 ["Foundry Owner","Foundry Project Manager","Foundry Account Owner","Contributor"], 1,
 "it can build and train in the project, but it can't create or manage model deployments.",
 T("That one plane is enough. Training is a data action; deploying is a control-plane action.",
   [["Train (data plane)","Data actions","Foundry User or above"],["Deploy (control plane)","Manage models","Account Owner or Owner"],["Both in one role","Only one","Foundry Owner"]],
   [["\"fine-tune ... and then deploy\"","Needs both planes."],["\"a single built-in role\"","Only Foundry Owner has both."]],
   "Fine-tune and deploy → Foundry Owner, or Foundry User + Foundry Account Owner as two roles.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "Baking the cake and putting it in the shop window are two different jobs."),
]
