"""Domain 1 practice bank: Plan and manage an Azure AI solution (25-30%)."""
from d12 import QUESTIONS as OLD

SK = {"q1": "Manage, monitor, secure", "q2": "Set up AI solutions", "q3": "Responsible AI", "q4": "Responsible AI",
      "q5": "Manage, monitor, secure", "q6": "Manage, monitor, secure", "q7": "Set up AI solutions", "q8": "Manage, monitor, secure"}
LEARN = {"q1": "https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry",
         "q2": "https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/deployment-types",
         "q3": "https://learn.microsoft.com/en-us/azure/foundry/guardrails/guardrails-overview",
         "q4": "https://learn.microsoft.com/en-us/azure/foundry/concepts/built-in-evaluators",
         "q5": "https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry",
         "q6": "https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/deployment-types",
         "q7": "https://learn.microsoft.com/en-us/azure/foundry/agents/environment-setup",
         "q8": "https://learn.microsoft.com/en-us/azure/foundry/concepts/observability"}

def T(premise, mp, apply, rule, guide):
    return dict(premise=premise, map=mp, apply=apply, rule=rule, guide=guide)

ITEMS = []
for q in OLD:
    if q["d"] != 1: continue
    ITEMS.append(dict(id="d1-" + q["id"], type="single", skill=SK[q["id"]], stem=q["stem"], options=q["options"],
                      answer=q["answer"], runner=q["runner"], runnerWhy=q["runnerWhy"], think=q["think"], eli5=q["eli5"], learn=LEARN[q["id"]]))

ITEMS += [
dict(id="d1-n1", type="single", skill="Choose Foundry services",
 stem="An agent classifies about 5,000 short claim emails per hour into six fixed categories. Tests show a small model is accurate enough, and cost per email matters. What do you deploy?",
 options=["A small model on a Global Standard deployment","Model router in Cost mode across several models","A reasoning model with high reasoning effort","The largest frontier model on a PTU deployment"],
 answer=0, runner=1, runnerWhy="it wins when prompts vary a lot in difficulty, so per-prompt routing saves more than one fixed small model.",
 think=T("That bigger or smarter models are the safe default. When a small model is proven accurate for a fixed task, anything larger only adds cost.",
  [["Fixed, simple task; small model proven","Cost","Small model, pay per token"],["Prompts vary from trivial to hard","Mixed difficulty","Model router"],["Multi-step reasoning fails","Capability","Reasoning model"]],
  [["\"six fixed categories\"","A narrow, repeatable task."],["\"a small model is accurate enough, and cost per email matters\"","Rules out larger or reasoning models."]],
  "Match the model to the task: small for narrow and proven, router for mixed difficulty, reasoning for multi-step problems.",
  "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools."),
 eli5="Don't hire a professor to sort the post into six trays.", learn="https://learn.microsoft.com/en-us/azure/foundry/openai/concepts/model-router"),
dict(id="d1-n2", type="single", skill="Choose Foundry services",
 stem="During a chat, customers upload their own repair estimates and ask questions about them. Nothing needs to persist after the conversation. Which knowledge option fits?",
 options=["File search over the uploaded documents","A Foundry IQ knowledge base over policy content","Agent memory storing each customer's estimates","An Azure AI Search index rebuilt every night"],
 answer=0, runner=1, runnerWhy="it wins for curated organisational content, such as policy wordings shared by every customer.",
 think=T("That every knowledge need is an index. Documents a user brings into one conversation belong to file search.",
  [["User uploads documents in the chat","Conversation-scoped","File search"],["Curated organisational content","Shared knowledge","Foundry IQ / AI Search"],["What the agent learns about a user over time","Personal, persistent","Memory (preview)"]],
  [["\"customers upload their own repair estimates\"","The user brings the documents."],["\"Nothing needs to persist\"","Rules out memory and a nightly index."]],
  "Memory = learned about the user; Foundry IQ = curated organisational content; file search = documents the user provides.",
  "Choose appropriate memory, tool, and knowledge integration services for agent solutions."),
 eli5="If someone hands you a letter, read the letter; don't file it in the library.", learn="https://learn.microsoft.com/en-us/azure/foundry/agents/concepts/what-is-foundry-iq"),
dict(id="d1-m1", type="multi", pick=2, skill="Manage, monitor, secure",
 stem="A support app must only call one published agent. A release pipeline must view quota usage for the subscription. Which two role assignments meet both needs with least privilege?",
 options=["Foundry Agent Consumer for the support app","Cognitive Services Usages Reader at subscription scope","Foundry User on the project for the support app","Cognitive Services Usages Reader on the resource","Foundry Account Owner for the release pipeline"],
 answer=[0, 1], runner=3, runnerWhy="right role, wrong scope: quota is viewed at subscription scope.",
 think=T("That the developer role is the minimum for any caller, and that any scope works for quota. Calling only needs Agent Consumer, and quota is a subscription-level view.",
  [["Only calls a published agent","Endpoint access","Foundry Agent Consumer"],["Builds agents and runs evaluations","Data actions","Foundry User"],["Views quota","Subscription-level read","Usages Reader at subscription scope"]],
  [["\"must only call one published agent\"","Agent Consumer, not Foundry User."],["\"view quota usage for the subscription\"","Usages Reader, assigned at subscription scope."]],
  "Call only → Agent Consumer. Build → Foundry User. Quota → Usages Reader at subscription scope.",
  "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="A visitor badge for the visitor, and the accounts office key for the person checking the budget.", learn="https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry"),
dict(id="d1-m2", type="multi", pick=2, skill="Choose Foundry services",
 stem="You plan to put a chat app behind model router. Which two constraints must the design account for?",
 options=["Its context window is the smallest underlying model's","It needs Global or Data Zone Standard deployments","Quality is the default routing mode","It routes requests on audio input as well as text","It can use Claude models without deploying them"],
 answer=[0, 1], runner=2, runnerWhy="Quality is a real mode, but Balanced is the default.",
 think=T("That a router inherits the best of every model. Its context window is the smallest one's, and it only runs on certain deployment types.",
  [["Long prompts get rejected","Smallest window wins","Use a model subset with large windows"],["Router won't deploy","Deployment type","Global or Data Zone Standard"],["Costs higher than expected","Routing mode","Cost mode or a model subset"]],
  [["\"constraints must the design account for\"","Look for limits, not features."],["\"chat app\"","Text input, so audio routing isn't the issue."]],
  "Model router: smallest context window, Global or Data Zone Standard only, Balanced by default, text-only routing, Claude deployed separately.",
  "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools."),
 eli5="A convoy moves at the speed of its slowest truck.", learn="https://learn.microsoft.com/en-us/azure/foundry/openai/concepts/model-router"),
dict(id="d1-m3", type="multi", pick=2, skill="Responsible AI",
 stem="An agent reads emails through a tool. It must block instructions hidden in those emails and block violent content in its replies. Which two guardrail controls do you add?",
 options=["Prompt Shields indirect attacks at tool response","Violence at output with annotate and block","Violence at output with annotate only","Prompt Shields user prompt attacks at user input","Groundedness at output with annotate and block"],
 answer=[0, 1], runner=2, runnerWhy="annotate-only isn't available for agents, and it wouldn't block anyway.",
 think=T("That every attack enters as the user's prompt. Hidden instructions in tool results are indirect attacks, checked at the tool response.",
  [["Instruction typed by the user","Direct attack","Prompt Shields at user input"],["Instruction inside fetched content","Indirect attack","Prompt Shields at tool response"],["Harmful reply","Output risk","Harm category at output, annotate and block"]],
  [["\"hidden in those emails\"","Arrives through a tool: indirect."],["\"block violent content in its replies\"","Output, and it must block."]],
  "Indirect attacks → Prompt Shields at tool response. Blocking needs 'annotate and block'; annotate-only isn't available for agents.",
  "Configure safety filters, guardrails, risk detection, and content moderation."),
 eli5="Check the parcels as well as the person at the door.", learn="https://learn.microsoft.com/en-us/azure/foundry/guardrails/guardrails-overview"),
dict(id="d1-y1", type="yesno", skill="Set up AI solutions",
 stem="For each statement about Foundry deployment types, select Yes if it's true.",
 statements=[dict(text="Global Batch costs about half as much as standard pricing and targets completion within 24 hours.", answer=True, why="Batch: 50% off, 24-hour target."),
  dict(text="Data Zone Standard keeps processing within the chosen data zone, such as the EU.", answer=True, why="That's the point of Data Zone deployments."),
  dict(text="Batch jobs draw on the same tokens-per-minute quota as standard deployments.", answer=False, why="Batch uses its own enqueued-token quota."),
  dict(text="New models usually reach Global deployments before Data Zone deployments.", answer=True, why="Global first, then Data Zone, then geography-based.")],
 think=T("That deployment types differ only in price. They also differ in where data is processed, how quota works and how soon new models arrive.",
  [["Need residency","Processing location","Data Zone"],["Need lowest cost, can wait","Bulk offline","Batch (own quota)"],["Need the newest model fast","Availability","Global"]],
  None, "Global = default and newest; Data Zone = residency; Provisioned = predictable latency; Batch = half price, 24 h, separate quota.",
  "Choose appropriate deployment options."),
 eli5="Same parcel, different couriers: one is fast, one stays in the country, one is cheap but slow.", learn="https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/deployment-types"),
dict(id="d1-y2", type="yesno", skill="Manage, monitor, secure",
 stem="For each statement about securing a Foundry project, select Yes if it's true.",
 statements=[dict(text="An API key on the Foundry resource can be limited to one project with role assignments.", answer=False, why="A key grants full access, with no role granularity."),
  dict(text="Agents and evaluations in a Foundry project require Microsoft Entra ID authentication.", answer=True, why="Keys don't work for agents, evaluations, datasets or workflows."),
  dict(text="Foundry Account Owner can run agents in every project without any other role.", answer=False, why="Account Owner manages accounts and models but has no data actions."),
  dict(text="A private endpoint with public access disabled makes inbound traffic to the resource private.", answer=True, why="Inbound privacy; outbound agent isolation needs Standard setup with your VNet.")],
 think=T("That an owner role can do everything, and that a key can be scoped. Owner roles split management from data actions, and keys can't be scoped.",
  [["Need per-identity control","Keys can't carry roles","Entra ID"],["Owner can't run agents","No data actions","Add Foundry User"],["Inbound must be private","Network","Private endpoint, public access off"]],
  None, "Keys: full access, no roles. Agents and evaluations: Entra only. Account Owner: management, no data actions.",
  "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="The building manager can't open the tenants' safes, and a master key can't be made to open only one door.", learn="https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry"),
dict(id="d1-o1", type="order", skill="Manage, monitor, secure",
 stem="Under load, a model deployment starts returning HTTP 429. Put the four actions in the order you take them.",
 pool=["Read the Retry-After value in the response","Retry with exponential backoff","Check TPM and RPM usage for that model and deployment type","Request more quota, or move steady load to Provisioned","Switch the app from Entra ID to an API key","Turn off the guardrail on the deployment"],
 answer=[0, 1, 2, 3],
 think=T("That a 429 is an error to fix in code or security. It's a rate limit: wait, retry, then fix capacity.",
  [["429 now","Rate limit hit","Honour Retry-After, back off"],["429 every peak","Quota too small","Check usage per model and type"],["Steady high load","Shared capacity","More quota or Provisioned"]],
  [["\"returning HTTP 429\"","Rate limit, not auth or safety: the two distractors don't apply."]],
  "429 → honour Retry-After → back off → check quota scope → raise quota or reserve capacity.",
  "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads."),
 eli5="When the shop says 'come back in five minutes', wait, try again, then ask for a bigger order slot."),
dict(id="d1-c1", type="code", skill="Set up AI solutions",
 stem="Complete the code so the app connects to a Foundry project without keys and caps the answer length on a reasoning model.",
 code='project = AIProjectClient(\n    endpoint="https://contoso.services.ai.azure.com/api/projects/claims",\n    credential=[[0]]())\nclient = project.[[1]]()\nr = client.responses.create(model="gpt-5-mini", input=note, [[2]]=300)',
 blanks=[dict(options=["DefaultAzureCredential","AzureKeyCredential","AzureSasCredential"], answer=0, why="keyless Entra ID authentication."),
         dict(options=["get_openai_client","agents.get_client","connections.get"], answer=0, why="returns an OpenAI client bound to the project."),
         dict(options=["max_output_tokens","max_tokens","max_completion_tokens"], answer=0, why="the Responses API's cap; max_tokens is rejected by reasoning models, and max_completion_tokens is the Chat Completions name.")],
 think=T("That every length parameter means the same everywhere. Each API names its own, and reasoning models reject max_tokens.",
  [["No keys allowed","Credential type","DefaultAzureCredential"],["Need an OpenAI client for the project","Client factory","get_openai_client"],["Cap length, Responses API","Parameter name","max_output_tokens"]],
  None, "Keyless: DefaultAzureCredential. Project client: get_openai_client(). Responses: max_output_tokens; Chat Completions: max_completion_tokens.",
  "Configure an application to connect to a Foundry project."),
 eli5="Right key, right door, right size of envelope.", learn="https://learn.microsoft.com/en-us/azure/foundry/quickstarts/get-started-code"),
dict(id="d1-c2", type="code", skill="Responsible AI",
 stem="Complete the code to run a cloud evaluation that checks whether an agent follows its instructions.",
 code='crit = [TestingCriterionAzureAIEvaluator(\n    type="azure_ai_evaluator", name="adherence",\n    evaluator_name="[[0]]",\n    initialization_parameters={"model": "gpt-5-mini"},\n    data_mapping={"query": "{{item.query}}", "response": "{{item.response}}"})]\nev = client.evals.[[1]](name="agent-eval", data_source_config=cfg, testing_criteria=crit)\nrun = client.evals.runs.[[2]](eval_id=ev.id, name="r1", data_source=ds)',
 blanks=[dict(options=["builtin.task_adherence","builtin.coherence","builtin.violence"], answer=0, why="task adherence measures whether the agent follows its instructions."),
         dict(options=["create","run","evaluate"], answer=0, why="evals.create defines the evaluation."),
         dict(options=["create","start","submit"], answer=0, why="evals.runs.create starts a run against a dataset.")],
 think=T("That coherence or safety evaluators measure instruction-following. Each evaluator answers one question; task adherence is the one about following instructions.",
  [["Follows its instructions?","Agent behaviour","Task adherence"],["Reads naturally?","Language quality","Coherence"],["Harmful content?","Safety","Violence and other safety evaluators"]],
  None, "Pick the evaluator by the question asked. Cloud evaluation: evals.create, then evals.runs.create.",
  "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling."),
 eli5="To check if someone followed the recipe, compare against the recipe, not against how nice the cake looks.", learn="https://learn.microsoft.com/en-us/azure/foundry/observability/how-to/cloud-evaluation-datasets"),
]

GOAL = ("Contoso Insurance runs a claims agent for its EU business. **Goal:** model processing must stay inside the EU, "
        "and response latency must stay predictable during the daily peak.")
def S(i, sol, ans, why_premise, mp, apply, rule):
    return dict(id="d1-s" + str(i), type="solution", skill="Set up AI solutions", scenario=GOAL,
                stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(why_premise, mp, apply, rule, "Choose appropriate deployment options."),
                eli5="Two boxes to tick: stays in Europe, and arrives on time every time.", learn="https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/deployment-types")
MAPS = [["Must stay in the EU","Processing location","Data Zone (EU)"],["Latency must be predictable at peak","Shared vs reserved capacity","Provisioned"],["Both","Both","Data Zone Provisioned"]]
ITEMS += [
 S(1, "Deploy the model as Data Zone Provisioned in the EU data zone.", True,
   "That residency and latency need two separate fixes. One deployment type covers both.", MAPS,
   [["\"stay inside the EU\"","Data Zone in the EU: met."],["\"latency must stay predictable\"","Provisioned capacity: met."]],
   "Residency + predictable latency = Data Zone Provisioned."),
 S(2, "Deploy the model as Global Standard in an EU region, and add a private endpoint.", False,
   "That a private endpoint or an EU region keeps processing in the EU. A Global deployment can process anywhere; a private endpoint only changes the network path.", MAPS,
   [["\"Global Standard\"","Processing may leave the EU: not met."],["\"private endpoint\"","Network privacy, not processing location."]],
   "Region of the resource ≠ where a Global deployment processes."),
 S(3, "Deploy the model as Data Zone Standard in the EU data zone, and request a higher TPM quota.", False,
   "That more quota means predictable latency. Standard capacity is shared, so latency varies at peak even with a larger quota.", MAPS,
   [["\"Data Zone Standard ... EU\"","Residency: met."],["\"higher TPM quota\"","Raises the ceiling, not predictability: not met."]],
   "Quota raises how much you can send; Provisioned makes latency predictable."),
]
BANK = dict(id="d1", title="Domain 1 · Plan and manage an Azure AI solution", minutes=40, items=ITEMS)
