SRC_RBAC = "https://learn.microsoft.com/en-us/azure/foundry/concepts/rbac-foundry"
LESSONS = [
dict(id="1a", d=1, title="Choose the right model and Foundry service", skill="Plan & manage · choose Foundry services",
 plain="Start from the job, not the model. A small model for classification, a large or reasoning model for multi-step work, a multimodal model when images or audio are involved, and a Foundry Tool when a purpose-built service already does it. For knowledge, pick by where the content comes from.",
 facts=[
  "**Foundry Models** catalog has 10,000+ models. *Models sold by Azure* are billed by Microsoft; partner and community models are billed separately.",
  "**Model router** picks a model per prompt. Modes: **Balanced** (default), Quality, Cost. Optional *model subset* limits the candidates.",
  "Model router works only on **Global Standard** and **Data Zone Standard** deployments; its context window is the **smallest** underlying model's; it routes on **text only**.",
  "Knowledge, by source: **memory** = what the agent learns about a user (preview) · **Foundry IQ** = curated organisational content (agentic retrieval over Azure AI Search) · **file search** = documents the user uploads in the conversation.",
  "Foundry IQ status: API GA, portal still preview. Memory: preview, 100 scopes per store, 10,000 memories per scope, no VNet support.",
 ],
 traps=["Model router's context window is the smallest underlying model's, not the largest.",
        "File search is for documents a user brings; organisational knowledge belongs in Foundry IQ or Azure AI Search.",
        "Claude models must be deployed separately before the router can use them."],
 harness="Our gateway already routes per job by golden-set score. Model router is the Foundry-managed alternative; it fits when per-prompt routing beats per-job routing.",
 lab="Deploy model router in a Foundry project, send five prompts of different difficulty, and read which model served each in the response.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/openai/concepts/model-router","https://learn.microsoft.com/en-us/azure/foundry/agents/concepts/what-is-foundry-iq"]),
dict(id="1b", d=1, title="Set up Foundry: resources, projects and deployment types", skill="Plan & manage · set up AI solutions",
 plain="One **Foundry resource** is the security, networking and billing boundary, and holds the model deployments. **Projects** inside it are where teams build; agents in one project share files, conversations and indexes. How you deploy a model decides where data is processed and how you pay.",
 facts=[
  "Project endpoint: `https://<resource>.services.ai.azure.com/api/projects/<project>`.",
  "Hub-based projects and standalone Azure OpenAI resources are *classic*; new work uses Foundry projects (an Azure OpenAI resource can be upgraded and keep its endpoint).",
  "Deployment types: **Global Standard** (default, newest models first) · **Data Zone** (US, EU or APAC residency) · **Standard** (one geography) · **Provisioned / PTU** (predictable latency) · **Global/Data Zone Batch** (50% off, 24-hour target, separate quota).",
  "Agent environment: **Basic** (platform storage) · **Standard** (your own Storage, AI Search, Cosmos DB; customer-managed keys) · **Standard + your VNet** (private outbound).",
  "Private MCP servers and the Azure Functions tool require the **Standard** setup.",
  "CI/CD: define agents with the SDK or REST in the pipeline (versions are snapshotted), use `azd ai` commands, and gate releases on evaluations over versioned datasets.",
 ],
 traps=["Batch is for offline bulk work, never for a live conversation.",
        "Data Zone is the answer for 'data must stay in the EU'; Global Standard may process anywhere.",
        "Limits worth knowing: 250 projects per resource, 32 deployments per resource."],
 harness="We use Global or Data Zone Standard behind the APIM gateway, PTU only when latency must be predictable, and Batch for document extraction and golden-set runs.",
 lab="Create a Foundry resource and two projects; deploy one model as Global Standard and one as Data Zone Standard; compare where each can process data.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/foundry-models/concepts/deployment-types","https://learn.microsoft.com/en-us/azure/foundry/agents/environment-setup"]),
dict(id="1c", d=1, title="Manage, monitor and secure AI systems", skill="Plan & manage · manage, monitor, secure",
 plain="Quotas protect everyone's capacity; roles decide who may build or only call; keyless identity removes secrets; private networking keeps traffic off the internet. Monitoring watches quality and safety as well as uptime.",
 facts=[
  "Quota (TPM/RPM) is per **subscription, region, model and deployment type**. A **429** means the limit was hit: back off and honour `Retry-After`.",
  "Reasoning tokens are billed as output tokens. Playground evaluations are on by default and billed.",
  "**Keyless**: Entra ID with `DefaultAzureCredential`, scope `https://ai.azure.com/.default`. An API key grants full access with no role granularity.",
  "Agents, evaluations, datasets, workflows and Content Understanding **require Entra ID**; keys don't work there.",
  "Roles: **Foundry Agent Consumer** (call agents only) · **Foundry User** (build in a project; least privilege for developers) · **Foundry Project Manager** · **Foundry Account Owner** (no data actions) · **Foundry Owner**.",
  "Inbound privacy: private endpoint with public access disabled. Outbound agent isolation: Standard setup with your own VNet.",
 ],
 code="from azure.identity import DefaultAzureCredential\nfrom azure.ai.projects import AIProjectClient\n\nproject = AIProjectClient(\n    endpoint=\"https://<res>.services.ai.azure.com/api/projects/<proj>\",\n    credential=DefaultAzureCredential())   # keyless: no API key anywhere",
 traps=["*Azure AI User* is now **Foundry User** (same role ID).",
        "*Azure AI Developer* is scoped to Azure ML hubs; it's the wrong answer for Foundry projects.",
        "Viewing quota needs **Cognitive Services Usages Reader** at subscription scope.",
        "For a standalone Azure OpenAI resource the role is *Cognitive Services OpenAI User*; for a Foundry project, *Foundry User*."],
 harness="Each agent runs with its own managed identity; the APIM gateway holds the limits; App Insights holds the traces (Part 3).",
 lab="Assign yourself Foundry User on a project, remove key access, and call a model with DefaultAzureCredential only.",
 src=[SRC_RBAC,"https://learn.microsoft.com/en-us/azure/foundry/foundry-models/quotas-limits"]),
dict(id="1d", d=1, title="Responsible AI: guardrails, evaluators and red teaming", skill="Plan & manage · responsible AI",
 plain="A **guardrail** is a named set of controls: which risk, where it's checked (input, output, tool call, tool response) and what happens (annotate, or annotate and block). **Evaluators** score quality and safety; the **AI Red Teaming Agent** attacks the app and reports how often attacks succeed.",
 facts=[
  "Risks: hate, sexual, self-harm, violence (severity threshold) · **Prompt Shields** (direct and indirect attacks) · protected material · groundedness (preview, models only) · PII (preview) · task adherence (preview).",
  "Guardrails for models are GA; **for agents, preview**. Tool-call and tool-response checkpoints apply to agents only.",
  "Default guardrail: `Microsoft.DefaultV2`. An agent **without** its own guardrail inherits its model deployment's; one **with** its own fully overrides it.",
  "Evaluators: quality (coherence, fluency), RAG (retrieval, groundedness 1–5, relevance), safety (violence, protected material, indirect attack…), agent (task adherence, intent resolution, tool call accuracy…).",
  "**Groundedness Pro** is pass/fail via Content Safety and needs no model deployment.",
  "**AI Red Teaming Agent**: built on PyRIT, metric is **Attack Success Rate (ASR)**, strategies such as Base64 and Flip.",
 ],
 traps=["Three different 'groundedness' things: the guardrail (blocks), the evaluator (scores 1–5) and Groundedness Pro (pass/fail).",
        "Annotate-only is not available for agents.",
        "An agent's own guardrail replaces the model's entirely; it doesn't merge."],
 harness="Content Safety detectors sit inside our positioned rules; evaluators and the red-team agent join AgentTwin in offline evaluation (Part 9).",
 lab="Create a guardrail with Prompt Shields for indirect attacks on tool responses, attach it to an agent, and send a document with a hidden instruction.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/guardrails/guardrails-overview","https://learn.microsoft.com/en-us/azure/foundry/concepts/built-in-evaluators"]),
dict(id="2a", d=2, title="Consume models: the Responses API and v1 endpoints", skill="GenAI & agents · build generative apps",
 plain="Foundry gives one project endpoint and an OpenAI-compatible client. The **Responses API** is the current way to call models and agents; the **v1 routes** (`/openai/v1/`) replace monthly API versions.",
 facts=[
  "Packages: `azure-ai-projects` 2.x (incompatible with 1.x), `azure-identity`, `openai`.",
  "`project.get_openai_client()` returns an OpenAI client bound to the project; `responses.create(model=..., input=...)`.",
  "v1 API: use `OpenAI(base_url=\".../openai/v1/\")`, not `AzureOpenAI()`; no `api-version` needed.",
  "**Reasoning models** don't take `temperature`, `top_p` or `max_tokens`: use `max_output_tokens` (Responses) or `max_completion_tokens` and `reasoning_effort`.",
  "A developer message equals a system message; don't send both.",
 ],
 code="openai = project.get_openai_client()\nr = openai.responses.create(\n    model=\"gpt-5-mini\",\n    input=\"Summarise this claim note in two lines: ...\",\n    max_output_tokens=300)\nprint(r.output_text)",
 traps=["`max_tokens` on a reasoning model is an error, not a cap.",
        "`AzureOpenAI()` with an `api-version` is the older pattern; v1 uses plain `OpenAI()`."],
 harness="Our PydanticAIClient calls the same endpoints through Pydantic AI's model layer, behind our LLMClient port (Part 4).",
 lab="Call one model with Responses, then the same prompt with reasoning_effort low and high; compare output tokens and latency.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/quickstarts/get-started-code","https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/reasoning"]),
dict(id="2b", d=2, title="RAG and generative workflows", skill="GenAI & agents · RAG, workflows",
 plain="Retrieval-augmented generation finds the right passages first, then asks the model to answer from them. In Foundry that's the Azure AI Search tool, Foundry IQ knowledge bases, or file search, depending on where the content lives.",
 facts=[
  "Azure AI Search tool: `query_type` defaults to **`vector_semantic_hybrid`**; `top_k` defaults to 5.",
  "The project's managed identity needs **Search Index Data Contributor** and **Search Service Contributor** for the Search tool.",
  "Foundry IQ adds **agentic retrieval**: multi-source, permission-aware, with retrieval reasoning effort minimal, low or medium.",
  "**Prompt flow retires 20 Apr 2027**; Foundry **Workflows** (preview) retire 1 Dec 2026. New orchestration goes to **Microsoft Agent Framework**.",
 ],
 traps=["Choosing prompt flow or Workflows for a new build is the retiring answer; Agent Framework is the current one.",
        "Hybrid + semantic is the default and usually the best grounding choice; pure vector misses exact codes and IDs."],
 harness="Our knowledge port uses pgvector today; Azure AI Search or Foundry IQ is the option when the corpus grows (Part 3).",
 lab="Index ten policy-wording PDFs in Azure AI Search, attach the Search tool to an agent, and ask a question whose answer is a clause number.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/agents/how-to/tools/ai-search","https://techcommunity.microsoft.com/blog/azure-ai-foundry-blog/prompt-flow-is-being-retired/4513587"]),
dict(id="2c", d=2, title="Build agents with Foundry Agent Service", skill="GenAI & agents · build agents",
 plain="A **prompt agent** is declared (model, instructions, tools) and Foundry runs it. A **hosted agent** is your own code in a container. Agents v2 talk in **conversations**, **responses** and **agent versions**, not threads and runs.",
 facts=[
  "Create: `project.agents.create_version(agent_name=..., definition=PromptAgentDefinition(...))`.",
  "Chat: `oa = project.get_openai_client(agent_name=...)`, `oa.conversations.create()`, then `oa.responses.create(conversation=...)`.",
  "Tools: function calling (runs in your app) · code interpreter · file search · Azure AI Search · OpenAPI · MCP · Azure Functions · Bing grounding · web search · A2A · computer use (preview) · memory (preview).",
  "**Toolbox** (GA): curate tools once and expose them to many agents through one MCP endpoint.",
  "Bing grounding and web search send queries **outside the Azure compliance boundary**.",
 ],
 code="from azure.ai.projects.models import PromptAgentDefinition\nagent = project.agents.create_version(\n    agent_name=\"fnol-intake\",\n    definition=PromptAgentDefinition(model=\"gpt-5-mini\",\n        instructions=\"Register motor claims. Never promise a payout.\"))\noa = project.get_openai_client(agent_name=\"fnol-intake\")\nconv = oa.conversations.create()\nr = oa.responses.create(conversation=conv.id, input=\"I had an accident today\")",
 traps=["Threads, runs and assistants are the classic API vocabulary.",
        "Bing grounding is wrong when data must stay inside a boundary.",
        "Function calling executes in your application, not in Foundry."],
 harness="Our customer-facing agents run their own loop (Part 4); prompt agents suit simple internal agents, and hosted agents can run our container.",
 lab="Create a prompt agent with a function tool, run a conversation, and handle the function call in your own code.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/agents/overview","https://learn.microsoft.com/en-us/azure/foundry/agents/concepts/toolbox-overview"]),
dict(id="2d", d=2, title="Multi-agent and human approval", skill="GenAI & agents · orchestration and safeguards",
 plain="When one agent hands work to another, use the **A2A tool** or **Agent Framework** workflows. When an action needs a person, stop and ask: MCP tools ask for approval by default, and function calls run in your code where you can add a gate.",
 facts=[
  "**Connected Agents is not available** in the new Agent Service; use the **A2A tool** (protocol v1.0, GA) or Workflows.",
  "MCP `require_approval`: `always` (default), `never`, or per-tool lists. The model returns an `mcp_approval_request`; you answer with an `mcp_approval_response`.",
  "Non-streaming MCP calls time out at **100 seconds**; use background mode for longer work.",
  "Microsoft Agent Framework 1.0 (Python, .NET) succeeds Semantic Kernel and AutoGen: agents, graph workflows, middleware, MCP.",
  "`tool_choice`: `auto`, `required` or `none`.",
 ],
 code="tool = MCPTool(server_label=\"claims\", server_url=\"https://mcp.example/claims\",\n               require_approval=\"always\", project_connection_id=\"claims-conn\")",
 traps=["Connected Agents is the classic answer; A2A is the current one.",
        "Setting `require_approval=\"never\"` on a write tool removes the human from the loop."],
 harness="Payout approvals in our design run on DBOS with Teams cards, under a separate identity (Parts 3 and 8).",
 lab="Attach an MCP server with approval always; approve one call and reject another; trace both in App Insights.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/agents/how-to/tools/model-context-protocol","https://learn.microsoft.com/en-us/azure/foundry/agents/how-to/tools/agent-to-agent"]),
dict(id="2e", d=2, title="Optimise and operationalise: prompts, reflection, tracing", skill="GenAI & agents · optimise and operationalise",
 plain="Tune with prompts and parameters, then measure. Add a critic step (an evaluator as judge) before turning up reasoning effort. Turn on tracing so every call, tool and token is visible.",
 facts=[
  "`reasoning_effort` ranges from `none` to `max` depending on the model; reasoning tokens count as output.",
  "Connect **Application Insights** to the project: server-side tracing then works with no code change, using OpenTelemetry GenAI conventions; traces viewable for 90 days.",
  "Client-side tracing: `azure-core-tracing-opentelemetry` with the OpenTelemetry SDK.",
  "Querying traces needs **Log Analytics Reader**.",
  "Orchestrate several models with model router, or rules first and a model only where needed.",
 ],
 traps=["Turning up reasoning effort is not the first fix for wrong answers; evaluate first.",
        "Tracing for prompt and hosted agents is GA; for workflow and external agents, preview."],
 harness="Spans go to App Insights and counters to Managed Prometheus; online rules read the traces (Part 9).",
 lab="Connect App Insights, run an agent conversation with two tool calls, and find the latency breakdown per span.",
 src=["https://learn.microsoft.com/en-us/azure/foundry/observability/how-to/trace-agent-setup","https://learn.microsoft.com/en-us/azure/foundry/openai/how-to/reasoning"]),
]

def Q(id,d,lesson,stem,options,answer,runner,runnerWhy,premise,mp,apply,rule,guide,eli5):
    return dict(id=id,d=d,lesson=lesson,stem=stem,options=options,answer=answer,runner=runner,runnerWhy=runnerWhy,
                think=dict(premise=premise,map=mp,apply=apply,rule=rule,guide=guide),eli5=eli5)

QUESTIONS = [
Q("q1",1,"1c","A developer builds and tests agents in one Foundry project. Security asks for the least privilege that still lets them create agents and run evaluations. Which role do you assign?",
 ["Foundry User on the project","Foundry Project Manager on the project","Azure AI Developer on the project","Foundry Agent Consumer on the project"],0,1,
 "it wins only if the developer must also manage the project or assign roles.",
 "That every 'developer' role in the list builds agents. Two of them don't: one only calls agents, one belongs to Azure ML hubs.",
 [["Must build agents and run evaluations","Needs data actions in the project","Foundry User"],["Must also manage the project and assign roles","Management on top of building","Foundry Project Manager"],["Only calls a published agent","Endpoint access only","Foundry Agent Consumer"]],
 [["\"create agents and run evaluations\"","Needs build permissions, which rules out Agent Consumer."],["\"least privilege\"","Rules out Project Manager, which adds management rights the stem doesn't need."]],
 "Build = Foundry User; manage = Project Manager; only call = Agent Consumer. Azure AI Developer belongs to hubs.",
 "Configure security, including managed identity, private networking, keyless credentials, and role policies.",
 "Give the builder the builder's key, not the manager's master key and not the visitor's badge."),
Q("q2",1,"1b","Claims data for an EU subsidiary must be processed only inside the EU. Traffic is steady during office hours and cost per token matters. Which deployment type fits?",
 ["Data Zone Standard in an EU region","Global Standard in an EU region","Data Zone Provisioned in an EU region","Data Zone Batch in an EU region"],0,2,
 "it wins if the stem asked for predictable latency at sustained high volume.",
 "That picking an EU region is enough. A Global deployment can process anywhere, whatever region the resource sits in.",
 [["Data must stay in a zone, pay per token","Residency + standard billing","Data Zone Standard"],["Need predictable latency at high, steady volume","Capacity must be reserved","Data Zone Provisioned"],["Bulk offline jobs, 24-hour turnaround","Cost over speed","Data Zone Batch"]],
 [["\"processed only inside the EU\"","Rules out Global Standard."],["\"cost per token matters\"","Points to pay-per-token, not reserved PTU."]],
 "Residency → Data Zone; predictable latency → Provisioned; bulk offline → Batch.",
 "Choose appropriate deployment options.",
 "Telling the post office 'deliver inside Europe only' needs a Europe-only service, not just a Europe address."),
Q("q3",1,"1d","An agent has no guardrail of its own. Its model deployment uses a custom guardrail that blocks prompt attacks. What applies to the agent's traffic?",
 ["The model deployment's custom guardrail","The Microsoft.DefaultV2 default guardrail","No guardrail until one is assigned","Both guardrails, merged by severity"],0,1,
 "it wins only if the model deployment itself had no custom guardrail.",
 "That an agent always starts from the default guardrail. It inherits from its model deployment.",
 [["Agent has no guardrail","Inherits the model deployment's","Nothing to do"],["Agent has its own guardrail","It fully overrides the model's","Put every control you need in it"],["Model has no custom guardrail","Default applies","DefaultV2"]],
 [["\"has no guardrail of its own\"","So inheritance decides."],["\"model deployment uses a custom guardrail\"","That's what it inherits, so DefaultV2 doesn't apply."]],
 "No agent guardrail → inherit the deployment's. Agent guardrail → replaces it entirely.",
 "Configure safety filters, guardrails, risk detection, and content moderation.",
 "A new worker follows the house rules of the building they're in, until they get their own rulebook."),
Q("q4",1,"1d","You must prove your RAG app's answers come from the retrieved passages, as a pass or fail per answer, without deploying a judge model. Which evaluator do you use?",
 ["Groundedness Pro evaluator","Groundedness evaluator, scored 1 to 5","Relevance evaluator","Groundedness guardrail"],0,1,
 "it wins when a 1–5 score is wanted and a judge model is available.",
 "That 'groundedness' is one thing. There are three: a guardrail that blocks, an evaluator that scores 1–5, and Groundedness Pro, which gives pass/fail.",
 [["Score answers 1–5 with a judge model","Quality trend","Groundedness evaluator"],["Pass/fail per answer, no model deployment","Uses Content Safety","Groundedness Pro"],["Block ungrounded output live","Runtime control","Groundedness guardrail (preview)"]],
 [["\"as a pass or fail\"","Rules out the 1–5 evaluator."],["\"without deploying a judge model\"","Points to Groundedness Pro, which runs on Content Safety."]],
 "Pass/fail without a judge = Groundedness Pro. Score = Groundedness. Block live = the guardrail.",
 "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling.",
 "A yes/no stamp from the inspector is different from a 1-to-5 grade from a teacher."),
Q("q5",1,"1c","An app calls a Foundry project with an API key. Auditors require every call to be tied to an identity with a scoped role. What do you change?",
 ["Use Entra ID with DefaultAzureCredential","Rotate the API key every 30 days","Store the API key in Key Vault","Restrict the key with a private endpoint"],0,2,
 "it's good practice if keys must stay, but a key still carries no identity or role.",
 "That protecting a key makes it auditable. A key grants full access with no identity behind it.",
 [["Need per-identity, role-scoped access","Keys can't carry roles","Entra ID, keyless"],["Must keep keys for a legacy client","Secret handling","Key Vault + rotation"],["Need traffic off the internet","Network, not identity","Private endpoint"]],
 [["\"tied to an identity with a scoped role\"","Only Entra ID tokens carry identity and roles."],["\"calls ... with an API key\"","Rotation, Key Vault and networking all keep the key, so they can't satisfy this."]],
 "Identity and roles → Entra ID. Keys give full access with no granularity.",
 "Configure security, including managed identity, private networking, keyless credentials, and role policies.",
 "A shared door code tells you someone came in, not who. A badge tells you who."),
Q("q6",1,"1b","Every night you summarise 40,000 archived claim notes. Results are needed by the next morning, and cost must be as low as possible. Which deployment type do you choose?",
 ["Global Batch","Global Standard","Global Provisioned","Data Zone Standard"],0,1,
 "it wins if results were needed within minutes rather than by morning.",
 "That every model call should be real-time. Offline bulk work can wait and is half price on Batch.",
 [["Bulk offline, results within 24 h","Cost matters most","Batch (50% off)"],["Interactive users waiting","Latency matters","Standard or Provisioned"],["Residency required for bulk","Zone + cost","Data Zone Batch"]],
 [["\"needed by the next morning\"","Fits Batch's 24-hour target."],["\"cost must be as low as possible\"","Batch is about half price."]],
 "Waiting users → Standard or PTU. Overnight bulk → Batch.",
 "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads.",
 "Overnight post is cheaper than a courier when nobody needs it before morning."),
Q("q7",1,"1b","Your agents need a private MCP server reachable only inside your network, and files stored with customer-managed keys. Which agent environment setup is required?",
 ["Standard setup with your own VNet","Basic setup with a private endpoint","Standard setup without a VNet","Basic setup with platform storage"],0,2,
 "it wins if storage with customer-managed keys were the only requirement and no private network reach was needed.",
 "That a private endpoint on the resource makes the agent's outbound calls private. Inbound and outbound are different.",
 [["Own storage, customer-managed keys","Data ownership","Standard"],["Agent must reach private resources","Outbound isolation","Standard + your VNet"],["Quick start, platform storage","Simplicity","Basic"]],
 [["\"private MCP server reachable only inside your network\"","Needs outbound isolation, so a VNet."],["\"customer-managed keys\"","Needs Standard, which rules out Basic."]],
 "Own storage → Standard. Reach private resources → Standard + your VNet.",
 "Design Azure infrastructure for AI apps and agent-based solutions.",
 "Your own locked filing cabinet is one thing; a private corridor to the next building is another."),
Q("q8",1,"1c","A team wants to watch an agent in production for quality drift and safety events, sampled from live traffic, with alerts. What do you configure?",
 ["Continuous evaluation in the monitoring dashboard","A nightly batch evaluation run over the golden set","Server-side tracing with no evaluators","A red-team run before every release"],0,1,
 "it wins when the goal is catching regressions before release rather than drift in live traffic.",
 "That offline tests also watch production. Drift shows up in live traffic, between releases.",
 [["Drift and safety in live traffic","Production signals","Continuous evaluation + alerts"],["Regression before release","Offline gate","Batch evaluation on a golden set"],["Attack resistance","Security","AI Red Teaming Agent"]],
 [["\"in production ... sampled from live traffic\"","Rules out offline golden-set runs."],["\"with alerts\"","Continuous evaluation feeds Azure Monitor alerts; tracing alone only records."]],
 "Before release → batch evaluation and red team. In production → continuous evaluation with alerts.",
 "Monitor model performance, drift, safety events, and grounding quality.",
 "A driving test happens once; a dashboard warning light watches every trip."),
Q("q9",2,"2c","You're migrating an agent from the classic Assistants-style API to the current Foundry Agent Service. What replaces threads and runs?",
 ["Conversations and responses","Sessions and invocations","Threads and agent versions","Workflows and steps"],0,2,
 "agent versions are real in the new API, but they replace assistants, not threads.",
 "That the new API only renamed the agent. It renamed the conversation objects too.",
 [["Threads","Conversation history","Conversations"],["Runs","One model turn","Responses"],["Assistants","Agent definition","Agent versions"]],
 [["\"threads and runs\"","Two objects: history and execution."],["\"current Foundry Agent Service\"","Agents v2 vocabulary: conversations and responses."]],
 "Threads → conversations; runs → responses; assistants → agent versions.",
 "Define agent roles, goals, conversation-tracking approach, and tool schemas.",
 "Same chat, new labels on the folders."),
Q("q10",2,"2d","Two agents must cooperate: an intake agent hands suspicious claims to a fraud agent. You're building on the current Agent Service. What do you use?",
 ["The A2A tool on the intake agent","Connected Agents on the intake agent","A Foundry Workflow in preview","A shared file search vector store"],0,2,
 "it works today but is preview and retires on 1 December 2026, so it's the weaker choice for a new build.",
 "That Connected Agents is still the multi-agent answer. It isn't available in the new Agent Service.",
 [["One agent calls another agent","Agent-to-agent","A2A tool"],["Fixed multi-step process","Orchestration","Agent Framework workflows"],["Shared documents, not delegation","Knowledge","File search / Foundry IQ"]],
 [["\"hands suspicious claims to a fraud agent\"","Delegation between agents."],["\"current Agent Service\"","Rules out Connected Agents."]],
 "Agent calls agent → A2A. Classic Connected Agents is gone; Workflows are retiring.",
 "Implement orchestrated multi-agent solutions.",
 "Instead of shouting across the office, use the proper internal phone line."),
Q("q11",2,"2d","An agent uses an MCP tool that can change policy records. Compliance requires a person to confirm each change before it runs. How do you configure the tool?",
 ["Set require_approval to always","Set require_approval to never","Set tool_choice to required","Add a Task Adherence guardrail"],0,3,
 "it detects drift from the task but doesn't stop a write for human confirmation.",
 "That a guardrail can stand in for a person's approval. Guardrails detect risk; approval needs a human decision.",
 [["Each write needs human confirmation","Human in the loop","require_approval=always"],["Detect the agent straying from its task","Runtime monitoring","Task Adherence (preview)"],["Force the model to use a tool","Tool selection","tool_choice=required"]],
 [["\"a person to confirm each change\"","Only an approval request does that."],["\"MCP tool\"","MCP approval is configured on the tool itself."]],
 "Human confirmation on MCP → require_approval always (the default). Never relax it for writes.",
 "Build autonomous or semiautonomous workflows with safeguards and approval flow controls.",
 "The assistant fills in the form; the manager signs it."),
Q("q12",2,"2a","A reasoning model returns an error when you set max_tokens and temperature. You still need to cap the answer length. What do you send?",
 ["max_output_tokens on the Responses API","max_tokens with the temperature setting removed","top_p with a lower value","A system and a developer message"],0,1,
 "removing temperature fixes half the error, but reasoning models still reject max_tokens.",
 "That reasoning models accept the classic sampling parameters. They don't.",
 [["Cap length on a reasoning model","Unsupported max_tokens","max_output_tokens / max_completion_tokens"],["Want less or more thinking","Effort, not sampling","reasoning_effort"],["Classic model needs creativity control","Sampling","temperature / top_p"]],
 [["\"reasoning model\"","Rules out temperature, top_p and max_tokens."],["\"cap the answer length\"","max_output_tokens does that, and includes reasoning tokens."]],
 "Reasoning models: max_output_tokens or max_completion_tokens, plus reasoning_effort. No temperature, no max_tokens.",
 "Tune generation behavior, such as prompt engineering and adjusting model parameters.",
 "A thinking machine has its own dials; the old knobs don't fit it."),
Q("q13",2,"2b","You're starting a new multi-step generative pipeline in Foundry that must be supported for years. Which orchestration option do you build on?",
 ["Microsoft Agent Framework","Prompt flow in Foundry","Foundry Workflows in preview","Semantic Kernel planners"],0,2,
 "it's available now but preview and retires on 1 December 2026.",
 "That anything in the Foundry portal is the long-term choice. Prompt flow and Workflows are both retiring.",
 [["New build, long life","Supported framework","Agent Framework"],["Existing prompt flow","Retires 20 Apr 2027","Migrate to Agent Framework"],["Semantic Kernel or AutoGen code","Predecessors","Move to Agent Framework"]],
 [["\"must be supported for years\"","Rules out retiring options."],["\"new\"","No legacy to keep; choose the successor."]],
 "New orchestration → Agent Framework. Prompt flow and Workflows are retiring.",
 "Design workflows, tool-augmented flows, and multistep reasoning pipelines.",
 "Don't build a new house on land scheduled to be cleared."),
Q("q14",2,"2c","Data for a regulated insurer must stay inside the Azure compliance boundary. An agent needs current public information about weather events. Which approach is wrong?",
 ["Add the Grounding with Bing Search tool","Call an approved weather API via OpenAPI","Index a licensed weather feed in AI Search","Query a weather MCP server you host"],0,1,
 "it's a valid alternative here, since you control the API, but it means maintaining an integration.",
 "That every built-in tool stays inside Azure's compliance boundary. Bing grounding sends queries outside it.",
 [["Public web data, boundary not required","Fresh web results","Bing grounding / web search"],["Boundary required, known source","Controlled integration","OpenAPI or MCP tool you approve"],["Boundary required, stable content","Indexed copy","Azure AI Search"]],
 [["\"must stay inside the Azure compliance boundary\"","Rules out Bing grounding and web search."],["\"Which approach is wrong?\"","Look for the one that breaks the boundary."]],
 "Bing grounding and web search leave the compliance boundary; the data protection terms don't cover them.",
 "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions.",
 "Asking a stranger on the street is quick, but the conversation isn't private."),
Q("q15",2,"2e","After deployment you need per-call latency, token use and tool calls for every agent conversation, without changing code. What do you do?",
 ["Connect Application Insights to the project","Add OpenTelemetry spans in the client code","Enable continuous evaluation sampling","Turn on diagnostic logs for the key"],0,1,
 "it works and adds client-side detail, but the stem rules out code changes.",
 "That tracing always needs instrumentation code. Foundry traces server-side once App Insights is connected.",
 [["Traces with no code change","Server-side tracing","Connect App Insights"],["Your own spans around calls","Client-side tracing","OpenTelemetry SDK"],["Quality scores on live traffic","Evaluation, not tracing","Continuous evaluation"]],
 [["\"without changing code\"","Rules out client-side spans."],["\"latency, token use and tool calls\"","That's tracing, not evaluation."]],
 "No-code tracing → connect App Insights. Extra detail → client-side OpenTelemetry.",
 "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns.",
 "Plug the meter into the socket instead of rewiring the house."),
Q("q16",2,"2c","Many agents across teams need the same five approved tools with one place for authentication and versioning. What do you use?",
 ["A Foundry toolbox exposed as one MCP endpoint","Function tools duplicated in each agent","A shared OpenAPI spec copied into each agent's tools","One hosted agent that calls the others"],0,2,
 "it shares the definition but each agent still holds its own copy, auth and version.",
 "That sharing a definition shares the tool. Each copy still needs its own auth and upgrade.",
 [["Many agents, same tools, central control","Curated catalogue","Toolbox (one MCP endpoint)"],["One agent, app-side logic","Local execution","Function calling"],["One API, one agent","Direct integration","OpenAPI tool"]],
 [["\"one place for authentication and versioning\"","A toolbox centralises both."],["\"Many agents across teams\"","Copies multiply the work."]],
 "Same tools for many agents → a toolbox behind one MCP endpoint.",
 "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions.",
 "One shared toolshed with a sign-out sheet beats a copy of every tool in every garage."),
Q("q17",2,"2e","An agent's answers are sometimes off-task. The team wants to improve them before raising reasoning effort, which adds cost. What's the first step?",
 ["Evaluate with Task Adherence and fix prompts","Raise reasoning_effort to high for all calls","Switch every call to the largest model","Add self-critique by calling the model twice"],0,3,
 "it can help, but it doubles calls before you know what is wrong.",
 "That more thinking is the first fix. Measuring tells you where the problem is first.",
 [["Answers off-task","Instructions or tools","Evaluate, then fix the prompt"],["Measured: hard reasoning fails","Capability","Raise effort or change model"],["Measured: quality varies run to run","Consistency","Self-critique loop"]],
 [["\"improve them before raising reasoning effort\"","Rules out raising effort first."],["\"which adds cost\"","Rules out doubling every call before measuring."]],
 "Evaluate before you escalate effort or model size.",
 "Implement model reflection, chain-of-thought evaluations, and self-critique loops.",
 "Find out why the cake sank before buying a bigger oven."),
Q("q18",2,"2a","A Python service calls models in a Foundry project. You want no API keys and no monthly api-version strings. Which client setup matches the current guidance?",
 ["OpenAI client on /openai/v1/ with an Entra token","AzureOpenAI client with an api-version and key","AzureOpenAI client with an api-version and token","OpenAI client on /openai/v1/ with an API key"],0,2,
 "it's keyless, but it still uses the older pattern with monthly api-version strings.",
 "That the Azure client class is always required for Azure. The v1 routes work with the standard OpenAI client.",
 [["No keys, no api-version","Current pattern","OpenAI() on /openai/v1/ + Entra token"],["Legacy code","Older pattern","AzureOpenAI() with api-version"],["Keys allowed","Simplest, least secure","API key"]],
 [["\"no API keys\"","Rules out both key options."],["\"no monthly api-version strings\"","Rules out the AzureOpenAI client options."]],
 "v1 routes: standard OpenAI client, Entra token provider, no api-version.",
 "Configure an application to connect to a Foundry project.",
 "The new door takes your staff badge and doesn't care what month it is."),
]
