"""Domain 3: Implement computer vision solutions (10-15%). Teaching cards + practice bank. All items original."""
from bank_d1 import T
from d345 import QUESTIONS345, LESSONS345
F = "https://learn.microsoft.com/en-us/azure/foundry/"
AS = "https://learn.microsoft.com/en-us/azure/ai-services/"

def old(d, prefix, skills):
    src = {l["id"]: l["src"][0] for l in LESSONS345}
    return [dict(id=prefix + q["id"], type="single", skill=skills[q["lesson"]], stem=q["stem"], options=q["options"], answer=q["answer"],
                 runner=q["runner"], runnerWhy=q["runnerWhy"], think=q["think"], eli5=q["eli5"], learn=src[q["lesson"]])
            for q in QUESTIONS345 if q["d"] == d]

CLUSTERS = [("A", "Generate images and video"), ("B", "Understand images and video"), ("C", "Safety and provenance")]
CARDS = [
dict(id="3.1", c="A", title="Generate images",
 one="Send a prompt to an image model deployment; get back base64 image data.",
 bridge="**New for you:** Claude reads images but doesn't make them. The prompt craft carries over (be specific about subject, style, framing); the API is OpenAI's images API on a Foundry deployment.",
 steps=["Deploy `gpt-image-2` (or 2.5)","`client.images.generate(model=..., prompt=..., size=...)`","Decode `data[0].b64_json` and save"],
 facts=["**GA:** gpt-image-2 and the gpt-image-2.5 family (custom sizes up to 3840 px).","**Limited access:** gpt-image-1.x. **Retired:** DALL-E 3 (March 2026).","Results are `b64_json`, not URLs.","`background=\"transparent\"` needs PNG output."],
 traps=["DALL-E 3 in an option is a retired service: never correct now.","gpt-image-1 works only after a limited-access approval."],
 checks=["d3-n1","d3-y1"], src=F+"openai/how-to/dall-e"),
dict(id="3.2", c="A", title="Edit images: masks and inpainting",
 one="Send the image, a mask and a prompt; only the masked area is redrawn.",
 bridge="**New for you.** Think of it as a scoped edit: like telling Claude Code to change one function and leave the file alone, the mask is the scope.",
 steps=["Make a PNG mask the same size as the image","Make the area to change **fully transparent**","`client.images.edit(image=..., mask=..., prompt=...)`"],
 facts=["Transparent pixels = edited; opaque pixels = kept.","Up to 16 input images per edit.","`input_fidelity` keeps faces and style closer to the input.","No mask = the prompt can change the whole image."],
 traps=["Black or white for the edit area is other tools' convention; Azure uses transparency.","A mask of a different size is rejected."],
 checks=["d3-q19","d3-c1"], src=F+"openai/how-to/dall-e"),
dict(id="3.3", c="A", title="Generate and remix video (Sora 2)",
 one="Video is a job: create, poll, download. To change a finished video, remix it.",
 bridge="Same shape as the Message Batches API in CCA-F: submit, poll status, fetch results. Nothing comes back on the first call.",
 steps=["`client.videos.create(model=\"sora-2\", prompt=..., size=..., seconds=...)`","Poll `videos.retrieve(id)` until completed","`videos.download_content(id)`; change it later with `videos.remix(id, prompt=...)`"],
 facts=["Sora 2 is **preview**; billed per second of video.","`size` 720x1280 (default) or 1280x720; `seconds` 4, 8 or 12.","`input_reference` sets the first frame and must match `size` exactly.","Rejected: real people, copyrighted characters and music, input images with faces."],
 traps=["Changing one thing in a finished clip = remix, not a new generation.","Any face in the reference image is rejected, however the size is set."],
 checks=["d3-q20","d3-o1"], src=F+"openai/concepts/video-generation"),
dict(id="3.4", c="B", title="Ask a vision model about an image",
 one="Captions, visual Q&A, alt text and 'what's in this photo' go to a vision-capable chat model.",
 bridge="Exactly like sending an image content block to Claude: here it's an `input_image` / `image_url` part with a URL or a base64 data URI.",
 steps=["Put the image in the message as a URL or `data:image/...;base64,`","Ask a specific question; ask for JSON with structured outputs if code reads it","Use `detail: \"low\"` when fine detail doesn't matter"],
 facts=["GPT-4.1 and GPT-5 family models accept images.","`detail: \"low\"` uses fewer tokens; `high` reads fine print.","Images count as input tokens.","For bounding regions and repeatable extraction at scale, prefer Content Understanding."],
 traps=["Image Analysis 4.0 for a new captioning build: deprecated.","A vision model gives answers, not a stable schema, unless you ask for structured outputs."],
 checks=["d3-n2","d3-m1"], src=F+"openai/how-to/gpt-with-vision"),
dict(id="3.5", c="B", title="Content Understanding for images and video",
 one="An analyzer = a field schema + settings; run it on images, documents, audio or video and get structured results with confidence.",
 bridge="Like a tool with a strict input_schema in CCA-F, but for output: you declare the fields, the service fills them and says how sure it is.",
 steps=["Set the resource's default LLM and embedding deployments (once)","Pick a prebuilt analyzer or define fields","`begin_analyze(...)` is long-running: poll for the result"],
 facts=["GA (API 2025-11-01).","Prebuilt: `prebuilt-read`, `prebuilt-layout` (no LLM needed), `prebuilt-imageSearch`, `prebuilt-videoSearch`, `prebuilt-documentSearch`.","Video output: transcript, key frames, per-segment descriptions; segment by your own categories if you want.","Field methods: extract, generate, classify."],
 traps=["It uses **your** model deployments; missing defaults make generative fields fail.","prebuilt-read/layout give text and layout, not your custom fields."],
 checks=["d3-q21","d3-n3","d3-s1"], src=AS+"content-understanding/overview"),
dict(id="3.6", c="B", title="What's retired or restricted in vision",
 one="Know which old vision answers are now wrong.",
 bridge="**New for you.** The CCA-F exam never tested product retirements; AI-103 does, often as the distractor.",
 steps=["Retired → never pick it","Retiring → don't pick it for a new build","Limited access → pick it only if the stem says you have approval"],
 facts=["Image Analysis 4.0: **deprecated**; its custom classification, custom object detection and background removal are **retired**.","Custom Vision: **retiring** (2028).","Face identification and verification: **limited access**.","DALL-E 3: retired."],
 traps=["\"Train a Custom Vision model\" for a new solution is the retiring answer.","Background removal in Image Analysis 4.0 is gone; use image edit with a transparent background instead."],
 checks=["d3-q21","d3-y2"], src=AS+"computer-vision/overview-image-analysis"),
dict(id="3.7", c="C", title="Safety for images: filters and hidden instructions",
 one="Images are filtered like text, and any text read from an image is untrusted data.",
 bridge="Straight from CCA-F: tool results are data, not instructions. An image a user uploads is one more tool result.",
 steps=["Content filters screen image inputs and outputs (hate, sexual, violence, self-harm)","OCR the text, pass it as a delimited document","Prompt Shields for **document (indirect) attacks** at the tool response point"],
 facts=["Prompt Shields: user prompt attacks (direct) and document attacks (indirect).","Agents add tool call and tool response intervention points (preview).","The instruction never gets obeyed, even if it passes the shield: the prompt says to treat it as data."],
 traps=["Text in an image is an indirect attack, not a user prompt attack.","Screening only user input misses attacks that arrive through tools."],
 checks=["d3-q22","d3-s2"], src=F+"openai/concepts/content-filter-prompt-shields"),
dict(id="3.8", c="C", title="Provenance: Content Credentials",
 one="Every generated image carries a signed C2PA manifest saying it was made by AI.",
 bridge="**New for you.** The responsible-AI idea is the same as CCA-F's transparency principle; the mechanism is a signed metadata manifest.",
 steps=["Generate the image","The service attaches a C2PA manifest","Anyone can verify it with a C2PA tool"],
 facts=["C2PA = Coalition for Content Provenance and Authenticity.","It's metadata, not a visible watermark.","Re-encoding or screenshots can strip it: it proves origin when present, not absence when missing."],
 traps=["\"Add a visible watermark\" isn't what Content Credentials do."],
 checks=["d3-y1"], src=F+"openai/concepts/content-credentials"),
]

SK = {"3a": "Generate images and video", "3b": "Generate images and video", "3c": "Understand images and video", "3d": "Safety and provenance"}
G, U, S = SK["3a"], SK["3c"], SK["3d"]
def single(id, skill, stem, options, runner, runnerWhy, think, eli5, learn):
    return dict(id=id, type="single", skill=skill, stem=stem, options=options, answer=0, runner=runner, runnerWhy=runnerWhy, think=think, eli5=eli5, learn=learn)

ITEMS = old(3, "d3-", SK) + [
single("d3-n1", G, "A designer needs product images with no background so they can be placed on any web page. You use gpt-image-2. What should you request?",
 ["background set to transparent, with PNG output","background set to transparent, with JPEG output","A white background, removed later by Image Analysis","A mask that covers the whole background area"], 1,
 "it sets the right background option, but JPEG has no alpha channel to hold transparency.",
 T("That background removal is a separate service. The image model can generate with a transparent background directly.",
   [["Image with no background","Generation option","background=transparent + PNG"],["Remove a background later","Retired feature","Image Analysis background removal: gone"],["Change one area","Edit","Mask"]],
   [["\"no background\"","Transparent background."],["\"placed on any web page\"","Needs alpha: PNG."]],
   "Transparent background needs PNG (or another format with alpha).", "Generate and edit images by using generative image models."),
 "Print the sticker on clear film, not on white paper.", F+"openai/how-to/dall-e"),
single("d3-n2", U, "An app sends thousands of shop-floor photos to a vision model to ask whether a hard hat is visible. Costs are high, and the answer doesn't depend on fine detail. What should you change?",
 ["Set the image detail level to low","Resize the photos to 4K before sending","Switch to Image Analysis 4.0 tagging","Send each photo twice for a second opinion"], 2,
 "it's cheap, but it's deprecated, so a poor choice for new work.",
 T("That lower cost needs another service. The detail setting controls how many tokens an image uses.",
   [["Coarse question, many images","Token cost","detail=low"],["Read fine print","Precision","detail=high"],["New visual tagging build","Deprecated service","Avoid Image Analysis 4.0"]],
   [["\"doesn't depend on fine detail\"","Low detail is enough."],["\"Costs are high\"","Fewer image tokens."]],
   "detail=low cuts image tokens when fine detail doesn't matter.", "Analyze images and video by using multimodal models and Content Understanding."),
 "Glance, don't squint, when you only need to know if someone is wearing a hat.", F+"openai/how-to/gpt-with-vision"),
single("d3-n3", U, "You need a searchable summary of each 30-minute dashcam video, split into segments with a description of each. What should you use?",
 ["Content Understanding prebuilt-videoSearch","A vision model with every frame attached","Sora 2 remix on each video","Speech batch transcription of each video"], 1,
 "it could describe frames, but 30 minutes of frames is far too many tokens and you'd build segmentation yourself.",
 T("That video understanding means sending frames to a chat model. Content Understanding segments and describes video for you.",
   [["Segment and describe video for search","Video analyzer","prebuilt-videoSearch"],["Words spoken only","Audio","Speech transcription"],["Make or change video","Generation","Sora 2"]],
   [["\"split into segments with a description\"","Built-in video output."],["\"searchable\"","The *Search analyzers prepare content for RAG."]],
   "Video RAG prep → Content Understanding prebuilt-videoSearch (transcript, key frames, segment descriptions).",
   "Analyze images and video by using multimodal models and Content Understanding."),
 "Hire the film editor who writes scene notes, not someone flicking through every still.", AS+"content-understanding/overview"),
dict(id="d3-m1", type="multi", pick=2, skill=U,
 stem="An app sends a photo to a vision-capable model in the Responses API. Which two ways can the app supply the image?",
 options=["A public or SAS URL to the image","A base64 data URI in the message","A path on the app server's local disk","The image's C2PA manifest ID","A Content Understanding analyzer ID"],
 answer=[0, 1], runner=2, runnerWhy="the model runs in Azure and can't read your server's disk; send the bytes as base64 instead.",
 think=T("That the model can fetch any file you can see. It can only read a URL it can reach or the bytes you send.",
   [["Image online","Reachable link","URL"],["Image on your machine","Send bytes","base64 data URI"],["Image metadata","Not image data","C2PA manifest"]],
   [["\"supply the image\"","URL or bytes."]],
   "Images go in as a URL or a base64 data URI.", "Analyze images and video by using multimodal models and Content Understanding."),
 eli5="Post the photo or give a link to it; a note saying where it is on your desk won't help.", learn=F+"openai/how-to/gpt-with-vision"),
dict(id="d3-y1", type="yesno", skill=G, stem="For each statement about image generation in Foundry, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="gpt-image-2 is generally available.", answer=True, why="It's the current GA image model."),
  dict(text="DALL-E 3 can still be deployed for new projects.", answer=False, why="It retired in March 2026."),
  dict(text="Generated images carry C2PA Content Credentials.", answer=True, why="A signed provenance manifest."),
  dict(text="Content Credentials add a visible watermark to the image.", answer=False, why="They're metadata, not visible.")],
 think=T("That provenance means a visible mark. It's signed metadata.", None, None,
   "gpt-image-2: GA. DALL-E 3: retired. C2PA: invisible signed metadata.", "Generate and edit images by using generative image models."),
 eli5="A birth certificate in the file, not a stamp on the picture.", learn=F+"openai/concepts/content-credentials"),
dict(id="d3-y2", type="yesno", skill=U, stem="You're choosing a service for a new vision solution. For each statement, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Image Analysis 4.0 custom object detection is available for new models.", answer=False, why="It's retired."),
  dict(text="Custom Vision is a good base for a new long-lived solution.", answer=False, why="It's retiring."),
  dict(text="Face identification requires a limited-access approval.", answer=True, why="Identification and verification are gated."),
  dict(text="Content Understanding can analyse images without a custom model.", answer=True, why="Use prebuilt or schema-defined analyzers.")],
 think=T("That a working service is a good base for new work. Retiring services are distractors for new builds.", None, None,
   "New vision builds → Content Understanding or a vision model. Image Analysis custom: retired. Custom Vision: retiring.",
   "Implement solutions that identify objects, components, or regions within images or video."),
 eli5="Don't open a new shop in a building scheduled for demolition.", learn=AS+"computer-vision/overview-image-analysis"),
dict(id="d3-c1", type="code", skill=G, stem="Complete the code to replace the sky in a photo while keeping everything else.",
 code='r = client.images.edit(model="gpt-image-2",\n    image=open("street.png", "rb"),\n    [[0]]=open("sky.png", "rb"),   # sky area is transparent\n    prompt="Same street under a sunset sky")\nimg = base64.b64decode(r.data[0].[[1]])',
 blanks=[dict(options=["mask","reference","overlay"], answer=0, why="the mask parameter scopes the edit."),
         dict(options=["b64_json","url","content"], answer=0, why="image models return base64.")],
 think=T("That the prompt alone limits an edit. The mask limits it; the prompt says what to draw.", None, None,
   "edit(image, mask, prompt) → b64_json.", "Generate and edit images by using generative image models."),
 eli5="The stencil decides where; the words decide what.", learn=F+"openai/how-to/dall-e"),
dict(id="d3-c2", type="code", skill=G, stem="Complete the code to generate a short clip and fetch it once it's ready.",
 code='job = client.videos.create(model="sora-2", prompt=p, size="1280x720", seconds="8")\nwhile job.status not in ("completed", "failed"):\n    time.sleep(10); job = client.videos.[[0]](job.id)\nclient.videos.[[1]](job.id).write_to_file("clip.mp4")',
 blanks=[dict(options=["retrieve","create","remix"], answer=0, why="poll the job's status."),
         dict(options=["download_content","retrieve","list"], answer=0, why="downloads the finished MP4.")],
 think=T("That create returns the video. It returns a job; you poll, then download.", None, None,
   "create → retrieve (poll) → download_content.", "Generate videos by using generative video models."),
 eli5="Order, check the oven, then take it out.", learn=F+"openai/concepts/video-generation"),
dict(id="d3-o1", type="order", skill=G, stem="A marketing clip must start from a product photo and then be adjusted to an evening scene. Put the four actions in order.",
 pool=["Resize the product photo to the exact output size","Create the video with the photo as input_reference","Poll the job until it completes","Remix the finished video with an 'evening' prompt","Add a mask to the video's first frame","Upload the photo to Content Understanding"],
 answer=[0, 1, 2, 3],
 think=T("That you can remix before the first job finishes. Remix needs a completed video id.", None, None,
   "Match size → create with input_reference → poll → remix.", "Generate videos by using generative video models."),
 eli5="Frame the photo, film it, wait for it, then reshoot at dusk."),
]
GOAL = ("An insurer receives photos of damaged vehicles. Each photo must produce structured fields (damaged part, severity, visible registration) with confidence scores, "
        "and any text in the photo must not be able to change the agent's behaviour. **Goal:** meet both requirements with generally available features.")
def SOL(i, sol, ans, prem, apply, rule):
    return dict(id="d3-s" + str(i), type="solution", skill=S if i == 2 else U, scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(prem, [["Fields with confidence","Analyzer","Content Understanding field schema"],["Text inside images","Indirect attack","Prompt Shields at tool response"],["New build","Retired","Image Analysis custom models"]],
                        apply, rule, "Analyze images and video by using multimodal models and Content Understanding."),
                eli5="Fill in the form from the photo, and treat any note in the photo as evidence, not orders.", learn=AS+"content-understanding/overview")
ITEMS += [
 SOL(1, "Define a Content Understanding analyzer with the three fields, and screen OCR text from each photo with Prompt Shields for document attacks.", True,
   "That safety needs a separate model. A field-schema analyzer gives fields with confidence; document attack screening covers text in images.",
   [["\"structured fields ... with confidence\"","Analyzer: met."],["\"Prompt Shields for document attacks\"","Indirect attack: met."]], "Fields → analyzer. Text in images → document (indirect) attack screening."),
 SOL(2, "Ask a vision model for the three fields as free text, and screen user messages with Prompt Shields for user prompt attacks.", False,
   "That any screening covers images. User prompt screening misses text that arrives inside an image.",
   [["\"free text\"","No confidence scores."],["\"user prompt attacks\"","Wrong attack type."]], "Match the shield to where the text comes from."),
 SOL(3, "Train an Image Analysis 4.0 custom object detection model for the parts, and run Prompt Shields for document attacks on OCR text.", False,
   "That the old custom detection still trains. It's retired.",
   [["\"Image Analysis 4.0 custom object detection\"","Retired: not met."]], "Retired features are never the answer."),
]
BANK = dict(id="d3", minutes=34, items=ITEMS)
