"""Domain 4: Implement text analysis solutions (10-15%). Teaching cards + practice bank. All items original."""
from bank_d1 import T
from dom3 import old, single
F = "https://learn.microsoft.com/en-us/azure/foundry/"
AS = "https://learn.microsoft.com/en-us/azure/ai-services/"

CLUSTERS = [("A", "Analyse text"), ("B", "Translate"), ("C", "Speech")]
CARDS = [
dict(id="4.1", c="A", title="Structured outputs for text analysis",
 one="For new work, sentiment, topics, entities and summaries come from an LLM that must return JSON matching your schema.",
 bridge="The CCA-F pattern of forcing a tool call with a strict input_schema to get reliable JSON. Azure's version: `response_format` with a JSON schema and `strict: true`.",
 steps=["Write the schema (or a Pydantic model)","`responses.parse(..., text_format=Model)` or `response_format={json_schema, strict: true}`","Read typed fields; handle refusals"],
 facts=["Strict mode: every property listed in `required`, `additionalProperties: false`.","JSON mode guarantees valid JSON, **not** your schema.","Optional fields: make the type nullable rather than leaving them out of `required`."],
 traps=["\"JSON mode with an example\" is the runner-up when the stem says code must rely on the shape.","Language sentiment or summarisation for a new service = legacy feature."],
 checks=["d4-q23","d4-c1"], src=F+"openai/how-to/structured-outputs"),
dict(id="4.2", c="A", title="Azure Language: what's still core",
 one="PII detection, named entities, language detection and health text stay with Azure Language.",
 bridge="**New for you.** CCA-F had no managed NLP service; think of these as deterministic, pre-built tools you'd call instead of prompting.",
 steps=["Create a `TextAnalyticsClient` with Entra ID","`recognize_pii_entities(docs, language=...)`","Use `redacted_text` downstream"],
 facts=["PII detection returns entities **and** `redacted_text`.","You can limit PII categories with `categories_filter`.","Text Analytics for health extracts medical entities and relations.","Custom NER is trained on your labelled examples."],
 traps=["PII redaction doesn't need an LLM: Language returns the redacted text.","Detecting language first is often the step before translation."],
 checks=["d4-n1","d4-y1"], src=AS+"language-service/personally-identifiable-information/overview"),
dict(id="4.3", c="A", title="Language retirements",
 one="Several Language features still work but are legacy: don't build new on them.",
 bridge="**New for you.** Retirement dates are a favourite distractor: the working-but-retiring service is the runner-up.",
 steps=["Retired → never pick","Legacy → don't pick for new work","Core → fine"],
 facts=["**Retired:** LUIS (31 Mar 2026).","**Legacy, retire 31 Mar 2029:** sentiment and opinion mining, key phrases, summarisation, CLU, custom question answering, custom text classification.","**Entity linking:** retires 1 Sep 2028.","Language Studio moves into Foundry (studio retires 20 Mar 2027)."],
 traps=["Entity linking retires a year before the other legacy features.","\"Use CLU\" for a new intent model: legacy; an LLM with structured outputs or an agent is the forward path."],
 checks=["d4-y1"], src=AS+"language-service/overview"),
dict(id="4.4", c="B", title="Translate text: NMT or an LLM",
 one="Translator picks the engine per target: classic neural MT by default, or your LLM deployment with tone and gender.",
 bridge="Like choosing a model per request in CCA-F, but inside one Translator call: each target language can name its own deployment.",
 steps=["`TranslationTarget(language=\"hi\")` → NMT","Add `deployment_name=...` → LLM translation","Add `tone=\"formal\"` (LLM only)"],
 facts=["Text API `2026-06-06` (GA).","NMT default category: `general`.","Adaptive custom translation uses reference sentence pairs, no full training.","Language auto-detects if you omit the source."],
 traps=["Tone needs the LLM option; NMT ignores it.","Custom training isn't needed for tone."],
 checks=["d4-q24","d4-n2"], src=AS+"translator/whats-new"),
dict(id="4.5", c="B", title="Translate documents",
 one="One file now → synchronous. Many files → batch from Blob Storage.",
 bridge="Same split as single request vs Message Batches in CCA-F: immediate and small, or asynchronous and bulk.",
 steps=["Single file: send it in the request, get the translated file back","Batch: source and target Blob containers","Batch identity: managed identity or SAS to the containers"],
 facts=["Document translation `2026-03-01` (GA).","Keeps the document's formatting (Word, PDF, PowerPoint and more).","Glossaries enforce your terms.","Batch is asynchronous: poll the job."],
 traps=["Batch for one file needed in the same request: wrong mode.","Translating extracted text loses formatting."],
 checks=["d4-o1"], src=AS+"translator/document-translation/overview"),
dict(id="4.6", c="C", title="Speech to text: pick the mode",
 one="One utterance, a live stream, a single file now, or many files later: each has its own mode.",
 bridge="**New for you.** The pattern matches CCA-F's sync vs batch choice; the names are the Speech SDK's.",
 steps=["One short phrase → `recognize_once`","Live, long audio → continuous recognition","One file, quick → fast transcription; many stored files → batch transcription"],
 facts=["`recognize_once` stops at the first pause (about 15 s max).","Batch transcription reads files from storage URLs and runs asynchronously.","Phrase lists boost recognition of names without training.","Custom speech trains on your audio and text for domain terms and accents."],
 traps=["recognize_once on a long file returns one sentence.","Custom speech ≠ custom voice."],
 checks=["d4-q25","d4-q26","d4-n3"], src=AS+"speech-service/overview"),
dict(id="4.7", c="C", title="Text to speech and SSML",
 one="Neural voices speak text; SSML controls voice, speed, pauses and pronunciation.",
 bridge="**New for you.** SSML is to speech what a system prompt is to tone, but deterministic markup.",
 steps=["Pick a neural voice (`speech_synthesis_voice_name`)","Plain text → `speak_text_async`; markup → `speak_ssml_async`","Set the output format for your channel"],
 facts=["`<prosody rate pitch>`, `<break time>`, `<phoneme>`, `<say-as>`.","Custom voice = your own brand voice (limited access).","Speech translation: `TranslationRecognizer` with `add_target_language`."],
 traps=["SSML sent with `speak_text_async` is read out as text.","Custom voice changes output, not recognition."],
 checks=["d4-c2","d4-y2"], src=AS+"speech-service/speech-synthesis-markup"),
dict(id="4.8", c="C", title="Voice agents: Voice Live",
 one="Voice Live runs the whole speech-to-speech loop for an agent: listening, turn-taking and speaking.",
 bridge="A CCA-F agent loop with a voice front end. Instead of wiring STT → model → TTS yourself, one managed service does it.",
 steps=["Open a Voice Live session (WebSocket)","Choose the model and voice","Stream audio both ways; it handles interruptions"],
 facts=["Noise suppression, echo cancellation, semantic turn detection.","Avatars and telephony integrations.","`gpt-realtime` is GA.","Content filters don't apply to audio models."],
 traps=["Chaining three services is the runner-up when the stem says low latency and fewest parts."],
 checks=["d4-s1"], src=AS+"speech-service/voice-live"),
]

SK = {"4a": "Analyse text", "4b": "Translate", "4c": "Speech"}
A, TR, SP = SK["4a"], SK["4b"], SK["4c"]
ITEMS = old(4, "d4-", SK) + [
single("d4-n1", A, "Support transcripts must be stored with names, phone numbers and card numbers hidden, but addresses kept for routing. What should you use?",
 ["Language PII detection with a category filter","Language PII detection with default settings","An LLM prompted to remove personal details","Language named entity recognition on each line"], 1,
 "it redacts personal data, but by default it would hide addresses too.",
 T("That PII detection is all or nothing. You can choose which categories it redacts.",
   [["Redact some PII, keep other types","Selective","categories_filter"],["Redact all PII","Default","PII detection"],["Find people, places, organisations","Not redaction","NER"]],
   [["\"names, phone numbers and card numbers hidden\"","PII redaction."],["\"addresses kept\"","Needs a category filter."]],
   "Language PII: redacted_text, narrowed with categories_filter.", "Implement text analysis, such as entity extraction, sentiment analysis, and PII detection."),
 "Black out the phone numbers, but leave the street name for the courier.", AS+"language-service/personally-identifiable-information/overview"),
single("d4-n2", TR, "Product descriptions must be translated into German with your brand's terms kept exactly, such as 'ClaimSnap'. What should you add?",
 ["A glossary for the translation","A formal tone on an LLM target","Custom speech trained on the terms","Language detection before translating"], 1,
 "tone changes register, not specific terms.",
 T("That an LLM always keeps brand names. A glossary enforces your terms.",
   [["Keep specific terms exactly","Terminology","Glossary"],["Formal or informal register","Style","tone (LLM)"],["Unknown source language","Detection","Auto-detect"]],
   [["\"brand's terms kept exactly\"","A glossary."]],
   "Exact terms → glossary. Register → tone.", "Translate text and documents by using Azure Translator."),
 "Hand the translator a list of words they must not change.", AS+"translator/document-translation/overview"),
single("d4-n3", SP, "A call-centre app transcribes live calls. It keeps mishearing 20 product names, and you need a fix today without training. What should you add?",
 ["A phrase list with the product names","A custom speech model trained on calls","A custom neural voice for the agent","SSML phoneme tags on each product name"], 1,
 "it gives the biggest accuracy gain, but needs data and training time.",
 T("That every recognition fix needs training. A phrase list boosts known words immediately.",
   [["A few known words, no training","Boost","Phrase list"],["Domain language, accents, time to train","Model","Custom speech"],["How the agent sounds","Output","Custom voice / SSML"]],
   [["\"fix today without training\"","Rules out custom speech."],["\"20 product names\"","A short list: phrase list."]],
   "Quick boost for names → phrase list. Broad domain accuracy → custom speech.", "Implement speech-to-text and text-to-speech."),
 "Give the listener a cheat-sheet before the call.", AS+"speech-service/improve-accuracy-phrase-list"),
dict(id="d4-y1", type="yesno", skill=A, stem="For each statement about Azure Language, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Entity linking retires before the other legacy Language features.", answer=True, why="1 Sep 2028 vs 31 Mar 2029."),
  dict(text="PII detection is a legacy feature.", answer=False, why="It's core."),
  dict(text="Key phrase extraction is a good base for a new service.", answer=False, why="It's legacy; use an LLM with structured outputs."),
  dict(text="LUIS has been retired.", answer=True, why="31 Mar 2026.")],
 think=T("That every Language feature is retiring. PII and NER are core.", None, None,
   "Core: PII, NER, language detection, health. Legacy: sentiment, key phrases, summarisation, CLU, CQA. Retired: LUIS.",
   "Implement text analysis, such as entity extraction, sentiment analysis, and PII detection."),
 eli5="Some rooms are being kept, some are being emptied; know which.", learn=AS+"language-service/overview"),
dict(id="d4-y2", type="yesno", skill=SP, stem="For each statement about Azure Speech, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="speak_ssml_async lets you change speaking rate with prosody.", answer=True, why="<prosody rate> in SSML."),
  dict(text="Custom voice needs a limited-access approval.", answer=True, why="It's a gated feature."),
  dict(text="Batch transcription returns results in the same HTTP call.", answer=False, why="It's asynchronous."),
  dict(text="Content filters apply to audio models such as gpt-realtime.", answer=False, why="They don't apply to audio.")],
 think=T("That every service is synchronous and filtered alike. Batch is asynchronous; audio models aren't content-filtered.", None, None,
   "SSML via speak_ssml_async. Custom voice: limited access. Batch: async.", "Implement speech-to-text and text-to-speech."),
 eli5="Write stage directions for the voice; send big jobs to the overnight queue.", learn=AS+"speech-service/overview"),
dict(id="d4-c1", type="code", skill=A, stem="Complete the code so each claim email returns fields your code can rely on.",
 code='class Claim(BaseModel):\n    policy_no: str\n    sentiment: Literal["positive", "neutral", "negative"]\n    summary: str\nr = client.responses.[[0]](model=m, input=email, [[1]]=Claim)\nclaim = r.output_parsed',
 blanks=[dict(options=["parse","create","stream"], answer=0, why="parse validates the output into the model."),
         dict(options=["text_format","response_format_json","schema_hint"], answer=0, why="the Responses API takes the Pydantic model as text_format.")],
 think=T("That asking for JSON in the prompt is enough. parse with a model enforces the schema.", None, None,
   "responses.parse(..., text_format=Model) → output_parsed.", "Implement solutions to extract entities, topics, summaries, and structured JSON outputs by using generative prompting and Foundry Tools."),
 eli5="Hand over a form with fixed boxes.", learn=F+"openai/how-to/structured-outputs"),
dict(id="d4-c2", type="code", skill=SP, stem="Complete the code to speak a reply slowly with a chosen neural voice.",
 code='cfg.speech_synthesis_voice_name = "en-GB-SoniaNeural"\nssml = \'<speak version="1.0" xml:lang="en-GB"><voice name="en-GB-SoniaNeural">\'\nssml += \'<[[0]] rate="-20%">Your claim is approved.</[[0]]></voice></speak>\'\nresult = synth.[[1]](ssml).get()',
 blanks=[dict(options=["prosody","break","phoneme"], answer=0, why="prosody controls rate and pitch."),
         dict(options=["speak_ssml_async","speak_text_async","recognize_once_async"], answer=0, why="SSML needs speak_ssml_async; speak_text_async reads the tags aloud.")],
 think=T("That any speak call understands markup. Only the SSML method does.", None, None,
   "SSML → speak_ssml_async; rate and pitch → <prosody>.", "Implement speech-to-text and text-to-speech."),
 eli5="Stage directions only work if you hand over the script, not just read it.", learn=AS+"speech-service/speech-synthesis-markup"),
dict(id="d4-o1", type="order", skill=TR, stem="Each night, hundreds of Word files in Blob storage must be translated into French and Spanish. Put the four actions in order.",
 pool=["Create source and target Blob containers","Give the Translator resource's managed identity access to them","Start a batch document translation job","Poll the job, then read the translated files","Call synchronous document translation per file","Train a custom speech model on the files"],
 answer=[0, 1, 2, 3],
 think=T("That batch translation reads files from your app. It reads and writes Blob containers itself.", None, None,
   "Containers → access → start batch → poll.", "Translate text and documents by using Azure Translator."),
 eli5="Set out the in-tray and out-tray, give the translator a key, then collect in the morning."),
]
GOAL = ("A bank's voice agent must talk with customers on the phone with low latency, let them interrupt, and speak in a formal register. "
        "**Goal:** meet the requirements with the fewest services to integrate.")
def SOL(i, sol, ans, prem, apply, rule):
    return dict(id="d4-s" + str(i), type="solution", skill=SP, scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(prem, [["Live, interruptible voice","Speech to speech","Voice Live"],["Separate STT, model, TTS","Pipeline","More parts, more latency"],["Stored recordings","Offline","Batch transcription"]],
                        apply, rule, "Implement speech-to-text and text-to-speech."),
                eli5="One phone line beats three people passing notes.", learn=AS+"speech-service/voice-live")
ITEMS += [
 SOL(1, "Use the Voice Live API with telephony integration, and set the formal register in the agent's instructions.", True,
   "That voice agents need a hand-built pipeline. Voice Live handles turn-taking and interruption in one service.",
   [["\"Voice Live ... telephony\"","Low latency, interruptions, phone: met."],["\"instructions\"","Register is a prompt matter: met."]], "Real-time voice agent → Voice Live."),
 SOL(2, "Chain continuous recognition, a model deployment, and neural text to speech.", False,
   "That working means meeting the goal. It works, but it's three services, not the fewest.",
   [["\"Chain\" three services","Not the fewest."]], "Fewest components for a voice agent → Voice Live."),
 SOL(3, "Use batch transcription on recorded calls and reply by text message.", False,
   "That any speech service fits. Batch is offline; the goal is a live conversation.",
   [["\"recorded calls\"","Not live."]], "Live conversation needs real-time audio."),
]
BANK = dict(id="d4", minutes=34, items=ITEMS)
