"""Domain 5: Implement information extraction solutions (10-15%). Teaching cards + practice bank. All items original."""
from bank_d1 import T
from dom3 import old, single
F = "https://learn.microsoft.com/en-us/azure/foundry/"
AS = "https://learn.microsoft.com/en-us/azure/ai-services/"
SR = "https://learn.microsoft.com/en-us/azure/search/"

CLUSTERS = [("A", "Build the search index"), ("B", "Query and connect to agents"), ("C", "Extract from documents")]
CARDS = [
dict(id="5.1", c="A", title="The indexing pipeline",
 one="Data source → indexer → skillset → index: the indexer pulls content, skills enrich it, the index stores it.",
 bridge="The retrieval half of CCA-F RAG, made concrete: chunking, embedding and storing are pipeline stages you configure, not code you write.",
 steps=["Data source (Blob, SQL, Cosmos DB, OneLake…)","Skillset: crack/layout → Text Split → embedding","Index projections write one document per chunk"],
 facts=["Skills: OCR, Document Layout, **Content Understanding skill** (GA), Text Split, Azure OpenAI Embedding, GenAI Prompt; custom logic via the **Web API skill**.","Indexers run on a schedule and pick up changes.","Index projections map one source file to many chunk documents."],
 traps=["The semantic ranker isn't a pipeline stage; it runs at query time.","Custom code in the pipeline = Web API custom skill."],
 checks=["d5-o1","d5-n1"], src=SR+"cognitive-search-concept-intro"),
dict(id="5.2", c="A", title="Fields and integrated vectorization",
 one="Field attributes decide what a field can do; vectors need a vector field, an embedding skill and a vectorizer.",
 bridge="**New for you.** CCA-F treated the retriever as a black box; here you set the schema yourself.",
 steps=["Mark fields searchable, filterable, sortable, facetable, retrievable; one `key`","Add a vector field with dimensions and a vector profile (HNSW)","Embedding skill at indexing + vectorizer at query time"],
 facts=["Filters need `filterable`; facets need `facetable`.","HNSW = approximate and fast; exhaustive KNN = exact and slow.","Vector filters apply before the vector search by default (pre-filter)."],
 traps=["Embedding skill without a vectorizer: text vector queries fail.","Changing a field's attributes usually means rebuilding the index."],
 checks=["d5-q27","d5-y1"], src=SR+"vector-search-integrated-vectorization"),
dict(id="5.3", c="B", title="Query types: keyword, vector, hybrid, semantic",
 one="Keyword finds exact words, vector finds meaning, hybrid does both, the semantic ranker reorders the top results.",
 bridge="CCA-F said retrieval quality decides answer quality. This card is the menu of retrieval styles and when each wins.",
 steps=["Exact IDs only → keyword (BM25)","Paraphrase → vector","Both → hybrid (RRF); best order → add `query_type=semantic`"],
 facts=["Hybrid merges lists with **Reciprocal Rank Fusion**.","The semantic ranker reranks the **top 50** and returns captions and answers.","`VectorizableTextQuery` sends text (needs a vectorizer); `VectorizedQuery` sends your vector.","Scoring profiles boost by field or freshness."],
 traps=["Semantic ranker can't find documents keyword search missed.","Pure vector search misses exact codes."],
 checks=["d5-q28","d5-c1"], src=SR+"hybrid-search-overview"),
dict(id="5.4", c="B", title="Knowledge bases and Foundry IQ",
 one="A knowledge base retrieves across several sources for an agent, which connects to it over MCP.",
 bridge="Like CCA-F's subagent that does research and returns findings: the knowledge base plans and runs retrieval, and the agent gets passages back.",
 steps=["Create knowledge sources (index, Blob, OneLake, web…)","Create a knowledge base over them","Connect the agent to its MCP endpoint with the project's managed identity"],
 facts=["Renamed from 'knowledge agents' (Nov 2025).","**GA: extractive retrieval.** Query planning, answer synthesis and reasoning effort: preview.","Tool: `knowledge_base_retrieve`."],
 traps=["Answer synthesis in a GA-only stem: wrong.","File search for organisational knowledge: wrong tool."],
 checks=["d5-q30","d5-s1"], src=F+"agents/concepts/what-is-foundry-iq"),
dict(id="5.5", c="B", title="Search access and security",
 one="Use Entra roles for search: one to query, one to load, one to manage.",
 bridge="CCA-F's least-privilege tools principle, as Azure role names.",
 steps=["Query → Search Index Data Reader","Load documents → Search Index Data Contributor","Create indexes, indexers → Search Service Contributor"],
 facts=["Turn on role-based access on the search service; you can then disable keys.","Indexers reach data sources with the search service's managed identity.","Private endpoints and shared private links for private data."],
 traps=["Service Contributor manages objects but can't query data.","An agent's Search tool needs the project identity to have the right Search roles."],
 checks=["d5-n2"], src=SR+"search-security-rbac"),
dict(id="5.6", c="C", title="Choose: Content Understanding or Document Intelligence",
 one="Content Understanding for multimodal, RAG and schema-defined fields; Document Intelligence for standard forms, labelled custom models and offline containers.",
 bridge="**New for you.** A service-choice question; the stem's constraint (no labels, offline, many layouts) picks the service.",
 steps=["Offline or on-premises → Document Intelligence container","Standard form (invoice, receipt, ID) → prebuilt model","Varied layouts, no labelling, RAG → Content Understanding"],
 facts=["Document Intelligence v4.0 is GA and **not deprecated**.","Custom template = fixed layout; custom neural = varied structured layouts (as few as 5 labelled samples).","Content Understanding uses your LLM deployments; read/layout don't need them."],
 traps=["\"Newest service always\" fails the offline case.","Custom neural still needs labelled samples."],
 checks=["d5-q29","d5-y2"], src=AS+"content-understanding/choosing-right-ai-tool"),
dict(id="5.7", c="C", title="Content Understanding analyzers",
 one="Define the fields you want; the analyzer extracts, generates or classifies them, with confidence and source location.",
 bridge="A strict output schema, as in CCA-F extraction, with grounding: each value points to where it came from.",
 steps=["Base on a prebuilt (`prebuilt-document`) or start blank","Add fields: name, type, method (extract / generate / classify)","Analyze; read values, confidence and source"],
 facts=["Classify fields take a fixed set of categories.","Confidence lets you route low-confidence results to a person.","Analyze is long-running: poll."],
 traps=["Generated fields aren't copied from the document: use extract when the value must appear verbatim."],
 checks=["d5-n3","d5-c2"], src=AS+"content-understanding/overview"),
]

SK = {"5a": "Build the search index", "5b": "Query and connect to agents", "5c": "Extract from documents"}
IX, QA, EX = "Build the search index", "Query and connect to agents", "Extract from documents"
ITEMS = old(5, "d5-", SK)
for q in ITEMS:   # q27 is an indexing question, q28 a query one
    if q["id"] == "d5-q27": q["skill"] = IX
    if q["id"] == "d5-q28": q["skill"] = QA
ITEMS += [
single("d5-n1", IX, "An indexing pipeline must call your own Python function to mask account numbers before chunks are stored. What should you add to the skillset?",
 ["A Web API custom skill","A GenAI Prompt skill","A scoring profile on the index","A synonym map on the account field"], 1,
 "it can transform text with a model, but you need your own deterministic code, not a prompt.",
 T("That all enrichment uses built-in skills. Your own code plugs in as a Web API skill.",
   [["Your own code in the pipeline","Custom","Web API skill"],["Model-written enrichment","Prompt","GenAI Prompt skill"],["Query-time ranking","Not indexing","Scoring profile"]],
   [["\"call your own Python function\"","Custom code."],["\"before chunks are stored\"","An indexing-time skill."]],
   "Custom pipeline logic → Web API custom skill (an HTTP endpoint, such as an Azure Function).", "Implement content extraction and indexing pipelines by using Azure AI Search."),
 "Plug your own machine into the conveyor belt.", SR+"cognitive-search-custom-skill-web-api"),
single("d5-n2", QA, "An app's managed identity must run queries against an index, and nothing else. Which role should you assign?",
 ["Search Index Data Reader","Search Index Data Contributor","Search Service Contributor","Reader on the search service"], 1,
 "it can query, but it can also load and delete documents.",
 T("That the management role includes queries. Data roles and service roles are separate.",
   [["Query only","Data, read","Search Index Data Reader"],["Load documents","Data, write","Search Index Data Contributor"],["Manage indexes","Control plane","Search Service Contributor"]],
   [["\"run queries ... and nothing else\"","Read data only."]],
   "Query → Data Reader. Load → Data Contributor. Manage → Service Contributor.", "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "A library card, not a librarian's key.", SR+"search-security-rbac"),
single("d5-n3", EX, "An analyzer must label each incoming document as invoice, receipt or contract, and route it. What should you define?",
 ["A field using the classify method with the three categories","A field using the generate method","A field using the extract method","A separate Translator call per document"], 1,
 "it would produce a label, but in free form; classify restricts it to your categories.",
 T("That a generated value is as good as a category. Classify returns one of your fixed labels.",
   [["One of fixed labels","Classify","classify + categories"],["Value written by the model","Generate","generate"],["Value copied from the page","Extract","extract"]],
   [["\"invoice, receipt or contract\"","A fixed set."],["\"route it\"","Code needs exact labels."]],
   "Fixed labels → classify. Verbatim values → extract. Summaries → generate.", "Extract structured content from documents, forms, and images by using Content Understanding."),
 "Tick one of three boxes rather than write a description.", AS+"content-understanding/overview"),
dict(id="d5-m1", type="multi", pick=2, skill=IX,
 stem="Users must filter results by region and see counts per product type in a sidebar. Which two field attributes do you need?",
 options=["filterable on region","facetable on product type","sortable on region","searchable on product type","key on region"],
 answer=[0, 1], runner=3, runnerWhy="searchable allows full-text matching, not counts.",
 think=T("That searchable covers every query feature. Filters and facets have their own attributes.",
   [["Restrict results","Filter","filterable"],["Counts per value","Facets","facetable"],["Full-text match","Search","searchable"]],
   [["\"filter by region\"","filterable."],["\"counts per product type\"","facetable."]],
   "Filter → filterable. Counts → facetable. Order → sortable.", "Implement content extraction and indexing pipelines by using Azure AI Search."),
 eli5="Sieve by region, tally by product.", learn=SR+"search-what-is-an-index"),
dict(id="d5-y1", type="yesno", skill=IX, stem="For each statement about integrated vectorization, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="An embedding skill vectorizes chunks at indexing time.", answer=True, why="The skill embeds content."),
  dict(text="A vectorizer embeds query text at query time.", answer=True, why="Needed for VectorizableTextQuery."),
  dict(text="HNSW returns exact nearest neighbours.", answer=False, why="It's approximate; exhaustive KNN is exact."),
  dict(text="Index projections let one PDF become many chunk documents.", answer=True, why="One-to-many mapping.")],
 think=T("That HNSW is exact. It trades exactness for speed.", None, None,
   "Embedding skill (index) + vectorizer (query). HNSW approximate; KNN exact.", "Configure retrieval and indexing strategies, such as hybrid search, semantic search, and vector search."),
 eli5="Two translators: one for the books, one for your question.", learn=SR+"vector-search-integrated-vectorization"),
dict(id="d5-y2", type="yesno", skill=EX, stem="For each statement about document extraction, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Document Intelligence is deprecated.", answer=False, why="v4.0 is GA and supported."),
  dict(text="Custom neural models need labelled samples.", answer=True, why="As few as 5, but labelled."),
  dict(text="Content Understanding prebuilt-layout needs an LLM deployment.", answer=False, why="Read and layout don't."),
  dict(text="Disconnected sites need Document Intelligence containers.", answer=True, why="Content Understanding is cloud-only.")],
 think=T("That the older service is on its way out. Document Intelligence stays for forms, labelled models and containers.", None, None,
   "DI: prebuilt forms, custom models, containers. CU: schema fields, multimodal, RAG.", "Extract structured content from documents, forms, and images by using Content Understanding."),
 eli5="Two good tools; the job picks the tool.", learn=AS+"content-understanding/choosing-right-ai-tool"),
dict(id="d5-c1", type="code", skill=QA, stem="Complete the code to run a keyword-plus-vector query on text you already embedded yourself, filtered to one region.",
 code='vq = [[0]](vector=embedding, k_nearest_neighbors=50, fields="contentVector")\nresults = search.search(search_text=q, vector_queries=[vq],\n    [[1]]="region eq \'EU\'", top=5)',
 blanks=[dict(options=["VectorizedQuery","VectorizableTextQuery","SemanticQuery"], answer=0, why="you pass your own vector."),
         dict(options=["filter","search_fields","facets"], answer=0, why="an OData filter; the field must be filterable.")],
 think=T("That every vector query sends text. If you embedded it, send the vector.", None, None,
   "Own vector → VectorizedQuery. Text → VectorizableTextQuery. Restrict → filter.", "Configure retrieval and indexing strategies, such as hybrid search, semantic search, and vector search."),
 eli5="Hand over the coordinates you already worked out.", learn=SR+"vector-search-how-to-query"),
dict(id="d5-c2", type="code", skill=EX, stem="Complete the analyzer field so the total is copied exactly from the document.",
 code='"fieldSchema": {"fields": {\n  "total": {"type": "number", "method": "[[0]]"},\n  "doc_kind": {"type": "string", "method": "[[1]]",\n               "enum": ["invoice", "receipt", "contract"]}}}',
 blanks=[dict(options=["extract","generate","classify"], answer=0, why="copied verbatim from the document."),
         dict(options=["classify","extract","generate"], answer=0, why="one of fixed categories.")],
 think=T("That the method doesn't matter. Extract copies; classify picks; generate writes.", None, None,
   "extract = verbatim; classify = fixed labels; generate = model-written.", "Extract structured content from documents, forms, and images by using Content Understanding."),
 eli5="Copy the number, tick the box.", learn=AS+"content-understanding/overview"),
dict(id="d5-o1", type="order", skill=IX, stem="You're setting up integrated vectorization for PDFs in Blob storage. Put the five configuration steps in order.",
 pool=["Create a data source for the Blob container","Create the index with a vector field and a vectorizer","Create a skillset with Text Split and an embedding skill","Create the indexer linking data source, skillset and index","Run the indexer and check the document count","Enable the semantic ranker on the agent","Create a knowledge base before the index"],
 answer=[0, 1, 2, 3, 4],
 think=T("That the indexer comes first. It references the other three, so it's created last.", None, None,
   "Data source → index → skillset → indexer → run.", "Implement content extraction and indexing pipelines by using Azure AI Search."),
 eli5="Lay out the shelf, the books and the tools before hiring the librarian."),
]
GOAL = ("A field office with no internet connection must extract totals and dates from standard supplier invoices. "
        "**Goal:** run extraction on-site with no cloud calls.")
def SOL(i, sol, ans, prem, apply, rule):
    return dict(id="d5-s" + str(i), type="solution", skill=EX, scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(prem, [["Offline, standard forms","Containers","DI prebuilt invoice container"],["Cloud, varied layouts","Generative","Content Understanding"],["Index for search","Not extraction","AI Search"]],
                        apply, rule, "Extract structured content from documents, forms, and images by using Content Understanding."),
                eli5="Take the scanner to the site when the site has no signal.", learn=AS+"document-intelligence/containers/install-run")
ITEMS += [
 SOL(1, "Run the Document Intelligence prebuilt invoice model in a disconnected container.", True,
   "That disconnected sites can't do extraction. Document Intelligence ships disconnected containers.",
   [["\"disconnected container\"","No cloud calls: met."],["\"prebuilt invoice\"","Standard invoices: met."]], "Offline → Document Intelligence containers."),
 SOL(2, "Use a Content Understanding custom analyzer with the two fields.", False,
   "That the newest service runs anywhere. Content Understanding is cloud-only.",
   [["\"Content Understanding\"","Needs the cloud: not met."]], "Content Understanding has no disconnected container."),
 SOL(3, "Run an Azure AI Search indexer with the OCR skill on the invoices.", False,
   "That OCR is extraction. Search indexes content in the cloud; it doesn't return invoice fields on-site.",
   [["\"Azure AI Search\"","Cloud service: not met."]], "Search builds an index; it isn't an offline form extractor."),
]
BANK = dict(id="d5", minutes=34, items=ITEMS)
