"""Domain 1 teaching cards: identity and access in Foundry. Checked against Microsoft Learn (RBAC for Foundry, updated 22 Sep 2026)."""
L = "https://learn.microsoft.com/en-us/azure/foundry/"
CLUSTERS = [("R", "Identity and access in Foundry")]
CARDS = [
dict(id="1.R1", c="R", title="The five Foundry roles, and the two Azure roles that can't build",
 one="Use agents → Agent Consumer. Build → Foundry User. Lead a team and publish → Project Manager. Set up resources, no building → Account Owner. Everything → Foundry Owner.",
 bridge="**New for you.** CCA-F had API keys and workspaces, not role scopes. Think of it as Claude Console roles, but enforced by Azure RBAC at resource, project and agent level.",
 steps=["Decide what the principal must **do**: call, build, publish, set up","Pick the smallest role that does it","Pick the smallest **scope**: agent, project, or resource"],
 facts=["**Foundry Agent Consumer:** call agent endpoints only. Assignable down to **one agent**.",
        "**Foundry User** (was Azure AI User): build, test, evaluate in a project; read access. Least privilege for developers and for the **project's managed identity**.",
        "**Foundry Project Manager:** build + manage projects + assign *only* Foundry User + **publish agents** (the minimum role to publish).",
        "**Foundry Account Owner:** create resources and projects, manage models, assign Foundry User / ACR / monitoring roles. **No data actions: can't build.**",
        "**Foundry Owner:** all of the above, building included.",
        "Azure **Owner** and **Contributor** manage resources (Contributor can deploy models) but have **no data actions**."],
 traps=["Owner or Contributor on the subscription still can't create an agent: add Foundry User.","**Azure AI Developer** is for hubs and Azure Machine Learning, not Foundry projects.","Don't use *Cognitive Services …* roles for Foundry, except **Cognitive Services Usages Reader** for quota.","Renamed roles keep their role IDs; scripts should use the ID."],
 checks=["d1-r1","d1-r2","d1-r3"], src=L+"concepts/rbac-foundry"),
dict(id="1.R2", c="R", title="Scopes and the two hops of identity",
 one="The caller needs a role on Foundry; the project's managed identity needs roles on everything Foundry reaches for it.",
 bridge="Like an MCP server that calls another API with its own credentials: the user is allowed into the server, and the server separately needs rights downstream.",
 steps=["Hop 1: user or app → Foundry (Foundry roles, at resource, project or agent scope)","Hop 2: project managed identity → Search, Storage and other connected resources (their data roles)","Check both when you see a 403"],
 facts=["Scopes: subscription → resource group → **Foundry resource → project → agent**.",
        "Agent scope is evaluated **only for calling that agent's endpoint**.",
        "The Azure portal assigns Agent Consumer **only at account scope**; use the **Azure CLI** for project or agent scope.",
        "Project managed identity examples: **Storage Blob Data Reader** on a storage account; Search roles (Search Index Data Contributor, Search Service Contributor) on AI Search for the Search tool.",
        "Quota and deployment eligibility: **Cognitive Services Usages Reader at subscription scope**; resource or project scope doesn't work."],
 traps=["Giving the *developer* a Search role doesn't fix the agent's Search tool: the call is made by the project's identity.","A project-scope Agent Consumer can call **every** agent in the project."],
 checks=["d1-r4","d1-r5","d1-r6"], src=L+"concepts/rbac-foundry"),
dict(id="1.R3", c="R", title="Keys, tokens, and how Foundry differs from other AI services",
 one="Entra ID + Azure RBAC, like the rest of Azure; but keys skip RBAC entirely, and roles differ by resource type.",
 bridge="Same split as Storage or Key Vault: owning the account isn't the same as reading the data. Control plane and data plane are separate permissions.",
 steps=["Prefer Entra ID; disable keys where possible","Use the token audience `https://ai.azure.com/.default` for the v1 API and projects","Match the role family to the resource type"],
 facts=["An **API key grants full access with no role checks**. Agents and evaluations need Entra ID anyway.",
        "Creating a resource or project **in the portal** auto-assigns Foundry User to you and the project identity, if you can assign roles; **SDK or CLI deployments don't**.",
        "**Fine-tuning** needs both planes: **Foundry Owner**, or Foundry User + Foundry Account Owner.",
        "Role families: Foundry resource and projects → **Foundry roles**; standalone Azure OpenAI or AI services resource → **Cognitive Services** roles (e.g. Cognitive Services OpenAI User); hub projects → **Azure AI Developer** and Azure ML roles."],
 traps=["Expecting RBAC to limit a key holder: it doesn't.","Using Cognitive Services OpenAI User for a Foundry project instead of Foundry User."],
 checks=["d1-r7"], src=L+"concepts/authentication-authorization-foundry"),
]
