"""Domain 2 teaching cards: Implement generative AI and agentic solutions (30-35%).
Each card: one-liner, bridge from CCA-F, how it works (steps), must-know facts, traps, checks (practice item ids)."""
L = "https://learn.microsoft.com/en-us/azure/foundry/"
CLUSTERS = [
 ("A", "Build generative applications with Foundry"),
 ("B", "Build agents with Foundry"),
 ("C", "Optimise and operationalise"),
]
CARDS = [
# ---- A ----
dict(id="2.1", c="A", title="Connect an app to a Foundry project",
 one="One project endpoint, one keyless credential, and you get an OpenAI-compatible client for models and agents.",
 bridge="Like creating an `Anthropic()` client with an API key, except Azure prefers your Entra identity over a key, and the client is bound to a **project**.",
 steps=["`AIProjectClient(endpoint, DefaultAzureCredential())`","`project.get_openai_client()`","`client.responses.create(model=..., input=...)`"],
 facts=["Endpoint: `https://<resource>.services.ai.azure.com/api/projects/<project>`.","Package `azure-ai-projects` 2.x; 1.x code doesn't run on it.","Direct model calls can also use `OpenAI(base_url=\".../openai/v1/\")` with an Entra token: no `api-version`."],
 traps=["`AzureOpenAI()` with an `api-version` is the older pattern.","Agents and evaluations need Entra ID; keys fail there."],
 checks=["d2-c1","d2-q18"], src=L+"quickstarts/get-started-code"),
dict(id="2.2", c="A", title="Deploy and consume models",
 one="Pick a model from the catalogue, deploy it with a deployment type, then call it through the Responses API.",
 bridge="Same as choosing Haiku, Sonnet or Opus for a job; here the catalogue also has GPT, Llama, Phi and Claude, and each needs a **deployment** first (except preview instant models).",
 steps=["Choose a model (small, large, reasoning, multimodal, code)","Deploy it (Global Standard to start)","Call it by deployment name"],
 facts=["Reasoning models reject `temperature`, `top_p`, `max_tokens`; use `max_output_tokens` and `reasoning_effort`.","Reasoning tokens are billed as output tokens.","A developer message equals a system message; don't send both."],
 traps=["`max_tokens` on a reasoning model is an error.","Bigger isn't the default answer: the stem's constraint (cost, latency, modality) decides."],
 checks=["d2-q12"], src=L+"openai/how-to/reasoning"),
dict(id="2.3", c="A", title="Implement RAG",
 one="Retrieve the right passages first, then ask the model to answer only from them.",
 bridge="Exactly the RAG pattern from CCA-F context management; Azure supplies the retriever (Azure AI Search, Foundry IQ, file search).",
 steps=["Index content in Azure AI Search","Attach the Search tool (or a knowledge base) to the agent","The agent retrieves, then answers with citations"],
 facts=["Search tool `query_type` defaults to `vector_semantic_hybrid`; `top_k` defaults to 5.","The project's managed identity needs Search Index Data Contributor and Search Service Contributor.","File search = documents the user uploads; Foundry IQ = curated organisational knowledge."],
 traps=["Pure vector search misses exact codes and IDs; hybrid catches them.","File search isn't for shared company knowledge."],
 checks=["d2-n1","d2-m2"], src=L+"agents/how-to/tools/ai-search"),
dict(id="2.4", c="A", title="Design workflows and multi-step pipelines",
 one="Chain model calls, tools and rules into a defined flow; build new ones on Microsoft Agent Framework.",
 bridge="The workflow-vs-agent choice from CCA-F: a fixed sequence (workflow) vs the model choosing steps (agent). Same decision here.",
 steps=["Fixed steps → a workflow (graph)","Model chooses steps → an agent","Use Agent Framework for both in new code"],
 facts=["Agent Framework 1.0 (Python, .NET) succeeds Semantic Kernel and AutoGen.","Prompt flow retires 20 April 2027.","Foundry Workflows (preview) retire 1 December 2026."],
 traps=["Prompt flow or Workflows for a new long-lived build = the retiring answer."],
 checks=["d2-q13"], src="https://learn.microsoft.com/en-us/agent-framework/overview/"),
dict(id="2.5", c="A", title="Evaluate models and apps",
 one="Score quality, groundedness, relevance and safety on a dataset before release, with built-in evaluators.",
 bridge="LLM-as-judge and golden sets from CCA-F; Foundry ships the judges and runs them in the cloud.",
 steps=["Upload a JSONL dataset","Pick evaluators (`builtin.<name>`)","`evals.create`, then `evals.runs.create`"],
 facts=["RAG evaluators: retrieval, groundedness (1–5), relevance; Groundedness Pro is pass/fail and needs no judge deployment.","Safety evaluators (violence, protected material, indirect attack…) need no model parameter.","Default pass threshold is 3 on the 1–5 scale."],
 traps=["Fabrication = groundedness, not relevance or coherence."],
 checks=["d2-n2"], src=L+"concepts/built-in-evaluators"),
# ---- B ----
dict(id="2.6", c="B", title="Prompt agents and hosted agents",
 one="A prompt agent is declared (model + instructions + tools) and Foundry runs it; a hosted agent is your own code in a container.",
 bridge="A prompt agent is like a Claude agent defined only by system prompt and tools; a hosted agent is like running your own Agent SDK loop, but hosted by Foundry.",
 steps=["`project.agents.create_version(agent_name, PromptAgentDefinition(...))`","Each change creates a new **agent version**","Hosted agents: container with Agent Framework, LangGraph or others"],
 facts=["Prompt agents are GA.","Agent versions are snapshotted automatically, handy for CI/CD.","A Responses call without a stored agent is an 'ephemeral agent'."],
 traps=["`create_agent` and assistants are the classic API; v2 is `create_version`."],
 checks=["d2-q9","d2-o1"], src=L+"agents/overview"),
dict(id="2.7", c="B", title="Conversations: tracking state",
 one="Agents v2 keep history in **conversations**; each model turn is a **response**.",
 bridge="In the Claude Messages API you resend the whole history yourself; here a conversation object can hold it server-side for you.",
 steps=["`oa = project.get_openai_client(agent_name=...)`","`conv = oa.conversations.create()`","`oa.responses.create(conversation=conv.id, input=...)`"],
 facts=["Threads → conversations; runs → responses; assistants → agent versions.","Agents in one project share conversation storage; other projects can't see it.","Standard setup puts conversations in your own Cosmos DB."],
 traps=["Thread and run vocabulary in an answer option signals the classic API."],
 checks=["d2-q9"], src=L+"agents/overview"),
dict(id="2.8", c="B", title="Tools and tool schemas",
 one="Tools give an agent actions; each has a name, a description and a JSON schema for its arguments.",
 bridge="Same as CCA-F tool design: name + description + input schema. Function calling runs in **your** code, like `tool_use` handled by your loop.",
 steps=["Define the function schema","Model returns a function-call item","Your app runs it and sends the output back"],
 facts=["Built-in tools: code interpreter, file search, Azure AI Search, OpenAPI, MCP, Azure Functions, Bing grounding, web search, A2A.","Computer use and memory are preview.","`tool_choice`: `auto`, `required` or `none`."],
 traps=["Bing grounding and web search send queries outside the Azure compliance boundary.","Azure Functions tool needs the Standard agent setup."],
 checks=["d2-q14","d2-m1"], src=L+"agents/overview"),
dict(id="2.9", c="B", title="MCP tools and the toolbox",
 one="Connect MCP servers as tools; a toolbox shares curated tools with many agents through one MCP endpoint.",
 bridge="The same Model Context Protocol from CCA-F, unchanged. New: approval is built into the tool definition.",
 steps=["`MCPTool(server_label, server_url, require_approval=...)`","Model returns an approval request","You approve or reject; the call runs"],
 facts=["`require_approval` defaults to `always`.","Non-streaming MCP calls time out at 100 seconds; use background mode for longer.","Private MCP servers need the Standard setup with your VNet."],
 traps=["`require_approval=\"never\"` on a write tool removes the human."],
 checks=["d2-q11","d2-q16","d2-y2"], src=L+"agents/how-to/tools/model-context-protocol"),
dict(id="2.10", c="B", title="Memory and knowledge for agents",
 one="Pick by source: memory for what the agent learns about a user, Foundry IQ for organisational knowledge, file search for uploaded files.",
 bridge="CCA-F's context-management choices (what to keep, what to retrieve), turned into three Azure services.",
 steps=["About the user, across chats → memory (preview)","Curated company content → Foundry IQ","Files brought into this chat → file search"],
 facts=["Memory types: user profile, chat summary, procedural.","Memory limits: 100 scopes per store, 10,000 memories per scope; no VNet support.","Foundry IQ connects agents to knowledge bases over MCP."],
 traps=["Memory is preview; it won't be the answer when the stem demands GA."],
 checks=["d2-m2"], src=L+"agents/concepts/what-is-memory"),
dict(id="2.11", c="B", title="Multi-agent solutions",
 one="When one agent hands work to another, use the A2A tool; for fixed multi-step flows, use Agent Framework workflows.",
 bridge="CCA-F's orchestrator–subagent pattern. Here the 'call another agent' primitive is the A2A tool.",
 steps=["Agent A gets an `a2a` tool pointing at agent B","A delegates; B answers","Both traces join in App Insights"],
 facts=["A2A tool (protocol v1.0) is GA.","Connected Agents isn't available in the new Agent Service.","Workflows are preview and retire 1 Dec 2026."],
 traps=["'Connected Agents' is the classic answer."],
 checks=["d2-q10"], src=L+"agents/how-to/tools/agent-to-agent"),
dict(id="2.12", c="B", title="Safeguards and approvals",
 one="Keep a human in the loop for risky actions: MCP approvals, gates around function calls, and guardrails on tool calls.",
 bridge="Claude Code's permission modes and hooks, in agent form: the agent proposes, a person or rule approves.",
 steps=["Classify actions: read vs write vs irreversible","Require approval on writes","Add guardrail checks at tool call and tool response"],
 facts=["Guardrail intervention points for agents: user input, output, tool call, tool response (tool points are preview).","Guardrails for agents are preview; annotate-only isn't available for agents.","An agent's own guardrail fully overrides its model's."],
 traps=["A guardrail detects risk; it doesn't replace a human approval."],
 checks=["d2-q11","d2-s1","d2-s2","d2-s3"], src=L+"guardrails/guardrails-overview"),
dict(id="2.13", c="B", title="Monitor and evaluate agents",
 one="Agent evaluators score whether it understood the user, followed instructions and used tools correctly.",
 bridge="CCA-F trajectory evaluation (was the right tool called with the right arguments?), as built-in evaluators.",
 steps=["Intent resolution: did it understand?","Task adherence: did it follow instructions?","Tool call accuracy: right tool, right arguments?"],
 facts=["Agent evaluators include task adherence, intent resolution, tool call accuracy, tool selection, tool input accuracy, task completion.","Evaluation level: `turn` (default) or `conversation`.","Continuous evaluation samples live traffic; alerts go through Azure Monitor."],
 traps=["Coherence and fluency don't tell you whether tools were used correctly."],
 checks=["d2-y1"], src=L+"concepts/built-in-evaluators"),
# ---- C ----
dict(id="2.14", c="C", title="Tune generation: prompts and parameters",
 one="Improve answers with prompt changes first; then adjust parameters; reasoning models use effort instead of temperature.",
 bridge="Prompt engineering from CCA-F applies as-is; extended thinking's budget maps to `reasoning_effort`.",
 steps=["Clear instructions and examples","Classic models: temperature / top_p","Reasoning models: `reasoning_effort`, `max_output_tokens`"],
 facts=["`reasoning_effort` ranges from `none` to `max`, depending on the model.","`max_output_tokens` includes reasoning tokens.","Parallel tool calls aren't supported at `minimal` effort."],
 traps=["Raising effort before measuring is the costly answer."],
 checks=["d2-q12","d2-q17"], src=L+"openai/how-to/reasoning"),
dict(id="2.15", c="C", title="Reflection and self-critique",
 one="Add a critic step: an evaluator or a second pass checks the answer before it's used.",
 bridge="CCA-F's evaluator–optimizer pattern.",
 steps=["Generate","Critique with an evaluator (e.g. groundedness, task adherence)","Revise or hand off if it fails"],
 facts=["Docs favour evaluating before raising effort.","A judge needs its own model deployment, except Groundedness Pro and safety evaluators."],
 traps=["Calling the model twice on every request doubles cost before you know what's wrong."],
 checks=["d2-q17"], src=L+"concepts/built-in-evaluators"),
dict(id="2.16", c="C", title="Observability and orchestration",
 one="Connect Application Insights for tracing with no code change; orchestrate several models with model router or rules-first logic.",
 bridge="CCA-F's tracing and cost-awareness; here OpenTelemetry GenAI traces land in App Insights automatically.",
 steps=["Connect App Insights to the project","Server-side traces appear (90 days in the portal)","Add client-side spans for extra detail"],
 facts=["Tracing is GA for prompt and hosted agents; preview for workflow and external agents.","Querying traces needs Log Analytics Reader.","Model router: Balanced/Quality/Cost modes; smallest model's context window."],
 traps=["'Add OpenTelemetry spans in code' is wrong when the stem says no code changes."],
 checks=["d2-q15"], src=L+"observability/how-to/trace-agent-setup"),
]
