"""Domain 1 teaching cards: identity and access in Foundry. Checked against Microsoft Learn (RBAC for Foundry, updated 22 Sep 2026)."""
L = "https://learn.microsoft.com/en-us/azure/foundry/"
CLUSTERS = [("R", "Identity and access in Foundry")]
CARDS = [
dict(id="1.R1", c="R", title="The five Foundry roles, and the two Azure roles that can't build",
 one="Use agents → Agent Consumer. Build → Foundry User. Lead a team and publish → Project Manager. Set up resources, no building → Account Owner. Everything → Foundry Owner.",
 bridge="**New for you.** CCA-F had API keys and workspaces, not role scopes. Think of it as Claude Console roles, but enforced by Azure RBAC at resource, project and agent level.",
 steps=["Decide what the principal must **do**: call, build, publish, set up","Pick the smallest role that does it","Pick the smallest **scope**: agent, project, or resource"],
 facts=["**Foundry Agent Consumer:** call agent endpoints only. Assignable down to **one agent**.",
        "**Foundry User** (was Azure AI User): build, test, evaluate in a project; read access. Least privilege for developers and for the **project's managed identity**.",
        "**Foundry Project Manager:** build + manage projects + assign *only* Foundry User + **publish agents** (the minimum role to publish).",
        "**Foundry Account Owner:** create resources and projects, manage models, assign Foundry User / ACR / monitoring roles. **No data actions: can't build.**",
        "**Foundry Owner:** all of the above, building included.",
        "Azure **Owner** and **Contributor** manage resources (Contributor can deploy models) but have **no data actions**."],
 traps=["Owner or Contributor on the subscription still can't create an agent: add Foundry User.","**Azure AI Developer** is for hubs and Azure Machine Learning, not Foundry projects.","Don't use *Cognitive Services …* roles for Foundry, except **Cognitive Services Usages Reader** for quota.","Renamed roles keep their role IDs; scripts should use the ID."],
 checks=["d1-r1","d1-r2","d1-r3"], src=L+"concepts/rbac-foundry"),
dict(id="1.R2", c="R", title="Scopes and the two hops of identity",
 one="The caller needs a role on Foundry; the project's managed identity needs roles on everything Foundry reaches for it.",
 bridge="Like an MCP server that calls another API with its own credentials: the user is allowed into the server, and the server separately needs rights downstream.",
 steps=["Hop 1: user or app → Foundry (Foundry roles, at resource, project or agent scope)","Hop 2: project managed identity → Search, Storage and other connected resources (their data roles)","Check both when you see a 403"],
 facts=["Scopes: subscription → resource group → **Foundry resource → project → agent**.",
        "Agent scope is evaluated **only for calling that agent's endpoint**.",
        "The Azure portal assigns Agent Consumer **only at account scope**; use the **Azure CLI** for project or agent scope.",
        "Project managed identity examples: **Storage Blob Data Reader** on a storage account; Search roles (Search Index Data Contributor, Search Service Contributor) on AI Search for the Search tool.",
        "Quota and deployment eligibility: **Cognitive Services Usages Reader at subscription scope**; resource or project scope doesn't work."],
 traps=["Giving the *developer* a Search role doesn't fix the agent's Search tool: the call is made by the project's identity.","A project-scope Agent Consumer can call **every** agent in the project."],
 checks=["d1-r4","d1-r5","d1-r6"], src=L+"concepts/rbac-foundry"),
dict(id="1.R3", c="R", title="Keys, tokens, and how Foundry differs from other AI services",
 one="Entra ID + Azure RBAC, like the rest of Azure; but keys skip RBAC entirely, and roles differ by resource type.",
 bridge="Same split as Storage or Key Vault: owning the account isn't the same as reading the data. Control plane and data plane are separate permissions.",
 steps=["Prefer Entra ID; disable keys where possible","Use the token audience `https://ai.azure.com/.default` for the v1 API and projects","Match the role family to the resource type"],
 facts=["An **API key grants full access with no role checks**. Agents and evaluations need Entra ID anyway.",
        "Creating a resource or project **in the portal** auto-assigns Foundry User to you and the project identity, if you can assign roles; **SDK or CLI deployments don't**.",
        "**Fine-tuning** needs both planes: **Foundry Owner**, or Foundry User + Foundry Account Owner.",
        "Role families: Foundry resource and projects → **Foundry roles**; standalone Azure OpenAI or AI services resource → **Cognitive Services** roles (e.g. Cognitive Services OpenAI User); hub projects → **Azure AI Developer** and Azure ML roles."],
 traps=["Expecting RBAC to limit a key holder: it doesn't.","Using Cognitive Services OpenAI User for a Foundry project instead of Foundry User."],
 checks=["d1-r7"], src=L+"concepts/authentication-authorization-foundry"),
]

CLUSTERS.append(("E", "Evaluators: which one? (with ELI5)"))
LE = L + "concepts/built-in-evaluators"
CARDS += [
dict(id="1.E1", c="E", title="Evaluator, guardrail, red team, tracing: who does what",
 one="Evaluators mark the homework; guardrails stop bad answers at the door; the red-teaming agent tests the locks; tracing is the CCTV.",
 bridge="Same split as CCA-F's evals vs runtime checks: an eval suite tells you how good the agent is; a hook or validator stops one bad action now.",
 steps=["Must something be **stopped** before a user sees it? → guardrail","Must something be **measured**? → evaluator (offline on a dataset, or continuous on live traffic)","Must you **attack** it before release? → AI Red Teaming Agent"],
 facts=["Evaluators never block anything, even when they run on live traffic.",
        "**Where you set them:** the portal's Evaluation page (pick a dataset or an agent, then evaluators); the agents playground (on by default, and billed); continuous evaluation on a deployed agent (with a sampling rate); or code: `azure-ai-evaluation`, cloud runs with `builtin.*` evaluators, in CI.",
        "**Three kinds:** maths (F1, BLEU, ROUGE, METEOR, GLEU, String Checker: deterministic, no model); AI-assisted (quality, RAG, agent: an LLM judge on **your** deployment, so you pay its tokens); Microsoft-hosted (safety evaluators, Groundedness Pro: billed as a Foundry service).",
        "**Why not always on:** every evaluator is extra calls per answer and can cost more than the app; many need inputs you may not have (ground truth, context, tool definitions); uncalibrated judges create noise; and they never block. Pick per app, sample live traffic, and keep cheap deterministic rules everywhere.","Evaluators score a single **turn** by default; scoring a whole **conversation** needs data in the messages format.","Combos from Learn: RAG → Retrieval + Groundedness + Relevance + safety; agents → Output Quality + Tool Use Quality + Rubric + safety; translation → BLEU + METEOR + Fluency + Coherence."],
 traps=["\"Continuous evaluation\" sounds live, but it scores answers users have already seen.","The Indirect Attack *evaluator* measures; *Prompt Shields* blocks."],
 table=dict(head=["Feature","What it does","ELI5"], rows=[
  ["**Evaluator** (offline)","Scores answers on a test dataset before release","A teacher marking homework before the report card goes out"],
  ["**Continuous evaluation**","Scores a sample of live answers","A teacher spot-checking homework that was already handed back"],
  ["**Guardrail**","Checks every input, output and tool call at runtime; can block","A security guard at the door who stops a bad answer leaving"],
  ["**AI Red Teaming Agent**","Generates attacks before release; reports attack success rate","A friendly burglar paid to test your locks"],
  ["**Tracing**","Records each step of every run","CCTV: it doesn't stop anything, but you can replay it"]]),
 checks=["d1-e4"], src=LE),
dict(id="1.E2", c="E", title="Quality and RAG evaluators",
 one="Did it read well, match the answer key, use the right books, stick to them, and answer the question?",
 bridge="The RAG checks from CCA-F's context work, with Azure names: retrieval quality, groundedness, relevance.",
 steps=["Have a reference answer (ground truth)? → similarity and word-overlap metrics are open to you","Have the retrieved passages? → Retrieval, Groundedness, Groundedness Pro","Have neither? → Relevance, Coherence, Fluency"],
 facts=["**Need ground truth:** Similarity, F1, BLEU, GLEU, ROUGE, METEOR, Document Retrieval, Response Completeness.",
        "**F1, BLEU, GLEU, ROUGE, METEOR** are maths, not a model: same input, same score.",
        "**Groundedness** = 1–5 from your own judge deployment; **Groundedness Pro** (preview) = pass/fail from Content Safety, **no deployment**."],
 traps=["Picking BLEU when there are no reference answers.","Picking Groundedness when the question says \"no model deployment\": that's Groundedness Pro."],
 table=dict(head=["Evaluator","Measures","ELI5","Needs"], rows=[
  ["Coherence","Logical flow","Does the story make sense from start to end?","Judge model"],
  ["Fluency","Language quality","Does it sound like a fluent speaker wrote it?","Judge model"],
  ["Similarity","Meaning vs the reference","Does it mean the same as the answer key?","Ground truth + judge"],
  ["F1 · BLEU · GLEU · ROUGE · METEOR","Word overlap with the reference","Count the words it shares with the answer key; BLEU and METEOR are the translation ones","Ground truth, no model"],
  ["Retrieval","Usefulness of retrieved passages","Did the librarian bring useful books?","Retrieved context"],
  ["Document Retrieval","Retrieval accuracy against a known list","Did the librarian bring the books on the teacher's list?","Ground truth"],
  ["**Groundedness**","Answer supported by the context, 1–5","Is every sentence backed by the books on the desk? A teacher you hire gives a mark","Context + judge"],
  ["**Groundedness Pro** (preview)","Same, pass/fail","Same question, but the exam board stamps pass or fail; no teacher to hire","Context, no deployment"],
  ["Relevance","Answers the question asked","Did it answer what you actually asked?","Judge model"],
  ["Response Completeness (preview)","Nothing important missing","Did it leave out anything from the answer key?","Ground truth"]]),
 checks=["d1-e1","d1-e2","d1-e4"], src=LE),
dict(id="1.E3", c="E", title="Safety and agent evaluators",
 one="Safety: is anything harmful, copied, leaked or made up about the user? Agent: did it understand, follow the rules, use its tools well, and finish?",
 bridge="CCA-F's agent evaluation (task success, tool-use correctness) split into separately named checks; read the question for which part failed.",
 steps=["Find **which part** failed: understanding, rules, tool choice, tool arguments, using tool results, or finishing","Pick the evaluator named for that part","Use a bundle (Output Quality, Tool Use Quality) to run several in one judge call"],
 facts=["Risk and safety evaluators run on Microsoft's side; you don't deploy a judge.","Several agent evaluators are **preview**: Task Adherence, Task Completion, Intent Resolution, Customer Satisfaction.",
        "**Ungrounded Attributes** is about made-up facts **about the user**, not about the documents."],
 traps=["Task Adherence (followed the rules) ≠ Task Completion (finished the job).","Tool Selection (right tool) ≠ Tool Input Accuracy (right arguments) ≠ Tool Output Utilization (used the result)."],
 table=dict(head=["Evaluator","ELI5"], rows=[
  ["Hate and Unfairness · Sexual · Violence · Self-Harm","Is there anything harmful in it?"],
  ["Protected Materials","Did it copy song lyrics or a page from a book?"],
  ["Indirect Attack (XPIA)","Did a note hidden in a document trick it? (measures only)"],
  ["Code Vulnerability","Did the code it wrote leave a door unlocked?"],
  ["**Ungrounded Attributes**","Did it guess things about the person with no evidence (\"you must be struggling financially\")?"],
  ["Prohibited Actions","Did it do something it was told never to do?"],
  ["Sensitive Data Leakage","Did it spill a secret?"],
  ["**Intent Resolution** (preview)","Did it understand what you actually wanted?"],
  ["**Task Adherence** (preview)","Did it follow the rules of the job?"],
  ["**Task Completion** (preview)","Did it finish the job?"],
  ["Customer Satisfaction (preview)","Would the customer leave happy?"],
  ["Task Navigation Efficiency","Did it take the shortest sensible route?"],
  ["Tool Call Accuracy","Did it use its tools well, overall?"],
  ["Tool Selection","Did it pick the right tool from the toolbox?"],
  ["Tool Input Accuracy","Did it give the tool the right details?"],
  ["Tool Output Utilization","Did it actually use what the tool gave back?"],
  ["Tool Call Success","Did the tool calls work without errors?"],
  ["Quality Grader · Output Quality · Tool Use Quality (preview)","One inspector checking five things in one visit: cheaper than five visits"],
  ["Rubric (preview)","Your own marking scheme, with weights"],
  ["Graders: String Checker · Model Labeler · Model Scorer · Text Similarity","An exact-match rule · sorting into labelled boxes · marking against your guideline · how close two texts are"]]),
 checks=["d1-e3","d1-e5","d1-e6"], src=LE),
]
