"""Domain 1 teaching cards: identity and access in Foundry. Checked against Microsoft Learn (RBAC for Foundry, updated 22 Sep 2026)."""
L = "https://learn.microsoft.com/en-us/azure/foundry/"
CLUSTERS = [("R", "Identity and access in Foundry")]
CARDS = [
dict(id="1.R1", c="R", title="The five Foundry roles, and the two Azure roles that can't build",
 one="Use agents → Agent Consumer. Build → Foundry User. Lead a team and publish → Project Manager. Set up resources, no building → Account Owner. Everything → Foundry Owner.",
 bridge="**New for you.** CCA-F had API keys and workspaces, not role scopes. Think of it as Claude Console roles, but enforced by Azure RBAC at resource, project and agent level.",
 steps=["Decide what the principal must **do**: call, build, publish, set up","Pick the smallest role that does it","Pick the smallest **scope**: agent, project, or resource"],
 facts=["**Foundry Agent Consumer:** call agent endpoints only. Assignable down to **one agent**.",
        "**Foundry User** (was Azure AI User): build, test, evaluate in a project; read access. Least privilege for developers and for the **project's managed identity**.",
        "**Foundry Project Manager:** build + manage projects + assign *only* Foundry User + **publish agents** (the minimum role to publish).",
        "**Foundry Account Owner:** create resources and projects, manage models, assign Foundry User / ACR / monitoring roles. **No data actions: can't build.**",
        "**Foundry Owner:** all of the above, building included.",
        "Azure **Owner** and **Contributor** manage resources (Contributor can deploy models) but have **no data actions**."],
 traps=["Owner or Contributor on the subscription still can't create an agent: add Foundry User.","**Azure AI Developer** is for hubs and Azure Machine Learning, not Foundry projects.","Don't use *Cognitive Services …* roles for Foundry, except **Cognitive Services Usages Reader** for quota.","Renamed roles keep their role IDs; scripts should use the ID."],
 checks=["d1-r1","d1-r2","d1-r3"], src=L+"concepts/rbac-foundry"),
dict(id="1.R2", c="R", title="Scopes and the two hops of identity",
 one="The caller needs a role on Foundry; the project's managed identity needs roles on everything Foundry reaches for it.",
 bridge="Like an MCP server that calls another API with its own credentials: the user is allowed into the server, and the server separately needs rights downstream.",
 steps=["Hop 1: user or app → Foundry (Foundry roles, at resource, project or agent scope)","Hop 2: project managed identity → Search, Storage and other connected resources (their data roles)","Check both when you see a 403"],
 facts=["Scopes: subscription → resource group → **Foundry resource → project → agent**.",
        "Agent scope is evaluated **only for calling that agent's endpoint**.",
        "The Azure portal assigns Agent Consumer **only at account scope**; use the **Azure CLI** for project or agent scope.",
        "Project managed identity examples: **Storage Blob Data Reader** on a storage account; Search roles (Search Index Data Contributor, Search Service Contributor) on AI Search for the Search tool.",
        "Quota and deployment eligibility: **Cognitive Services Usages Reader at subscription scope**; resource or project scope doesn't work."],
 traps=["Giving the *developer* a Search role doesn't fix the agent's Search tool: the call is made by the project's identity.","A project-scope Agent Consumer can call **every** agent in the project."],
 checks=["d1-r4","d1-r5","d1-r6"], src=L+"concepts/rbac-foundry"),
dict(id="1.R3", c="R", title="Keys, tokens, and how Foundry differs from other AI services",
 one="Entra ID + Azure RBAC, like the rest of Azure; but keys skip RBAC entirely, and roles differ by resource type.",
 bridge="Same split as Storage or Key Vault: owning the account isn't the same as reading the data. Control plane and data plane are separate permissions.",
 steps=["Prefer Entra ID; disable keys where possible","Use the token audience `https://ai.azure.com/.default` for the v1 API and projects","Match the role family to the resource type"],
 facts=["An **API key grants full access with no role checks**. Agents and evaluations need Entra ID anyway.",
        "Creating a resource or project **in the portal** auto-assigns Foundry User to you and the project identity, if you can assign roles; **SDK or CLI deployments don't**.",
        "**Fine-tuning** needs both planes: **Foundry Owner**, or Foundry User + Foundry Account Owner.",
        "Role families: Foundry resource and projects → **Foundry roles**; standalone Azure OpenAI or AI services resource → **Cognitive Services** roles (e.g. Cognitive Services OpenAI User); hub projects → **Azure AI Developer** and Azure ML roles."],
 traps=["Expecting RBAC to limit a key holder: it doesn't.","Using Cognitive Services OpenAI User for a Foundry project instead of Foundry User."],
 checks=["d1-r7"], src=L+"concepts/authentication-authorization-foundry"),
]

CLUSTERS.append(("E", "Evaluators: which one? (with ELI5)"))
LE = L + "concepts/built-in-evaluators"
CARDS += [
dict(id="1.E0", c="E", title="What to learn for the exam: three tiers",
 one="Know the families and the look-alike pairs cold; recognise the rest by name; look up the rare ones on Microsoft Learn.",
 bridge="Same exam tactic as CCA-F: learn the decision rules, not the catalogue. Here Learn is open, but a lookup costs a whole question's time (about 2 minutes).",
 steps=["Tier 1: learn until you can answer without looking","Tier 2: recognise the name and what it checks","Tier 3: skip; look up only if one appears"],
 facts=["Most evaluator questions reduce to two calls: **measure or block?** and **which family** (RAG, agent, safety, ground-truth maths)?"],
 traps=["Memorising every evaluator: time better spent on the look-alike pairs."],
 table=dict(head=["Tier","What","Why"], rows=[
  ["**1 · Know cold**","Evaluator vs guardrail vs red team vs continuous evaluation","Measure vs block vs attack: the most-tested idea"],
  ["**1 · Know cold**","Groundedness vs Groundedness Pro","1–5 with your judge vs pass/fail with no deployment"],
  ["**1 · Know cold**","Relevance · Retrieval · Groundedness","The RAG trio: answered the question? fetched useful text? stuck to it?"],
  ["**1 · Know cold**","Intent Resolution · Task Adherence · Task Completion · Tool Call Accuracy","Understood? followed the rules? finished? used tools well?"],
  ["**1 · Know cold**","Indirect Attack evaluator vs Prompt Shields","Measures vs blocks"],
  ["**1 · Know cold**","Hate and Unfairness · Sexual · Violence · Self-Harm","One harm family"],
  ["**1 · Know cold**","The needs rule","Ground truth → Similarity, F1/BLEU/ROUGE/METEOR · context → Groundedness, Retrieval · no deployment → maths or Microsoft-hosted"],
  ["**1 · Know cold**","AI Red Teaming Agent → attack success rate","The pre-release safety answer"],
  ["2 · Recognise","Ungrounded Attributes · Protected Materials · Code Vulnerability","Unsupported guesses about the user (emotions, protected traits) · copied text · insecure code"],
  ["2 · Recognise","BLEU / METEOR · Document Retrieval · Response Completeness","Translation vs references · retrieval vs a known list · nothing important missing"],
  ["2 · Recognise","Tool Selection · Tool Input Accuracy · Tool Output Utilization","Right tool · right details · used the result"],
  ["2 · Recognise","Evaluation levels","Conversation level needs the messages format"],
  ["3 · Skip, look up","GLEU, ROUGE vs F1; Customer Satisfaction; Task Navigation Efficiency; Tool Call Success; Prohibited Actions; Sensitive Data Leakage; bundles (Quality Grader is deprecated); Rubric; Azure OpenAI graders; custom","Unlikely as answers; the name is a strong hint"]]),
 checks=["d1-e4"], src=LE),
dict(id="1.E1", c="E", title="Evaluator, guardrail, red team, tracing: who does what",
 one="Evaluators mark the homework; guardrails stop bad answers at the door; the red-teaming agent tests the locks; tracing is the CCTV.",
 bridge="Same split as CCA-F's evals vs runtime checks: an eval suite tells you how good the agent is; a hook or validator stops one bad action now.",
 steps=["Must something be **stopped** before a user sees it? → guardrail","Must something be **measured**? → evaluator (offline on a dataset, or continuous on live traffic)","Must you **attack** it before release? → AI Red Teaming Agent"],
 facts=["Evaluators never block anything, even when they run on live traffic.",
        "**Where you set them:** the portal's Evaluation page (pick a dataset or an agent, then evaluators); the agents playground (on by default, and billed); continuous evaluation on a deployed agent (with a sampling rate); or code: `azure-ai-evaluation`, cloud runs with `builtin.*` evaluators, in CI.",
        "**Three kinds:** maths (F1, BLEU, ROUGE, METEOR, GLEU, String Checker: deterministic, no model); AI-assisted (quality, RAG, agent: an LLM judge on **your** deployment, so you pay its tokens); Microsoft-hosted (safety evaluators, Groundedness Pro: billed as a Foundry service).",
        "**Why not always on:** every evaluator is extra calls per answer and can cost more than the app; many need inputs you may not have (ground truth, context, tool definitions); uncalibrated judges create noise; and they never block. Pick per app, sample live traffic, and keep cheap deterministic rules everywhere.","Evaluators score a single **turn** by default; scoring a whole **conversation** needs data in the messages format.","Combos from Learn: RAG → Retrieval + Groundedness + Relevance + safety; agents → Output Quality + Tool Use Quality + Rubric + safety; translation → BLEU + METEOR + Fluency + Coherence."],
 traps=["\"Continuous evaluation\" sounds live, but it scores answers users have already seen.","The Indirect Attack *evaluator* measures; *Prompt Shields* blocks."],
 table=dict(head=["Feature","What it does","ELI5"], rows=[
  ["**Evaluator** (offline)","Scores answers on a test dataset before release","A teacher marking homework before the report card goes out"],
  ["**Continuous evaluation**","Scores a sample of live answers","A teacher spot-checking homework that was already handed back"],
  ["**Guardrail**","Checks every input, output and tool call at runtime; can block","A security guard at the door who stops a bad answer leaving"],
  ["**AI Red Teaming Agent**","Generates attacks before release; reports attack success rate","A friendly burglar paid to test your locks"],
  ["**Tracing**","Records each step of every run","CCTV: it doesn't stop anything, but you can replay it"]]),
 checks=["d1-e4"], src=LE),
dict(id="1.E2", c="E", title="Quality and RAG evaluators",
 one="Did it read well, match the answer key, use the right books, stick to them, and answer the question?",
 bridge="The RAG checks from CCA-F's context work, with Azure names: retrieval quality, groundedness, relevance.",
 steps=["Have a reference answer (ground truth)? → similarity and word-overlap metrics are open to you","Have the retrieved passages? → Retrieval, Groundedness, Groundedness Pro","Have neither? → Relevance, Coherence, Fluency"],
 facts=["**Need ground truth:** Similarity, F1, BLEU, GLEU, ROUGE, METEOR, Document Retrieval, Response Completeness.",
        "**F1, BLEU, GLEU, ROUGE, METEOR** are maths, not a model: same input, same score.",
        "**Groundedness** = 1–5 from your own judge deployment; **Groundedness Pro** (preview) = pass/fail from Content Safety, **no deployment**."],
 traps=["Picking BLEU when there are no reference answers.","Picking Groundedness when the question says \"no model deployment\": that's Groundedness Pro."],
 table=dict(head=["Evaluator","Measures","ELI5","Needs"], rows=[
  ["Coherence","Logical flow","Does the story make sense from start to end?","Judge model"],
  ["Fluency","Language quality","Does it sound like a fluent speaker wrote it?","Judge model"],
  ["Similarity","Meaning vs the reference","Does it mean the same as the answer key?","Ground truth + judge"],
  ["F1 · BLEU · GLEU · ROUGE · METEOR","Word overlap with the reference","Count the words it shares with the answer key; BLEU and METEOR are the translation ones","Ground truth, no model"],
  ["Retrieval","Usefulness of retrieved passages","Did the librarian bring useful books?","Retrieved context"],
  ["Document Retrieval","Retrieval accuracy against a known list","Did the librarian bring the books on the teacher's list?","Ground truth"],
  ["**Groundedness**","Answer supported by the context, 1–5","Is every sentence backed by the books on the desk? A teacher you hire gives a mark","Context + judge"],
  ["**Groundedness Pro** (preview)","Same, pass/fail","Same question, but the exam board stamps pass or fail; no teacher to hire","Context, no deployment"],
  ["Relevance","Answers the question asked","Did it answer what you actually asked?","Judge model"],
  ["Response Completeness (preview)","Nothing important missing","Did it leave out anything from the answer key?","Ground truth"]]),
 checks=["d1-e1","d1-e2","d1-e4"], src=LE),
dict(id="1.E3", c="E", title="Safety and agent evaluators",
 one="Safety: is anything harmful, copied, leaked or made up about the user? Agent: did it understand, follow the rules, use its tools well, and finish?",
 bridge="CCA-F's agent evaluation (task success, tool-use correctness) split into separately named checks; read the question for which part failed.",
 steps=["Find **which part** failed: understanding, rules, tool choice, tool arguments, using tool results, or finishing","Pick the evaluator named for that part","Use a bundle (Output Quality, Tool Use Quality) to run several in one judge call"],
 facts=["Risk and safety evaluators run on Microsoft's side; you don't deploy a judge.","Several agent evaluators are **preview**: Task Adherence, Task Completion, Intent Resolution, Customer Satisfaction.",
        "**Ungrounded Attributes** is about unsupported guesses **about the user**: their emotional state, protected traits (gender, ethnicity, religion, health) or circumstances. Not about the documents."],
 traps=["Task Adherence (followed the rules) ≠ Task Completion (finished the job).","Tool Selection (right tool) ≠ Tool Input Accuracy (right arguments) ≠ Tool Output Utilization (used the result).","Limited support: avoid Tool Call Accuracy, Tool Input Accuracy, Tool Output Utilization, Tool Call Success and Groundedness when the agent uses Azure AI Search, Bing, SharePoint, Code Interpreter, Fabric Data Agent or Web Search tools. Function, MCP and File Search tools are supported.","**Quality Grader is deprecated** and can no longer run: use Output Quality and Tool Use Quality."],
 table=dict(head=["Evaluator","ELI5"], rows=[
  ["Hate and Unfairness · Sexual · Violence · Self-Harm","Is there anything harmful in it?"],
  ["Protected Materials","Did it copy song lyrics or a page from a book?"],
  ["Indirect Attack (XPIA)","Did a note hidden in a document trick it? (measures only)"],
  ["Code Vulnerability","Did the code it wrote leave a door unlocked?"],
  ["**Ungrounded Attributes**","Did it guess things about the person with no evidence: how they feel, their gender, ethnicity or health, or their money (\"you must be struggling financially\")?"],
  ["Prohibited Actions","Did it do something it was told never to do?"],
  ["Sensitive Data Leakage","Did it spill a secret?"],
  ["**Intent Resolution** (preview)","Did it understand what you actually wanted?"],
  ["**Task Adherence** (preview)","Did it follow the rules of the job?"],
  ["**Task Completion** (preview)","Did it finish the job?"],
  ["Customer Satisfaction (preview)","Would the customer leave happy?"],
  ["Task Navigation Efficiency","Did it take the shortest sensible route?"],
  ["Tool Call Accuracy","Did it use its tools well, overall?"],
  ["Tool Selection","Did it pick the right tool from the toolbox?"],
  ["Tool Input Accuracy","Did it give the tool the right details?"],
  ["Tool Output Utilization","Did it actually use what the tool gave back?"],
  ["Tool Call Success","Did the tool calls work without errors?"],
  ["Output Quality · Tool Use Quality (preview)","One inspector checking several things in one visit: cheaper than separate visits. Quality Grader is deprecated"],
  ["Rubric (preview)","Your own marking scheme, with weights"],
  ["Graders: String Checker · Model Labeler · Model Scorer · Text Similarity","An exact-match rule · sorting into labelled boxes · marking against your guideline · how close two texts are"]]),
 checks=["d1-e3","d1-e5","d1-e6"], src=LE),
dict(id="1.E4", c="E", title="When to use which evaluator, and what it costs",
 one="Start from the job: RAG, agent, reference-based text, or safety. Then check what you have (ground truth, context) and what you can pay for (a judge model).",
 bridge="CCA-F's \"cheapest check that answers the question\": deterministic checks first, LLM judges where meaning matters, and never more judges than you'll act on.",
 steps=["Name the job you're evaluating","Check the inputs you have: reference answers? retrieved passages? tool definitions?","Pick the cheapest evaluator that answers the question; add LLM judges only where meaning matters"],
 facts=["**Free, deterministic:** F1, BLEU, GLEU, ROUGE, METEOR, Document Retrieval, String Checker, and **Task Navigation Efficiency** (compares actions with expected actions; no judge).",
        "**Your judge's tokens:** Coherence, Fluency, Similarity, Relevance, Retrieval, Groundedness, Response Completeness, every agent and tool evaluator except Task Navigation Efficiency, Rubric, Model Labeler, Model Scorer. About one judge call per evaluator per answer; bundles (Output Quality, Tool Use Quality) do several in one call.",
        "**Billed by Foundry, no deployment of yours:** the risk and safety evaluators and Groundedness Pro. Check the pricing page for rates."],
 traps=["Running every AI-assisted evaluator on every answer: the judge can cost more than the app.","Choosing an LLM judge where a deterministic check would do, such as \"must mention clause WR-3\" → String Checker."],
 table=dict(head=["If you're evaluating…","Use","Needs","Cost"], rows=[
  ["A RAG answer","Retrieval + Groundedness (or Groundedness Pro) + Relevance","Query, retrieved passages, response","Judge tokens (Groundedness Pro: Foundry-billed)"],
  ["An agent","Intent Resolution + Task Adherence + Task Completion + Tool Call Accuracy, or the Output Quality and Tool Use Quality bundles","Conversation, tool definitions and calls","Judge tokens; bundles fewer calls"],
  ["An agent's path against the expected one","Task Navigation Efficiency","Actions and expected actions","Free"],
  ["A translation or summary with reference answers","BLEU / METEOR (translation), ROUGE (summaries), F1, Similarity","Ground truth","Free, except Similarity (judge)"],
  ["Retrieval against a known answer list","Document Retrieval","Labelled relevant documents","Free"],
  ["Harmful or risky output","Hate and Unfairness, Sexual, Violence, Self-Harm, Protected Materials, Indirect Attack, Code Vulnerability, Ungrounded Attributes","Query and response","Foundry-billed"],
  ["Writing quality","Coherence, Fluency","Response","Judge tokens"],
  ["A hard business rule","String Checker, or your own custom evaluator","The rule","Free"],
  ["Attack resistance before release","AI Red Teaming Agent (not an evaluator)","The agent or model","Foundry-billed"]]),
 checks=["d1-e1","d1-e2","d1-e5"], src=LE),
dict(id="1.E5", c="E", title="Agent evaluators: what each needs and returns",
 one="Each agent evaluator answers one question, needs specific fields, and returns pass/fail (some from a 1–5 score). Only Task Navigation Efficiency needs no judge.",
 bridge="CCA-F's split between judging the outcome and judging the steps: Microsoft calls them system evaluation (did the job get done well?) and process evaluation (was each tool step right?).",
 steps=["Map the fields your data has: query and response, or messages; plus tool_definitions for tool evaluators","Pick turn level (one reply) or conversation level (the whole chat) where both are supported","Read pass/fail for the gate; read the score and reason to find the cause"],
 facts=["**System evaluation** (the outcome): Task Completion, Customer Satisfaction, Task Adherence, Task Navigation Efficiency, Intent Resolution.",
        "**Process evaluation** (the steps): Tool Call Accuracy, Tool Selection, Tool Input Accuracy, Tool Output Utilization, Tool Call Success.",
        "**Conversation level** is supported by Task Completion, Customer Satisfaction and the two bundles; the rest are turn level only.",
        "A bundle **passes only if every applicable component passes**; skipped components don't fail it. Learn recommends a GPT-5.6-family judge for bundles."],
 traps=["Task Navigation Efficiency needs **expected actions** (ground truth): no expected path, no evaluator.","Tool Call Success still uses a judge model, even though it only reads the response."],
 table=dict(head=["Evaluator","Question","Needs","Returns"], rows=[
  ["Intent Resolution (preview)","Did it understand what the user wanted?","query + response, or messages","1–5, then pass/fail at a threshold"],
  ["Task Adherence (preview)","Did it follow its system instructions?","query + response, or messages (+ tool_definitions)","Pass/fail"],
  ["Task Completion (preview)","Did it finish the job with a usable result?","query + response, or messages","Pass/fail"],
  ["Customer Satisfaction (preview)","Would the user be happy?","query + response, or messages","1–5"],
  ["Tool Selection","Did it pick the right tools, and no unnecessary ones?","query + tool_definitions","Pass/fail"],
  ["Tool Input Accuracy","Did it pass the right arguments?","query + response + tool_definitions","Pass/fail"],
  ["Tool Output Utilization","Did it use what the tool returned?","query + response + tool_definitions","Pass/fail"],
  ["Tool Call Success","Did the tool calls run without errors?","response, or messages","Pass/fail"],
  ["Tool Call Accuracy","Right calls, right parameters, no redundancy, overall","query + tool_definitions","1–5, then pass/fail"],
  ["Task Navigation Efficiency","Did it take the expected path?","actions (or messages) + expected_actions","Maths, no judge: pass/fail plus precision, recall and F1. Match modes: exact, in order, any order"],
  ["Output Quality · Tool Use Quality (preview)","Several of the above in one judge call","query + response (+ tool_definitions), or messages","Passes only if every applicable component passes"]]),
 checks=["d1-e5","d1-e6"], src=L+"concepts/evaluation-evaluators/agent-evaluators"),
]
