"""Mock Exam #1, part A: D1 and D2 items outside the case studies. All items original."""
from bank_d1 import T
L = "https://learn.microsoft.com/en-us/azure/foundry/"
D1, D2 = "D1 · Plan and manage", "D2 · GenAI and agents"

def single(id, skill, stem, options, runner, runnerWhy, think, eli5, learn):
    return dict(id=id, type="single", skill=skill, stem=stem, options=options, answer=0, runner=runner, runnerWhy=runnerWhy, think=think, eli5=eli5, learn=learn)

A = [
single("m1-01", D1, "You have a Microsoft Foundry project that serves a broker chat app through model router. Finance asks you to cut spend, and slightly lower quality on simple questions is acceptable. What should you change?",
 ["Set the routing mode to Cost","Limit the model subset to small models","Set the routing mode to Quality","Move the router to a Provisioned deployment"], 1,
 "it also cuts cost, but it blocks larger models even for hard questions; Cost mode keeps them available.",
 T("That limiting models is the only way to save money. The router's mode already trades quality for cost per prompt.",
   [["Spend too high, mixed questions","Routing mode","Cost mode"],["Some models must never be used","Eligibility","Model subset"],["Quality matters most","Routing mode","Quality mode"]],
   [["\"slightly lower quality on simple questions is acceptable\"","Exactly the Cost-mode trade-off."],["\"cut spend\"","Rules out Quality mode and reserved capacity."]],
   "Model router modes: Balanced (default), Quality, Cost. A model subset limits which models are eligible at all.",
   "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools."),
 "Tell the dispatcher to send small jobs to the cheaper courier.", L+"openai/concepts/model-router"),
single("m1-02", D1, "Your data science team uses a hub-based project. A new team will build agents in the new Foundry portal and wants the current agent features. What should the new team create?",
 ["A Foundry project in a Foundry resource","A new project inside the existing hub","A standalone Azure OpenAI resource","An Azure Machine Learning workspace"], 1,
 "it keeps them next to the data science team, but hub-based projects are classic and not supported in the new portal.",
 T("That every project type gets the new features. Hub-based projects are classic; new work uses Foundry projects.",
   [["New agent work, new portal","Project type","Foundry project"],["Existing classic workloads","Hub-based","Keep, plan to migrate"],["Standalone Azure OpenAI","Not in new portal","Upgrade to a Foundry resource"]],
   [["\"build agents in the new Foundry portal\"","Rules out hub-based and standalone resources."],["\"current agent features\"","Foundry projects get new investment."]],
   "New work → Foundry project in a Foundry resource. Hubs and standalone Azure OpenAI are classic.",
   "Design Azure infrastructure for AI apps and agent-based solutions."),
 "Move into the new building rather than adding a room to the old one.", L+"what-is-foundry"),
single("m1-03", D1, "A partner team must call one specific agent in your Foundry project, but no other agents and no build actions. How should you grant access?",
 ["Foundry Agent Consumer scoped to that agent","Foundry Agent Consumer scoped to the project","Foundry User scoped to that agent","Foundry User scoped to the project"], 1,
 "right role, but project scope lets them call every agent in the project.",
 T("That roles only attach to resources and projects. Agent-scoped assignments limit endpoint access to one agent.",
   [["Call one agent only","Endpoint access, narrow scope","Agent Consumer at agent scope"],["Call any agent in the project","Wider scope","Agent Consumer at project scope"],["Build agents","Data actions","Foundry User"]],
   [["\"one specific agent ... no other agents\"","Needs agent scope."],["\"no build actions\"","Rules out Foundry User."]],
   "Least privilege has two parts: the smallest role and the smallest scope. Roles can be assigned at agent scope.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "Give them the key to one room, not the whole floor.", L+"concepts/rbac-foundry"),
single("m1-04", D1, "A model deployment answers from retrieved documents. You must stop ungrounded answers from reaching users at runtime. Preview features are allowed. What should you configure?",
 ["A groundedness control in the deployment's guardrail","The Groundedness Pro evaluator on a dataset","The Relevance evaluator in continuous evaluation on live traffic","Prompt Shields for indirect attacks"], 1,
 "it measures groundedness pass/fail, but offline on a dataset; it doesn't block anything at runtime.",
 T("That evaluators protect users. Evaluators measure; guardrails act at runtime.",
   [["Block ungrounded output live","Runtime control","Groundedness guardrail (preview, models)"],["Measure groundedness before release","Offline","Groundedness / Groundedness Pro evaluators"],["Hidden instructions in documents","Attack, not grounding","Prompt Shields"]],
   [["\"stop ... from reaching users at runtime\"","Needs a guardrail, not an evaluator."],["\"Preview features are allowed\"","The groundedness guardrail is preview."]],
   "Block at runtime = guardrail. Measure = evaluator.",
   "Configure safety filters, guardrails, risk detection, and content moderation."),
 "A smoke alarm reports a fire; a sprinkler puts it out.", L+"guardrails/guardrails-overview"),
single("m1-05", D1, "Before release, security wants one number showing how often adversarial prompts succeed against your agent. What should you run, and what do you report?",
 ["The AI Red Teaming Agent, reporting attack success rate","The indirect attack evaluator, reporting its score","Prompt Shields in production, reporting how many attacks it blocked","A Content Safety blocklist, reporting hits"], 1,
 "it scores one risk on an existing dataset; it doesn't generate attacks against the agent.",
 T("That a safety evaluator simulates attackers. The red-teaming agent generates attacks and measures how many succeed.",
   [["How often attacks succeed, pre-release","Simulated attacks","AI Red Teaming Agent, ASR"],["Indirect-attack risk in a dataset","One evaluator","Indirect attack evaluator"],["Attacks blocked in production","Runtime","Prompt Shields metrics"]],
   [["\"Before release\"","Rules out production signals."],["\"how often adversarial prompts succeed\"","Attack success rate."]],
   "Pre-release attack resistance = AI Red Teaming Agent; metric = Attack Success Rate.",
   "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling."),
 "Hire a friendly burglar and count how many doors he opens.", L+"how-to/develop/run-ai-red-teaming-cloud"),
dict(id="m1-06", type="multi", pick=2, skill=D1,
 stem="A steady, high-volume workload on a Global Standard deployment gets frequent HTTP 429 responses during the day. Which two actions reduce how often the 429s happen?",
 options=["Move the steady load to a Provisioned deployment","Request a higher quota for that model and type","Honour Retry-After and back off exponentially","Switch the app from Entra ID authentication to a resource API key","Turn off the guardrail on the deployment"],
 answer=[0, 1], runner=2, runnerWhy="it's the right way to handle a 429, but it doesn't make 429s less frequent.",
 think=T("That handling an error reduces it. Retrying copes with 429s; capacity fixes them.",
   [["429s happen","Rate limit","Back off, honour Retry-After"],["429s happen often","Not enough capacity","More quota or Provisioned"],["Auth or safety settings","Unrelated","No effect on 429s"]],
   [["\"reduce how often\"","Asks for capacity fixes, not retry handling."]],
   "Handle 429s with backoff; reduce them with more quota or reserved capacity.",
   "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads."),
 eli5="A wider road reduces traffic jams; waiting patiently only helps you through them.", learn=L+"foundry-models/quotas-limits"),
dict(id="m1-07", type="yesno", skill=D1, stem="For each statement about Foundry guardrails, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Guardrails for model deployments are generally available.", answer=True, why="Model guardrails are GA; agent guardrails are preview."),
  dict(text="Tool call and tool response intervention points apply to agents only.", answer=True, why="Models have no tool checkpoints."),
  dict(text="The annotate-only action can be used in a guardrail assigned to an agent.", answer=False, why="Annotate-only is for models; agents need annotate and block."),
  dict(text="Microsoft.DefaultV2 is the default guardrail.", answer=True, why="It applies when nothing else is assigned.")],
 think=T("That guardrails behave the same for models and agents. Agents add tool checkpoints and lose annotate-only.", None, None,
   "Models: GA, input/output, annotate or block. Agents: preview, adds tool call/response, block only.", "Configure safety filters, guardrails, risk detection, and content moderation."),
 eli5="Agents get extra checkpoints at the tool desk, and the checkpoints there can't just take notes.", learn=L+"guardrails/guardrails-overview"),
dict(id="m1-08", type="yesno", skill=D1, stem="For each statement about Foundry quotas and cost, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Quota is scoped per subscription, region, model and deployment type.", answer=True, why="All four define the pool."),
  dict(text="Reasoning tokens are billed as input tokens.", answer=False, why="They're billed as output tokens."),
  dict(text="Evaluations in the agents playground are on by default and billed.", answer=True, why="Turn them off if you don't want the cost."),
  dict(text="Viewing quota requires Cognitive Services Usages Reader at subscription scope.", answer=True, why="Quota is a subscription-level view.")],
 think=T("That cost is just input plus visible output. Reasoning tokens and playground evaluations add to it.", None, None,
   "Quota: per subscription, region, model, type. Reasoning tokens = output. Playground evaluations cost money.", "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads."),
 eli5="The thinking out loud is charged like talking.", learn=L+"foundry-models/quotas-limits"),
dict(id="m1-09", type="code", skill=D1, stem="Complete the code so a service calls a Foundry model through the v1 endpoint without keys or api-version strings.",
 code='token_provider = get_bearer_token_provider(\n    DefaultAzureCredential(), "[[0]]")\nclient = OpenAI(\n    base_url="https://contoso.openai.azure.com/[[1]]",\n    api_key=token_provider)',
 blanks=[dict(options=["https://ai.azure.com/.default","https://management.azure.com/.default","https://graph.microsoft.com/.default"], answer=0, why="the token scope for Foundry model calls."),
         dict(options=["openai/v1/","openai/deployments/","api/projects/claims/"], answer=0, why="the v1 route, used with the standard OpenAI client.")],
 think=T("That Azure needs its own client class and a monthly version. The v1 route works with the standard OpenAI client.", None, None,
   "v1: OpenAI() + base_url .../openai/v1/ + Entra token provider; no api-version.", "Configure an application to connect to a Foundry project."),
 eli5="Right badge for the right building, and the new front door.", learn=L+"openai/api-version-lifecycle"),
dict(id="m1-10", type="code", skill=D1, stem="Complete the commands: deploy a model for overnight bulk scoring of EU claims at the lowest price, and let the pipeline identity build and run evaluations with least privilege.",
 code='az cognitiveservices account deployment create -g rg -n contoso \\\n  --deployment-name nightly --model-name gpt-5-mini --model-format OpenAI \\\n  --sku-name [[0]] --sku-capacity 100\naz role assignment create --assignee $PIPELINE_ID \\\n  --role "[[1]]" --scope $PROJECT_ID',
 blanks=[dict(options=["DataZoneBatch","GlobalBatch","DataZoneStandard"], answer=0, why="EU residency plus batch pricing."),
         dict(options=["Foundry User","Foundry Account Owner","Azure AI Developer"], answer=0, why="builds and runs evaluations; Account Owner has no data actions; Azure AI Developer is for hubs.")],
 think=T("That Batch alone satisfies residency. Global Batch can process anywhere; the EU needs a Data Zone type.", None, None,
   "Residency + bulk = Data Zone Batch. Build and evaluate = Foundry User.", "Choose appropriate deployment options."),
 eli5="Cheap overnight post that stays inside Europe, and a builder's badge, not a landlord's.", learn=L+"foundry-models/concepts/deployment-types"),
dict(id="m1-11", type="order", skill=D1, stem="You must make inbound access to a Foundry resource private without cutting users off midway. Put the four actions in order.",
 pool=["Create a private endpoint for the resource in your VNet","Configure the private DNS zone for the endpoint","Confirm access works from inside the VNet","Disable public network access on the resource","Switch the agents to the Standard setup","Rotate the resource's API keys"],
 answer=[0, 1, 2, 3],
 think=T("That you disable public access first. Turn it off last, after private access is proven.", None, None,
   "Private endpoint → DNS → verify → disable public access.", "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="Build the new road and check it works before closing the old one."),
# ---------------- D2 ----------------
single("m1-12", D2, "You call a model through the Responses API without a stored agent. The next call must continue the same exchange without resending the history. What should you pass?",
 ["previous_response_id from the last response","The conversation ID from conversations.create","A thread_id from the earlier exchange","A system message summarising the history"], 1,
 "it also works, but only if you created a conversation first; the stem continues a single response chain.",
 T("That continuing a chat always needs a conversation object. A response can also be chained to the previous one by ID.",
   [["Continue from the last response","Response chain","previous_response_id"],["Persist history across sessions","Conversation object","conversation ID"],["Classic API","Old vocabulary","thread_id"]],
   [["\"without a stored agent\"","A plain Responses call."],["\"continue the same exchange\"","Chain from the last response."]],
   "Chain one exchange with previous_response_id; keep long-lived history in a conversation.",
   "Integrate generative workflows into applications by using Foundry SDKs and connectors."),
 "Say 'as I was saying' instead of retelling the whole story.", L+"openai/api-version-lifecycle"),
single("m1-13", D2, "Your team has a working LangGraph agent packaged in a container. You want Foundry to run it with Foundry identity, tracing and publishing. What should you use?",
 ["A hosted agent","A prompt agent","A Foundry Workflow","Connected Agents"], 1,
 "it wins if the agent is only instructions plus tools; here the logic is already code.",
 T("That Foundry only runs agents it defines. Hosted agents run your own code.",
   [["Existing agent code","Bring your own","Hosted agent"],["Instructions + tools only","Declarative","Prompt agent"],["New orchestration code","Framework","Agent Framework"]],
   [["\"working LangGraph agent packaged in a container\"","Your code."],["\"Foundry ... identity, tracing and publishing\"","Hosted, not rebuilt."]],
   "Your code → hosted agent. Declarative → prompt agent.",
   "Build agents that integrate retrieval, function-calling, and conversation memory."),
 "Rent the shop for your own chef instead of hiring theirs.", L+"agents/overview"),
single("m1-14", D2, "An agent must analyse a spreadsheet a user uploads and return a chart. The analysis code must not be able to reach the internet. Which tool should you add?",
 ["Code interpreter","Azure Functions tool","OpenAPI tool","Grounding with Bing Search"], 1,
 "it runs your own code in Azure, but needs the Standard setup and isn't a sandbox for user files.",
 T("That every code task needs your own function. Code interpreter is a sandbox with no outbound network.",
   [["Run Python on user data, no internet","Sandbox","Code interpreter"],["Run your own logic in Azure","Your code","Azure Functions tool"],["Call an API","Integration","OpenAPI tool"]],
   [["\"analyse a spreadsheet ... return a chart\"","Run code on a file."],["\"must not be able to reach the internet\"","Code interpreter has no outbound network."]],
   "Sandboxed analysis → code interpreter (1-hour session, 30-minute idle timeout).",
   "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions."),
 "A calculator in a locked room.", L+"agents/overview"),
single("m1-15", D2, "An agent must call lookup_policy before every answer. A sentence in the instructions works most of the time, but audits find misses. What should you configure?",
 ["Set tool_choice to required","Set tool_choice to auto","Add more emphasis to the instructions","Set tool_choice to none"], 2,
 "it often helps, but instructions are guidance, not enforcement; audits still find misses.",
 T("That a stronger prompt guarantees behaviour. tool_choice enforces a tool call.",
   [["Must always call a tool","Enforcement","tool_choice=required"],["Model decides","Default","auto"],["Must never call tools","Final answer","none"]],
   [["\"must call ... before every answer\"","Enforce it."],["\"works most of the time\"","Prompting is the runner-up that already failed."]],
   "Guarantee a tool call with tool_choice=required; prompts only guide.",
   "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 "A rule on the door works better than a reminder on the wall.", L+"agents/overview"),
single("m1-16", D2, "An agent should remember each customer's preferred language across separate conversations. Preview features are allowed. What should you use?",
 ["Agent memory with a user profile","Conversation history in one conversation","File search over a preferences file","A Foundry IQ knowledge base"], 1,
 "it remembers within one conversation, not across separate ones.",
 T("That conversations persist forever across chats. Cross-conversation facts about a user belong in memory.",
   [["Facts about a user across chats","Persistent, personal","Memory (preview)"],["Within one chat","Conversation state","Conversation"],["Company knowledge","Shared","Foundry IQ"]],
   [["\"across separate conversations\"","Rules out one conversation's history."],["\"Preview features are allowed\"","Memory is preview."]],
   "About the user, across chats → memory. Within a chat → conversation.",
   "Build agents that integrate retrieval, function-calling, and conversation memory."),
 "A regular customer's usual order, remembered by the barista.", L+"agents/concepts/what-is-memory"),
single("m1-17", D2, "Requests that match 20 known FAQ intents must get the same approved answer every time; all other requests go to a model. What should you build?",
 ["A rules step first, with the model as fallback","Model router across several models","One model deployment with temperature set to zero for every request","A fine-tuned model trained on the FAQs"], 1,
 "it picks between models, but every answer still comes from a model.",
 T("That temperature zero makes a model deterministic. Only rules guarantee the same approved answer.",
   [["Answer must be identical every time","Determinism","Rules first"],["Pick the cheapest capable model","Routing","Model router"],["Domain style","Training","Fine-tuning"]],
   [["\"same approved answer every time\"","Rules, not a model."],["\"all other requests go to a model\"","Hybrid: rules, then model."]],
   "Orchestrate hybrid flows: rules where answers must be fixed, models where they can't be.",
   "Orchestrate multiple models, flows, or hybrid LLM and rules engines."),
 "Use the printed timetable for train times; ask the clerk only when it's not on the board.", L+"openai/concepts/model-router"),
dict(id="m1-18", type="multi", pick=2, skill=D2,
 stem="You need to see agent traces in the Foundry portal and let an engineer query them with KQL, without changing application code. Which two actions do you take?",
 options=["Connect Application Insights to the project","Grant the engineer Log Analytics Reader","Add OpenTelemetry spans in the client code","Enable continuous evaluation on the agent","Grant the engineer Cognitive Services OpenAI User"],
 answer=[0, 1], runner=2, runnerWhy="client spans add detail, but the stem rules out code changes and server-side tracing already works.",
 think=T("That tracing needs instrumentation code. Connecting App Insights turns on server-side traces.",
   [["Traces with no code change","Server-side","Connect App Insights"],["Query traces","Permissions","Log Analytics Reader"],["Extra custom detail","Client-side","OpenTelemetry SDK"]],
   [["\"without changing application code\"","Rules out client spans."],["\"query them with KQL\"","Needs Log Analytics Reader."]],
   "Server-side tracing: connect App Insights. Reading traces: Log Analytics Reader.",
   "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns."),
 eli5="Plug in the recorder, then give the auditor a reading card.", learn=L+"observability/how-to/trace-agent-setup"),
dict(id="m1-19", type="yesno", skill=D2, stem="For each statement about Foundry Agent Service, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Prompt agents are generally available.", answer=True, why="Prompt agents are GA."),
  dict(text="Changing a prompt agent's definition creates a new agent version.", answer=True, why="Versions are snapshotted automatically."),
  dict(text="Function tools run inside Foundry's managed sandbox.", answer=False, why="Function calling runs in your application."),
  dict(text="Connected Agents is available in the new Agent Service.", answer=False, why="Use the A2A tool or workflows instead.")],
 think=T("That every tool runs in Foundry. Function tools hand the call back to your code.", None, None,
   "Prompt agents GA, versioned. Functions run in your app. Connected Agents → A2A.", "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 eli5="The agent writes the request; your own staff carry it out.", learn=L+"agents/overview"),
dict(id="m1-20", type="yesno", skill=D2, stem="For each statement about reasoning models in Foundry, select Yes if it's true. NOTE: Each correct selection is worth one point.",
 statements=[dict(text="Reasoning models accept the temperature parameter.", answer=False, why="Most reject temperature and top_p."),
  dict(text="max_output_tokens includes reasoning tokens.", answer=True, why="The cap covers thinking and answer."),
  dict(text="Parallel tool calls aren't supported at minimal reasoning effort.", answer=True, why="A documented limitation."),
  dict(text="You should send both a system message and a developer message.", answer=False, why="They're equivalent; send one.")],
 think=T("That reasoning models take the classic sampling knobs. They use effort and output caps instead.", None, None,
   "Reasoning: no temperature/top_p/max_tokens; use reasoning_effort and max_output_tokens.", "Tune generation behavior, such as prompt engineering and adjusting model parameters."),
 eli5="A thinking machine has an effort dial, not a creativity dial.", learn=L+"openai/how-to/reasoning"),
dict(id="m1-21", type="code", skill=D2, stem="Complete the code so your app runs a function the model asks for and returns the result.",
 code='r = client.responses.create(model=m, input=q, tools=[lookup_tool])\ncall = next(i for i in r.output if i.type == "[[0]]")\nresult = lookup_policy(**json.loads(call.arguments))\nr2 = client.responses.create(model=m, tools=[lookup_tool], previous_response_id=r.id,\n    input=[{"type": "[[1]]", "call_id": call.call_id, "output": json.dumps(result)}])',
 blanks=[dict(options=["function_call","tool_use","mcp_approval_request"], answer=0, why="the Responses API item for a function the model wants called; tool_use is the Claude API's name."),
         dict(options=["function_call_output","tool_result","mcp_approval_response"], answer=0, why="returns your function's result; tool_result is the Claude API's name.")],
 think=T("That tool calls look the same in every API. Claude uses tool_use/tool_result; the Responses API uses function_call/function_call_output.", None, None,
   "Responses API: function_call in, function_call_output back, chained with previous_response_id.", "Build agents that integrate retrieval, function-calling, and conversation memory."),
 eli5="Same game, different names for the pieces.", learn=L+"agents/overview"),
dict(id="m1-22", type="code", skill=D2, stem="Complete the code so the client talks to a published prompt agent named fnol.",
 code='oa = project.get_openai_client([[0]]="fnol")\nconv = oa.conversations.create()\nr = oa.responses.create(conversation=conv.id, input=text)\n# or bind per call on an unbound client:\nr = client.responses.create(input=text,\n    extra_body={"agent_reference": {"name": "fnol", "type": "[[1]]"}})',
 blanks=[dict(options=["agent_name","agent_id","assistant_id"], answer=0, why="the client is bound by agent name."),
         dict(options=["agent_reference","agent_version","prompt_agent"], answer=0, why="the reference type for binding a call to an agent.")],
 think=T("That agents are addressed by an assistant ID. In v2 you bind by name.", None, None,
   "Bind a client with get_openai_client(agent_name=...), or a call with an agent_reference.", "Integrate generative workflows into applications by using Foundry SDKs and connectors."),
 eli5="Call the agent by name, not by an old staff number.", learn=L+"quickstarts/get-started-code"),
dict(id="m1-23", type="order", skill=D2, stem="You change a prompt agent's instructions and must release only if quality holds. Put the four actions in order.",
 pool=["Update the instructions, creating a new agent version","Run a cloud evaluation on the golden dataset for the new version","Compare the results with the previous version's run","Point the application to the new version","Delete the previous agent version","Turn off tracing during the evaluation"],
 answer=[0, 1, 2, 3],
 think=T("That you release, then measure. Evaluate the new version against the old one first.", None, None,
   "New version → evaluate → compare → release. Keep the old version for rollback.", "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis."),
 eli5="Taste the new recipe next to the old one before changing the menu."),
]
GOAL = ("Agents must answer from current policy content held in an Azure AI Search index, a Blob container and OneLake. "
        "**Goal:** use only generally available features, and the agent must connect to the knowledge without storing keys.")
def S(i, sol, ans, prem, apply, rule):
    return dict(id="m1-s" + str(i), type="solution", skill=D2, scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(prem, [["Several sources, GA","Knowledge base","Extractive retrieval"],["Want a composed answer from the KB","Preview","Answer synthesis"],["User-uploaded files","Wrong tool","File search"]],
                        apply, rule, "Connect retrieval pipelines directly to workflows and agent tools."),
                eli5="The librarian may fetch pages from three shelves; writing the essay for you is still being tested.", learn=L+"agents/concepts/what-is-foundry-iq")
A += [
 S(1, "Create a knowledge base over the three sources with extractive retrieval, and connect the agent to its MCP endpoint using the project's managed identity.", True,
   "That multi-source retrieval must be preview. Knowledge bases with extractive retrieval over these sources are GA.",
   [["\"index, a Blob container and OneLake\"","All GA knowledge sources."],["\"project's managed identity\"","No keys: met."]], "GA knowledge base: extractive retrieval; agents connect over MCP with managed identity."),
 S(2, "Create the same knowledge base, enable answer synthesis, and connect with the project's managed identity.", False,
   "That synthesis is part of GA. It's still preview.",
   [["\"enable answer synthesis\"","Preview: not met."],["\"managed identity\"","Keyless: met, but the first half fails."]], "Answer synthesis and query planning are preview."),
 S(3, "Upload copies of all documents to a file search vector store attached to the agent.", False,
   "That file search serves organisational knowledge. It's for documents users provide, and copies go stale.",
   [["\"copies of all documents\"","Not current content."],["\"file search\"","Wrong tool for curated sources."]], "File search = user-provided files, not curated organisational content."),
]
