"""Mock Exam #1, part A: D1 and D2 items outside the case studies. All items original.
Exam level: 40-60 word stems, two or three constraints per stem, near-miss distractors."""
from bank_d1 import T
L = "https://learn.microsoft.com/en-us/azure/foundry/"
D1, D2 = "D1 · Plan and manage", "D2 · GenAI and agents"

def single(id, skill, stem, options, runner, runnerWhy, think, eli5, learn):
    return dict(id=id, type="single", skill=skill, stem=stem, options=options, answer=0, runner=runner, runnerWhy=runnerWhy, think=think, eli5=eli5, learn=learn)

NOTE = " NOTE: Each correct selection is worth one point."
A = [
single("m1-01", D1, "You have a Microsoft Foundry project that serves a broker chat app through a model router deployment. About 70% of questions are short policy lookups; the rest need multi-step reasoning. Finance asks you to reduce spend by at least 30% without preventing hard questions from reaching larger models. What should you configure?",
 ["Set the router's routing mode to Cost","Limit the router's model subset to small models","Set the router's routing mode to Quality","Replace the router with a gpt-5-mini deployment"], 1,
 "it cuts cost too, but it stops hard questions from ever reaching a larger model, which the stem forbids.",
 T("That the only way to save money is to remove expensive models. The router's mode already trades quality for cost on each prompt.",
   [["Cut spend, keep large models available","Routing mode","Cost mode"],["Some models must never be used","Eligibility","Model subset"],["Quality matters most","Routing mode","Quality mode"]],
   [["\"reduce spend by at least 30%\"","Rules out Quality mode."],["\"without preventing hard questions from reaching larger models\"","Rules out a small-model subset and a single small model."]],
   "Model router modes: Balanced (default), Quality, Cost. A model subset limits which models are eligible at all.",
   "Choose an appropriate model for each task, including large language models (LLMs), small language models, multimodal models, and Foundry Tools."),
 "Tell the dispatcher to prefer the cheap courier, but still allow the van for big parcels.", L+"openai/concepts/model-router"),
single("m1-03", D1, "Your Foundry project contains six agents. A partner application, which runs with a user-assigned managed identity, must invoke only the claims-triage agent. The partner must not be able to call the other agents, create or change agents, or read evaluation results. You need to grant access by following the principle of least privilege. What should you do?",
 ["Assign Foundry Agent Consumer to the identity, scoped to the claims-triage agent","Assign Foundry Agent Consumer to the identity, scoped to the project","Assign Foundry User to the identity, scoped to the claims-triage agent","Assign Cognitive Services OpenAI User to the identity on the resource"], 1,
 "right role, but project scope lets the partner call all six agents.",
 T("That roles only attach to resources and projects. Agent-scoped assignments limit access to one agent.",
   [["Call one agent only","Endpoint access, narrow scope","Agent Consumer at agent scope"],["Call any agent in the project","Wider scope","Agent Consumer at project scope"],["Build agents, run evaluations","Data actions","Foundry User"]],
   [["\"invoke only the claims-triage agent\"","Agent scope."],["\"must not ... create or change agents\"","Rules out Foundry User."]],
   "Least privilege has two parts: the smallest role and the smallest scope.",
   "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 "Give them the key to one room, not the whole floor.", L+"concepts/rbac-foundry"),
single("m1-04", D1, "A Foundry model deployment answers employee questions by using passages retrieved by your application. Compliance requires that answers not supported by the retrieved passages are stopped before users see them, starting this week. Your release pipeline already runs the Groundedness Pro evaluator on a test dataset. Preview features are allowed. What should you add?",
 ["A groundedness control in the deployment's guardrail","Continuous evaluation with Groundedness Pro on live traffic","A higher Groundedness Pro pass threshold in the pipeline","Prompt Shields for indirect attacks in the guardrail"], 1,
 "it scores live answers, but after users have seen them; evaluators measure, they don't block.",
 T("That an evaluator on live traffic protects users. Evaluators report; guardrails act on the response.",
   [["Stop ungrounded answers live","Runtime control","Groundedness guardrail (preview)"],["Measure groundedness","Offline or continuous","Groundedness / Groundedness Pro evaluators"],["Hidden instructions in passages","Attack, not grounding","Prompt Shields"]],
   [["\"stopped before users see them\"","Needs a runtime control."],["\"Preview features are allowed\"","The groundedness guardrail control is preview."]],
   "Block at runtime = guardrail. Measure = evaluator, offline or continuous.",
   "Configure safety filters, guardrails, risk detection, and content moderation."),
 "A smoke alarm reports a fire; a sprinkler puts it out.", L+"guardrails/guardrails-overview"),
single("m1-05", D1, "Before release, your security team needs a report showing how often adversarial prompts, such as jailbreaks and attempts to extract data, succeed against your agent, broken down by attack strategy. The attacks must be generated automatically rather than written by hand. What should you run, and which metric should you report?",
 ["The AI Red Teaming Agent, reporting attack success rate","The indirect attack evaluator, reporting its defect rate","Prompt Shields in production, reporting blocked requests","A content safety evaluation, reporting average severity"], 1,
 "it scores one risk on a dataset you already have; it doesn't generate attacks or break results down by strategy.",
 T("That a safety evaluator simulates attackers. The red-teaming agent generates attacks and measures how many succeed.",
   [["How often attacks succeed, pre-release","Simulated attacks","AI Red Teaming Agent, ASR"],["Risk in an existing dataset","One evaluator","Indirect attack evaluator"],["Attacks blocked in production","Runtime","Prompt Shields"]],
   [["\"Before release\"","Rules out production signals."],["\"generated automatically\"","Rules out evaluators on your own dataset."],["\"broken down by attack strategy\"","The red-teaming report does this."]],
   "Pre-release attack resistance = AI Red Teaming Agent; metric = Attack Success Rate (ASR).",
   "Apply responsible AI instrumentation, including evaluators, safety evaluations, and explanation tooling."),
 "Hire a friendly burglar and count how many doors he opens, and how.", L+"how-to/develop/run-ai-red-teaming-cloud"),
dict(id="m1-06", type="multi", pick=2, skill=D1,
 stem="A claims-summary service sends a steady 400 requests per minute, with peaks of 900, to a gpt-5-mini Global Standard deployment. During peaks, the service receives HTTP 429 responses and user requests time out. You need to reduce how often 429 responses occur. Which two actions should you perform? Each correct answer presents a complete solution.",
 options=["Move the steady load to a Provisioned deployment","Request a quota increase for that model and type","Honour Retry-After and back off exponentially","Move the deployment to the Data Zone Standard type","Switch the service from Entra ID to API keys"],
 answer=[0, 1], runner=2, runnerWhy="it's the right way to handle a 429, but it doesn't make 429s less frequent.",
 think=T("That handling an error reduces it. Retrying copes with 429s; capacity fixes them.",
   [["429s happen","Rate limit","Back off, honour Retry-After"],["429s happen often","Not enough capacity","More quota or Provisioned"],["Residency type","Data Zone","Usually less quota than Global, not more"]],
   [["\"reduce how often 429 responses occur\"","Asks for capacity, not retry handling."],["\"steady 400 requests per minute\"","Predictable load suits Provisioned."]],
   "Handle 429s with backoff; reduce them with more quota or reserved capacity.",
   "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads."),
 eli5="A wider road reduces traffic jams; waiting patiently only helps you through them.", learn=L+"foundry-models/quotas-limits"),
dict(id="m1-07", type="yesno", skill=D1, stem="You are configuring guardrails for a Foundry project that hosts both model deployments and agents. For each of the following statements, select Yes if the statement is true. Otherwise, select No." + NOTE,
 statements=[dict(text="Guardrails assigned to model deployments are generally available.", answer=True, why="Model guardrails are GA; agent guardrails are preview."),
  dict(text="The tool call and tool response intervention points can be used only in guardrails assigned to agents.", answer=True, why="Models have no tool checkpoints."),
  dict(text="A guardrail assigned to an agent can use the annotate-only action for jailbreak detection.", answer=False, why="Annotate-only is for models; agents use annotate and block."),
  dict(text="An agent with no guardrail assigned inherits the guardrail of its model deployment.", answer=True, why="Guardrails inherit when none is assigned to the agent.")],
 think=T("That guardrails behave the same for models and agents. Agents add tool checkpoints and lose annotate-only.", None, None,
   "Models: GA, input/output, annotate or block. Agents: preview, adds tool call/response, block. No agent guardrail → inherits the model's.", "Configure safety filters, guardrails, risk detection, and content moderation."),
 eli5="Agents get extra checkpoints at the tool desk, and the guards there can't just take notes.", learn=L+"guardrails/guardrails-overview"),
dict(id="m1-08", type="yesno", skill=D1, stem="You are estimating quota and cost for a Foundry workload that uses a reasoning model and the agents playground. For each of the following statements, select Yes if the statement is true. Otherwise, select No." + NOTE,
 statements=[dict(text="Quota is allocated per subscription, region, model, and deployment type.", answer=True, why="All four define the pool."),
  dict(text="Reasoning tokens are billed at the input token rate.", answer=False, why="They're billed as output tokens."),
  dict(text="Evaluations that run in the agents playground are enabled by default and incur charges.", answer=True, why="Turn them off if you don't want the cost."),
  dict(text="Prompt caching must be enabled on the deployment before cached input tokens are discounted.", answer=False, why="It's on by default for supported models.")],
 think=T("That cost is just input plus visible output, and that discounts need switching on. Reasoning tokens bill as output; caching is automatic.", None, None,
   "Quota: per subscription, region, model, type. Reasoning tokens = output. Playground evaluations cost money. Caching is on by default.", "Manage quotas, scaling, rate limits, and cost footprints for model and agent workloads."),
 eli5="The thinking out loud is charged like talking, and the loyalty discount applies without asking.", learn=L+"foundry-models/quotas-limits"),
dict(id="m1-09", type="code", skill=D1, stem="You are writing a Python service that calls a gpt-5-mini deployment in a Foundry resource named contoso. Security policy forbids API keys, and the team wants to stop maintaining api-version strings in code. You need to complete the client initialization. How should you complete the code?",
 code='token_provider = get_bearer_token_provider(\n    DefaultAzureCredential(), "[[0]]")\nclient = OpenAI(\n    base_url="https://contoso.openai.azure.com/[[1]]",\n    api_key=token_provider)\nr = client.responses.create(model="gpt-5-mini", input=prompt)',
 blanks=[dict(options=["https://ai.azure.com/.default","https://management.azure.com/.default","https://graph.microsoft.com/.default"], answer=0, why="the token scope for Foundry model calls; management is for ARM, graph for Microsoft Graph."),
         dict(options=["openai/v1/","openai/deployments/gpt-5-mini/","api/projects/claims/"], answer=0, why="the v1 route, used with the standard OpenAI client and no api-version.")],
 think=T("That Azure needs its own client class and a monthly version string. The v1 route works with the standard OpenAI client.", None, None,
   "v1: OpenAI() + base_url .../openai/v1/ + Entra token provider; no api-version.", "Configure an application to connect to a Foundry project."),
 eli5="Right badge for the right building, and the new front door.", learn=L+"openai/api-version-lifecycle"),
dict(id="m1-10", type="code", skill=D1, stem="Each night, a pipeline scores 2 million EU customer claims with gpt-5-mini. Results are needed by morning, EU data must be processed inside the EU, and cost must be minimised. The pipeline's identity must also create and run evaluations, with least privilege. How should you complete the commands?",
 code='az cognitiveservices account deployment create -g rg -n contoso \\\n  --deployment-name nightly --model-name gpt-5-mini --model-format OpenAI \\\n  --sku-name [[0]] --sku-capacity 100\naz role assignment create --assignee $PIPELINE_ID \\\n  --role "[[1]]" --scope $PROJECT_ID',
 blanks=[dict(options=["DataZoneBatch","GlobalBatch","DataZoneStandard"], answer=0, why="EU residency plus batch pricing; Global Batch can process anywhere, Data Zone Standard isn't discounted."),
         dict(options=["Foundry User","Foundry Account Owner","Azure AI Developer"], answer=0, why="builds and runs evaluations; Account Owner has no data actions; Azure AI Developer is for hub projects.")],
 think=T("That Batch alone satisfies residency. Global Batch can process anywhere; the EU needs a Data Zone type.", None, None,
   "Residency + overnight bulk = Data Zone Batch. Build and evaluate = Foundry User.", "Choose appropriate deployment options."),
 eli5="Cheap overnight post that stays inside Europe, and a builder's badge, not a landlord's.", learn=L+"foundry-models/concepts/deployment-types"),
dict(id="m1-11", type="order", skill=D1, stem="Users currently reach a Foundry resource over its public endpoint. Security requires that all inbound access move to a private endpoint in your hub virtual network, and users must not lose access at any point during the change. Which four actions should you perform in sequence?",
 pool=["Create a private endpoint for the resource in the virtual network","Link the private DNS zone for the endpoint to the network","Confirm the resource resolves and responds from inside the network","Disable public network access on the resource","Switch the agents to the Standard setup with your own storage","Rotate the resource's API keys"],
 answer=[0, 1, 2, 3],
 think=T("That you disable public access first. Turn it off last, after private access is proven.", None, None,
   "Private endpoint → DNS → verify → disable public access.", "Configure security, including managed identity, private networking, keyless credentials, and role policies."),
 eli5="Build the new road and check it works before closing the old one."),
# ---------------- D2 ----------------
single("m1-12", D2, "A stateless microservice calls a gpt-5 deployment directly through the Responses API, without an agent or a conversation object. Each user exchange takes two or three calls, and to keep input tokens down the service must not resend earlier messages. History doesn't need to outlive the exchange. What should each follow-up call include?",
 ["The previous_response_id of the last response","A conversation ID created by conversations.create","The thread_id returned by the first call","The full message history with store set to false"], 1,
 "it works, but it creates a durable conversation object the stem says isn't needed; chaining by response ID is lighter.",
 T("That continuing a chat always needs a conversation object. A response can be chained to the previous one by ID.",
   [["Chain a short exchange","Response chain","previous_response_id"],["History across sessions","Durable state","Conversation object"],["Classic Assistants API","Old vocabulary","thread_id"]],
   [["\"without an agent or a conversation object\"","A plain Responses chain."],["\"must not resend earlier messages\"","Rules out sending the full history."],["\"doesn't need to outlive the exchange\"","No durable conversation needed."]],
   "Chain one exchange with previous_response_id; keep long-lived history in a conversation.",
   "Integrate generative workflows into applications by using Foundry SDKs and connectors."),
 "Say 'as I was saying' instead of retelling the whole story.", L+"openai/api-version-lifecycle"),
single("m1-13", D2, "Your team has a working LangGraph agent with custom routing logic, packaged as a container image. You need to run it in Foundry so that it uses the project's managed identity, appears in Foundry tracing, and can be published to Microsoft Teams. You must not rewrite the orchestration logic. What should you create?",
 ["A hosted agent that runs the container image","A prompt agent configured with the same tools","A Foundry Workflow that calls each graph node","An Azure Container App that calls Foundry models"], 1,
 "it gets Foundry identity and publishing, but you'd re-express the routing logic as instructions, which the stem forbids.",
 T("That Foundry only runs agents it defines. Hosted agents run your own code.",
   [["Existing agent code","Bring your own","Hosted agent"],["Instructions + tools only","Declarative","Prompt agent"],["Your own hosting","Outside Foundry","No Foundry publishing or identity"]],
   [["\"packaged as a container image\"","Your code."],["\"must not rewrite the orchestration logic\"","Rules out a prompt agent."],["\"published to Microsoft Teams\"","Needs Foundry agent publishing."]],
   "Your code → hosted agent. Declarative → prompt agent. Workflows retire 1 Dec 2026.",
   "Build agents that integrate retrieval, function-calling, and conversation memory."),
 "Rent the shop for your own chef instead of retraining theirs.", L+"agents/overview"),
single("m1-14", D2, "An agent must let users upload a spreadsheet of claims, calculate loss ratios, and return a chart. Security requires that code written by the model runs in an isolated sandbox with no outbound network access, and the team doesn't want to host or patch any compute. Which tool should you add to the agent?",
 ["Code interpreter","Azure Functions tool running a Python function","OpenAPI tool that calls a Python service","Function calling to pandas code in the app"], 1,
 "it can run Python in Azure, but you host and patch the function app, and it runs your code, not the model's.",
 T("That every code task needs your own function. Code interpreter is a managed sandbox with no outbound network.",
   [["Run model-written Python on user files","Managed sandbox","Code interpreter"],["Run your own logic in Azure","Your compute","Azure Functions tool"],["Call an API","Integration","OpenAPI tool"]],
   [["\"code written by the model\"","Code interpreter runs it."],["\"no outbound network access\"","The sandbox has none."],["\"doesn't want to host or patch any compute\"","Rules out Functions and your own service."]],
   "Sandboxed analysis of user files → code interpreter (1-hour session, 30-minute idle timeout).",
   "Integrate agent tools, including APIs, knowledge stores, search, content understanding, and custom functions."),
 "A calculator in a locked room someone else maintains.", L+"agents/overview"),
single("m1-15", D2, "An agent must call the lookup_policy function before answering any coverage question, because answers must reflect the live policy record. The instructions already say 'Always call lookup_policy first', but an audit of 1,000 traces found 37 answers given without a call. The agent has only this one tool. What should you change?",
 ["Set tool_choice to required","Keep tool_choice auto and strengthen the instructions","Set temperature to 0 on the deployment","Set parallel_tool_calls to false"], 1,
 "it often lowers the miss rate, but instructions guide; they don't guarantee, and the audit already shows misses.",
 T("That a stronger prompt guarantees behaviour. tool_choice enforces a tool call.",
   [["Must always call a tool","Enforcement","tool_choice=required"],["Model decides","Default","auto"],["Run tools one at a time","Ordering","parallel_tool_calls"]],
   [["\"must call ... before answering any coverage question\"","Enforce it."],["\"The instructions already say\"","Prompting is the runner-up that already failed."]],
   "Guarantee a tool call with tool_choice=required; prompts only guide.",
   "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 "A rule on the door works better than a reminder on the wall.", L+"agents/overview"),
single("m1-16", D2, "A travel-insurance agent should greet returning customers in their preferred language and recall their usual destination, across conversations that happen weeks apart. Within one conversation the agent already tracks context. The data must stay in Foundry, and preview features are allowed. What should you add?",
 ["Agent memory scoped to each user","One long-lived conversation reused for each customer","File search over a nightly export of customer profiles","A Foundry IQ knowledge base over the CRM database"], 1,
 "it would carry history forward, but it grows without limit and isn't designed for facts across weeks.",
 T("That a conversation is the right place for long-term facts about a user. Cross-conversation facts belong in memory.",
   [["Facts about a user across chats","Persistent, personal","Memory (preview)"],["Within one chat","Conversation state","Conversation"],["Shared company knowledge","Organisational","Foundry IQ"]],
   [["\"across conversations that happen weeks apart\"","Memory, not a conversation."],["\"preview features are allowed\"","Memory is preview."]],
   "About the user, across chats → memory. Within a chat → conversation.",
   "Build agents that integrate retrieval, function-calling, and conversation memory."),
 "A regular customer's usual order, remembered by the barista.", L+"agents/concepts/what-is-memory"),
single("m1-17", D2, "A bank's chatbot handles 20 regulated FAQ intents, such as fee disclosures, whose answers legal approved word for word and which must never vary. All other questions should be answered by a model. You need to guarantee the regulated answers while keeping model costs low. What should you implement?",
 ["A rules step that returns approved text, with a model as fallback","A model at temperature 0 with the approved answers in its instructions","A model fine-tuned on the approved question-and-answer pairs","Model router in Quality mode across the available models"], 1,
 "it's usually close, but a model can still paraphrase, and every FAQ still costs a model call.",
 T("That temperature zero makes a model deterministic. Only rules guarantee the same approved text.",
   [["Answer must be identical every time","Determinism","Rules first"],["Pick a model per prompt","Routing","Model router"],["Domain style","Training","Fine-tuning"]],
   [["\"must never vary\"","Rules, not a model."],["\"keeping model costs low\"","FAQ hits never call a model."]],
   "Hybrid flows: rules where answers must be fixed, models where they can't be.",
   "Orchestrate multiple models, flows, or hybrid LLM and rules engines."),
 "Use the printed timetable for train times; ask the clerk only when it's not on the board.", L+"openai/concepts/model-router"),
dict(id="m1-18", type="multi", pick=2, skill=D2,
 stem="Your prompt agents run in production. You need agent traces to appear in the Foundry portal, and an on-call engineer must query those traces by using KQL. You must not change or redeploy application code. Which two actions should you perform? Each correct answer presents part of the solution.",
 options=["Connect an Application Insights resource to the project","Grant the engineer Log Analytics Reader on the workspace","Add OpenTelemetry spans to the client application","Enable continuous evaluation on every production agent","Grant the engineer the Foundry Agent Consumer role on the project"],
 answer=[0, 1], runner=2, runnerWhy="client spans add detail, but they need a code change, and server-side tracing already works once App Insights is connected.",
 think=T("That tracing needs instrumentation code. Connecting App Insights turns on server-side agent traces.",
   [["Traces with no code change","Server-side","Connect App Insights"],["Query traces with KQL","Permissions","Log Analytics Reader"],["Extra custom detail","Client-side","OpenTelemetry SDK"]],
   [["\"must not change or redeploy application code\"","Rules out client spans."],["\"query those traces by using KQL\"","Needs Log Analytics Reader."]],
   "Server-side tracing: connect App Insights. Reading traces: Log Analytics Reader.",
   "Set up observability by implementing tracing, token analytics, safety signals, and latency breakdowns."),
 eli5="Plug in the recorder, then give the auditor a reading card.", learn=L+"observability/how-to/trace-agent-setup"),
dict(id="m1-19", type="yesno", skill=D2, stem="You are migrating agents from the classic Assistants-based service to Foundry Agent Service. For each of the following statements, select Yes if the statement is true. Otherwise, select No." + NOTE,
 statements=[dict(text="Prompt agents are generally available.", answer=True, why="Prompt agents are GA."),
  dict(text="Changing a prompt agent's instructions creates a new agent version.", answer=True, why="Versions are snapshotted automatically."),
  dict(text="Function tools execute inside Foundry's managed sandbox.", answer=False, why="Function calling hands the call back to your application."),
  dict(text="Connected Agents is the recommended way to call another agent.", answer=False, why="Use the A2A tool or workflows instead.")],
 think=T("That every tool runs in Foundry. Function tools hand the call back to your code.", None, None,
   "Prompt agents GA, versioned. Functions run in your app. Connected Agents → A2A tool.", "Define agent roles, goals, conversation-tracking approach, and tool schemas."),
 eli5="The agent writes the request; your own staff carry it out.", learn=L+"agents/overview"),
dict(id="m1-20", type="yesno", skill=D2, stem="You are tuning a reasoning model deployment that an agent uses for multi-step claims decisions. For each of the following statements, select Yes if the statement is true. Otherwise, select No." + NOTE,
 statements=[dict(text="You can lower randomness by setting the temperature parameter.", answer=False, why="Most reasoning models reject temperature and top_p."),
  dict(text="The max_output_tokens limit includes reasoning tokens.", answer=True, why="The cap covers thinking and answer."),
  dict(text="Parallel tool calls aren't supported at minimal reasoning effort.", answer=True, why="A documented limitation."),
  dict(text="You should send both a system message and a developer message for best results.", answer=False, why="They're equivalent; send one.")],
 think=T("That reasoning models take the classic sampling knobs. They use effort and output caps instead.", None, None,
   "Reasoning: no temperature/top_p/max_tokens; use reasoning_effort and max_output_tokens.", "Tune generation behavior, such as prompt engineering and adjusting model parameters."),
 eli5="A thinking machine has an effort dial, not a creativity dial.", learn=L+"openai/how-to/reasoning"),
dict(id="m1-21", type="code", skill=D2, stem="Your application calls a model through the Responses API and exposes a lookup_policy function. When the model asks for the function, your code must run it and send the result back so the model can finish its answer, without resending the earlier input. How should you complete the code?",
 code='r = client.responses.create(model=m, input=q, tools=[lookup_tool])\ncall = next(i for i in r.output if i.type == "[[0]]")\nresult = lookup_policy(**json.loads(call.arguments))\nr2 = client.responses.create(model=m, tools=[lookup_tool], previous_response_id=r.id,\n    input=[{"type": "[[1]]", "call_id": call.call_id, "output": json.dumps(result)}])',
 blanks=[dict(options=["function_call","tool_use","mcp_approval_request"], answer=0, why="the Responses API item for a function the model wants called; tool_use is the Claude API's name."),
         dict(options=["function_call_output","tool_result","mcp_approval_response"], answer=0, why="returns your function's result; tool_result is the Claude API's name.")],
 think=T("That tool calls look the same in every API. Claude uses tool_use/tool_result; the Responses API uses function_call/function_call_output.", None, None,
   "Responses API: function_call in, function_call_output back, chained with previous_response_id.", "Build agents that integrate retrieval, function-calling, and conversation memory."),
 eli5="Same game, different names for the pieces.", learn=L+"agents/overview"),
dict(id="m1-23", type="order", skill=D2, stem="You need to change a production prompt agent's instructions. The change may ship only if task adherence on the golden dataset doesn't drop, and you must be able to roll back instantly if users report problems. Which four actions should you perform in sequence?",
 pool=["Update the instructions, which creates a new agent version","Run a cloud evaluation of the new version on the golden dataset","Compare the result with the current version's evaluation run","Point the application to the new agent version","Delete the previous agent version to avoid confusion","Turn off tracing while the evaluation runs"],
 answer=[0, 1, 2, 3],
 think=T("That you release, then measure. Evaluate the new version against the old one first, and keep the old one.", None, None,
   "New version → evaluate → compare → release. Keep the old version for rollback.", "Integrate monitoring into deployed agents, evaluate agent behavior, and perform error analysis."),
 eli5="Taste the new recipe next to the old one before changing the menu, and keep the old recipe card."),
]
GOAL = ("You have agents that must answer from current policy content stored in an Azure AI Search index, an Azure Blob Storage container, and a OneLake lakehouse. "
        "Content changes daily. **Goal:** use only generally available features, keep answers current, and connect the agents to the knowledge without storing keys.")
def S(i, sol, ans, prem, apply, rule):
    return dict(id="m1-s" + str(i), type="solution", skill=D2, scenario=GOAL, stem="**Proposed solution:** " + sol + " Does this meet the goal?", answer=ans,
                think=T(prem, [["Several sources, GA","Knowledge base","Extractive retrieval"],["Composed answer from the KB","Preview","Answer synthesis"],["User-uploaded files","Wrong tool","File search"]],
                        apply, rule, "Connect retrieval pipelines directly to workflows and agent tools."),
                eli5="The librarian may fetch pages from three shelves; writing the essay for you is still being tested.", learn=L+"agents/concepts/what-is-foundry-iq")
A += [
 S(1, "You create a knowledge base over the three sources that uses extractive retrieval, and you connect each agent to the knowledge base's MCP endpoint by using the project's managed identity.", True,
   "That multi-source retrieval must be preview. Knowledge bases with extractive retrieval over these sources are GA.",
   [["\"extractive retrieval\"","GA: met."],["\"project's managed identity\"","No keys: met."],["Sources read in place","Current content: met."]], "GA knowledge base: extractive retrieval; agents connect over MCP with managed identity."),
 S(2, "You create the same knowledge base, enable answer synthesis so the agents receive composed answers, and connect each agent by using the project's managed identity.", False,
   "That synthesis is part of GA. It's still preview.",
   [["\"enable answer synthesis\"","Preview: not met."],["\"managed identity\"","Keyless is met, but one failure is enough."]], "Answer synthesis and query planning are preview."),
 S(3, "You export all documents nightly to a file search vector store attached to each agent, and the agents read the store by using the project's managed identity.", False,
   "That file search serves organisational knowledge. It's for documents users provide, and nightly copies lag daily changes.",
   [["\"export all documents nightly\"","Copies lag: currency at risk."],["\"file search\"","Wrong tool for curated sources."]], "File search = user-provided files, not curated organisational content."),
]
